<?php 
    $this->headLink ()->appendStylesheet ( $this->basePath ( 'css/history/eiken-mapping-result.css' ) );
    $this->headLink()->appendStylesheet($this->basePath ( 'css/history/hackIE9.css' ), 'screen, projection', 'IE 9');
	$paging = $this->paginationHelper($paginator , $page, '/history/eiken/mapping-error/year/'.$year.'/kai/'.$kai, $numPerPage);
?>
 <?php //$this->headLink ()->appendStylesheet ( $this->basePath ( 'css/jquery-ui.css' ) )?>
<?php $tabIndex = 1;
?>
 <script>
 var listPupil = <?php echo $jsonListPupil;?>;
 </script>


<div class="confirm-result">
	<!-- Nav tabs -->
	<ul class="nav nav-tabs nav-confirm-result nav-custom-grey" role="tablist">
		<li role="presentation" class="active">
		  <a href="#mapping-error"
			aria-controls="mapping-error" role="tab" data-toggle="tab">
			 <?php echo $this->translate('生徒名簿突合せ結果：未突合') ;?>
		  </a>
		</li>
		<li  >
    		<a href="<?php echo '/history/eiken/mapping-success/year/'.$year.'/kai/'.$kai;?>" >
    		<?php echo $this->translate('生徒名簿突合せ結果：突合済') ;?>
    		</a>
		</li>
	</ul>

	<!-- Tab panes -->
	<div class="tab-content">
		<!-- mapping-error -->
		<div role="tabpanel" class="tab-pane active" id="mapping-error">
			<!-- 2 div data-->
			<div class="row">
                    <div class="top-mark">
                    <label class="font-mark"> 
                        生徒名簿との突合せ結果です。<br/>
                        突合せができた受験者は「突合済」タブに表示されます。<br/>
                        突合せができなかった受験者は「未突合」タブに表示されます。<br/>
                        <i class="text-parenthesis-jp">「氏名（漢字）」欄に氏名を入力して生徒名簿に存在する生徒と突合せを行ってください。<i><br/>
                        作業を終えたら「保存」ボタンを押してください。（作業途中でも「保存」ボタンは押せます）<br/>
                        </label>
                    </div>
				<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 col-left">

					<span class="title-result-exam"><?php echo $this->translate('試験結果') ;?></span>
					<div class="data-result-exam" id="data-result-exam">
						<table class="table-result-exam table table-bordered tbl-striped" id="table-left">
							<thead>
								<tr>
									<th class="jname text-center"><?php echo $this->translate('氏名(漢字)') ;?></th>
									<th class="jnameKana text-center"><?php echo $this->translate('氏名(カナ)') ;?></th>
									<th class="jbirth-day text-center"><?php echo $this->translate('生年月日') ;?></th>
									<!-- <th class="jpupil-id"><?php echo $this->translate('生徒ID') ;?></th> -->
									<th class="jschool-org text-center"><?php echo $this->translate('学校区分') ;?></th>
									<th class="jschool-year text-center"><?php echo $this->translate('学年番号') ;?></th>
									<th  class="jkumi text-center"><?php echo $this->translate('クラス') ;?></th>
									 <th class="jeiken-lv-id text-center"><?php echo $this->translate('受験級') ;?></th>
									<th class="jtotal text-center"><?php echo $this->translate('一次得点合計') ;?></th>
									<th class="jpass-fail text-center"><?php echo $this->translate('一次合否結果') ;?></th>
									<th class="jtotal text-center"><?php echo $this->translate('ニ次得点合計') ;?></th>
									<th class="jpass-fail text-center"><?php echo $this->translate('二次合否結果') ;?></th>

									<!--<th class="jeiken-id"><?php echo $this->translate('英検ID') ;?></th>-->
								</tr>
							</thead>
							<!-- 20 row -->
							<tbody>
							     <tr><td class="td-first"></td></tr>
							     <?php if(!empty($mappingData["mappingError"])){?>
							     <?php foreach ($mappingData["mappingError"] as $key=>$items){
							         foreach ($items as $keyChild=>$item){

							         ?>
							          <tr id="error-result-exam-<?php echo $key.$keyChild?>">
							             <!-- Name Kanji -->
						                 <td class="jname">
						                 
						                  <?php if(!empty($keepSession[$item['id']])):?>
                                         <input name="nameKanji[<?php echo $key?>]" id="input-error-result-exam-<?php echo $key.$keyChild?>"
					                       data-follow="error-pupil-manager-<?php echo $key.$keyChild?>"
					                       data-focus="error-result-exam-<?php echo $key.$keyChild?>"
                                           data-value="<?php echo $this->escapehtml($keepSession[$item['id']]['nameKanji']); ?>"
                                           value="<?php echo $this->escapehtml($keepSession[$item['id']]['nameKanji']); ?>"
                                           data-id="<?php echo $item['id']?>"
                                           class="form-control mapping-error-autocomplete" type="text" tabindex="<?php echo $tabIndex++;?>">
                                         <?php else :?>
                                           <input name="nameKanji[<?php echo $key?>]" id="input-error-result-exam-<?php echo $key.$keyChild?>"
						                      data-follow="error-pupil-manager-<?php echo $key.$keyChild?>"
						                      data-focus="error-result-exam-<?php echo $key.$keyChild?>"
						                      data-value="<?php echo $this->escapehtml($item['nameKanji']); ?>"
						                      value="<?php echo $this->escapehtml($item['nameKanji']); ?>"
						                      data-id="<?php echo $item['id']?>"
						                      class="form-control mapping-error-autocomplete" type="text" tabindex="<?php echo $tabIndex++;?>">
                                         <?php endif; ?>
						                 </td>
						                  <!-- Name Kantana -->
						                  <td class="jnameKana"><?php echo (!empty($item['nameKana'])) ? $this->escapehtml($item['nameKana']):'&nbsp'; ?></td>
						                  <!-- Birthday -->
						                  <td class="jbirth-day">
						                  <?php 
						                  echo (!empty($item['birthday']))?$item['birthday']->format('Y/n/j'):'&nbsp'; 
						                  ?>
						                  </td>
						                  <!-- Pupil ID -->
					                      <!--<td class="text-right jpupil-id"><?php echo (!empty($item['pupilId'])) ? $this->escapehtml($item['pupilId']):'&nbsp'; ?></td>-->
						                  <!-- OrgClassfication -->
						                  <td class="jschool-org">
						                      <?php 
						                      if($item['schoolNumber']!== NULL){
						                          if(!empty($listMappingOrgClass[$item['schoolNumber']])){
						                              echo $listMappingOrgClass[$item['schoolNumber']];
						                          }else {
						                              echo $this->escapehtml($item['schoolNumber']);
						                          }
						                          
						                      }
						                      ?>
					                      </td>
						                  <!-- ShoolYear Code -->
						                  <td class="jschool-year "><?php echo (!empty($item['schoolYearCode'])) ? $this->escapehtml($item['schoolYearCode']) :'&nbsp'; ?></td>
						                  <!-- kumi Class -->
						                  <td class="jkumi"><?php echo (!empty($item['classCode'])) ? $this->escapehtml($item['classCode']):'&nbsp'; ?></td>
						                  <!-- EikenLevel -->
						                  <td class="jeiken-lv-id text-right">
						                  <?php 
						                  if($item['eikenLevelId']!== NULL){
						                      if(!empty($listMappingLevel[$item['eikenLevelId']])){
						                          echo $listMappingLevel[$item['eikenLevelId']];
						                      }else{
						                          echo $this->escapehtml($item['eikenLevelId']);
						                      }
						                  }
						                  ?>
						                  </td>
						                  <!-- Eikentotal1 -->
						                  <td class="jtotal  text-right">
						                   <?php
            								    if($item['eikenLevelId'] == 6 || $item['eikenLevelId'] == 7){
            								        if($item['totalPrimaryScore']!== NULL || $item['firstExamResultsPerfectScore']!== NULL){
            								            echo $item['totalPrimaryScore'] . "/" . $item['firstExamResultsPerfectScore'];
            								        }
            								        
            								    }else{
            								        if ($item['oneExemptionFlag'] == 1) {
            								            echo '&nbsp';
            								        } elseif ($item['oneExemptionFlag'] == 0 || $item['oneExemptionFlag'] == null) {
            								            if($item['totalPrimaryScore'] == null && $item['firstExamResultsPerfectScore'] == null){
            								                echo '&nbsp';
            								            }else{
            								                echo $item['totalPrimaryScore'] . "/" . $item['firstExamResultsPerfectScore'];
            								            }
            								        }
            								    }
                                            ?>
						                  </td>
						                  <!-- PassFail1 -->
						                  <td class="jpass-fail">
						                      <?php
                                                    if ($item['oneExemptionFlag'] == 1) {
                                                        if(!empty($item['firstExamResultsFlagForDisplay'])){
                                                            echo $item['firstExamResultsFlagForDisplay'];
                                                        }else{
                                                            echo '&nbsp'; 
                                                        }
                                                    } else{
                                                        if ($item['primaryPassFailFlag'] == 1) {
                                                            echo '合格';
                                                        } elseif ($item['primaryPassFailFlag'] === 0) {
                                                            echo '不合格' . $item['primaryFailureLevel'];
                                                        } else {
                                                            echo '&nbsp';
                                                        }
                                                    }
                                                ?>
						                  </td>
						                  <!-- Eikentotal2 -->
						                  <td class="jtotal text-right">
						                   <?php
            								    if($item['eikenLevelId'] == 6 || $item['eikenLevelId'] == 7){
            								        echo '&nbsp';
            								    }else{
            								        if($item['totalSecondScore'] == null && $item['secondExamResultsPerfectScore'] == null){
            								            echo '&nbsp';
            								        }else{
            								            echo $item['totalSecondScore'] . "/" . $item['secondExamResultsPerfectScore'];
            								        }
            								    }
                                            ?>
						                  </td>
						                  <!-- PassFail2 -->
						                  <td class="jpass-fail">
						                      <?php
                								    if($item['eikenLevelId'] == 6 || $item['eikenLevelId'] == 7){
                								        echo '&nbsp';
                								    }else{
                								        if ($item['secondPassFailFlag'] == 1) {
                								            echo '合格';
                								        } elseif ($item['secondPassFailFlag'] === 0){
                								            echo '不合格' . ($item['secondUnacceptableLevel'] ? $item['secondUnacceptableLevel']:'&nbsp');
                								        }
                								    }
                                                ?>
						                  </td>

						                  <!-- EikenID -->
						             </tr>
							         <?php }
							         }
							     }?>
							     


							</tbody>
							<!--end 20 row -->
						</table>
					</div>

				</div>
				<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 col-right">
					<span class="title-pupil-manager"><?php echo $this->translate('生徒名簿') ;?></span>
					<div class="data-pupil-manager">
						<table class="table-pupil-manager table table-bordered tbl-striped" id="table-right">
							<thead>
								<tr>
									<th class="jname text-center"><?php echo $this->translate('氏名(漢字)') ;?></th>
									<th class="jnameKana text-center"><?php echo $this->translate('氏名(カナ)') ;?></th>
									<th class="jbirth-day text-center"><?php echo $this->translate('生年月日') ;?></th>
									<th class="jschool-year text-center"><?php echo $this->translate('学年') ;?></th>
									<th  class="jkumi text-center"><?php echo $this->translate('クラス') ;?></th>
									<th class="jnumber text-center"><?php echo $this->translate('番号') ;?></th>

								</tr>
							</thead>
							<!--20 row -->
							<tbody>
							     <tr><td class="td-first"></td></tr>

							     <?php if(!empty($mappingData["mappingError"])){?>
							     <?php foreach($mappingData["mappingError"] as $key=>$items){
							         foreach ($items as $keyChild=>$item){
							             if(!empty($keepSession[$item['id']])){
							                 ?>
                                             <tr id="error-pupil-manager-<?php echo $key.$keyChild?>">
             									<td class="jname"><?php echo (!empty($keepSession[$item['id']]['nameKanji'])) ? $this->escapehtml($keepSession[$item['id']]['nameKanji']):'&nbsp'; ?></td>
             									<!-- NameKana -->
             									<td class="jnameKana"><?php echo (!empty($keepSession[$item['id']]['nameKana'])) ? $this->escapehtml($keepSession[$item['id']]['nameKana']):'&nbsp';?></td>
             									<!-- Birthday -->
             									<td class="jbirth-day"><?php echo ($keepSession[$item['id']]['birthday']!== NULL) ? $this->escapehtml($keepSession[$item['id']]['birthday']):'&nbsp';?></td>
             									<!-- SchoolYear -->
             									<td class="jschool-year"><?php echo ($keepSession[$item['id']]['orgSchoolYearId']!== NULL) ? $this->escapehtml($keepSession[$item['id']]['orgSchoolYearName']):'&nbsp';?></td>
             									<!-- Class-Kumi -->
             									<td  class="jkumi"><?php echo ($keepSession[$item['id']]['classId']!== NULL) ? $this->escapehtml($keepSession[$item['id']]['className']):'&nbsp'; ?></td>
             									<!-- Number -->
             									<td class="jnumber"><?php echo ($keepSession[$item['id']]['number']!== NULL) ? $this->escapehtml($keepSession[$item['id']]['number']):'&nbsp'; ?></td>

         								    </tr>
							             <?php }elseif(!empty($mappingData['pupilError'][$item['tempPupilId']]) && $item['mappingStatus']== 2){
							                 //duplicate
							                 ?>
							                 <tr id="error-pupil-manager-<?php echo $key.$keyChild?>">
            									<!-- NameKanji -->
            									<td class="jname">
            									<?php 
                                            	  echo (!empty($mappingData['pupilError'][$item['tempPupilId']]['firstNameKanji'])) ? $this->escapehtml($mappingData['pupilError'][$item['tempPupilId']]['firstNameKanji']):'&nbsp'; 
                                            	  echo (!empty($mappingData['pupilError'][$item['tempPupilId']]['lastNameKanji'])) ? $this->escapehtml($mappingData['pupilError'][$item['tempPupilId']]['lastNameKanji']):'&nbsp'; 
                                            	 ?>
            									</td>
            									<!-- NameKana -->
            									<td class="jnameKana">
            									<?php 
                                        		 echo (!empty($mappingData['pupilError'][$item['tempPupilId']]['firstNameKana'])) ? $this->escapehtml($mappingData['pupilError'][$item['tempPupilId']]['firstNameKana']):'&nbsp';
                                        		 echo (!empty($mappingData['pupilError'][$item['tempPupilId']]['lastNameKana'])) ? $this->escapehtml($mappingData['pupilError'][$item['tempPupilId']]['lastNameKana']):'&nbsp';
                                        		 ?>
            									</td>
            									<!-- Birthday -->
            									<td class="jbirth-day">
            									<?php 
                                            	   echo !(empty($mappingData['pupilError'][$item['tempPupilId']]['birthday'])) ? $mappingData['pupilError'][$item['tempPupilId']]['birthday']->format('Y/n/j'):'&nbsp'; 
                                            	   ?>
            									</td>
            									<!-- SchoolYear -->
            									<td class="jschool-year">
            									<?php echo (!empty($mappingData['pupilError'][$item['tempPupilId']]['orgSchoolYearId'])) ? $this->escapehtml($mappingData['pupilError'][$item['tempPupilId']]['orgSchoolYearName']):'&nbsp'; ?>
            									</td>
            									<!-- Class-Kumi -->
            									<td  class="jkumi">
            									<?php echo (!empty($mappingData['pupilError'][$item['tempPupilId']]['classId'])) ? $this->escapehtml($mappingData['pupilError'][$item['tempPupilId']]['className']):'&nbsp'; ?>
            									</td>
            									<!-- Number ID-->
            									<td class="jnumber">
            									<?php echo (!empty($mappingData['pupilError'][$item['tempPupilId']]['number'])) ? $this->escapehtml($mappingData['pupilError'][$item['tempPupilId']]['number']):'&nbsp'; ?>
            									</td>
        								    </tr>
						                 <?php 
							             }else{
							                 //neu khong thi hien blank

                                    ?>
                                    <tr id="error-pupil-manager-<?php echo $key.$keyChild?>">
    									<!-- NameKanji -->
    									<td class="jname"></td>
    									<!-- NameKana -->
    									<td class="jnameKana"></td>
    									<!-- Birthday -->
    									<td class="jbirth-day"></td>
    									<!-- SchoolYear -->
    									<td class="jschool-year"></td>
    									<!-- Class-Kumi -->
    									<td  class="jkumi"></td>
    									<!-- Number ID-->
    									<td class="jnumber"></td>
								    </tr>
                                    <?php }
							           }
							         }
							     }?>


							<tbody>
								<!--end 20 row -->

						</table>
					</div>
				</div>
			</div>
			<!-- 2 div data-->
			<!-- Paging -->
			<?php if (count($paginator) > $numPerPage ) : ?>
    			<div class="text-center paging">
    				<nav>
    					<ul class="pagination">
                            <?php  echo $paging; ?>
						</ul>
    				</nav>
    			</div>
			<?php endif;?>
			<!--End Paging -->


		</div>
		<!-- End mapping-error -->
	</div>
	<!-- Group Button -->
	<div class="box-footer">
		<div style="text-align: right;">
			<button type="button" id="btnCancel" class="btn btn-large-180"
				onclick="EIKEN_MAPPING_RESULT.mappingCancel()" tabindex="<?php echo $tabIndex++;?>"><?php echo $this->translate('キャンセル') ;?> </button>
			<button type="button" id="btnSubmitToMapping"
				class="btn btn-large-180 btn-red" onclick="EIKEN_MAPPING_RESULT.mappingSave()" tabindex="<?php echo $tabIndex++;?>">
				<i class="fa-download-w"></i><?php echo $this->translate('保存') ;?></button>
		</div>
	</div>
	<!--End Group Button -->


</div>

<?php
    $this->headScript()->appendFile($this->basePath('js/jquery-ui.js'));
    $this->inlineScript()->appendFile($this->basePath('js/history/eiken-mapping-result.js'));
    echo $this->inlineScript();
?>
<script type="text/javascript">
$("document").ready(function(){
	EIKEN_MAPPING_RESULT.init();
});
</script>