<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'PupilMnt\Module'                        => __DIR__ . '/Module.php',
    'PupilMnt\Controller\PupilController' => __DIR__ . '/src/PupilMnt/Controller/PupilController.php',
    'PupilMnt\Controller\ImportPupilController' => __DIR__ . '/src/PupilMnt/Controller/ImportPupilController.php',
);
