<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'ConsoleInvitation\Module'                        => __DIR__ . '/Module.php',
    'ConsoleInvitation\Controller\ConsoleInvitationController' => __DIR__ . '/src/ConsoleInvitation/Controller/ConsoleInvitationController.php',
    'ConsoleInvitation\Controller\ConsoleLearningProgressController' => __DIR__ . '/src/ConsoleInvitation/Controller/ConsoleLearningProgressController.php',
);
