<?php
$this->headLink()->appendStylesheet($this->basePath('css/ImportStudent.css'))
                    ->appendStylesheet($this->basePath('css/studentandclass.css'))
                    ->appendStylesheet($this->basePath('css/OrgInforManagement.css'))
                    ->appendStylesheet($this->basePath('css/pupil/import-pupil.css'))
                    ->appendStylesheet($this->basePath('css/pupil/duplicate.css'));
$this->headScript()->appendFile($this->basePath('js/uploadform.js?v=20161119'));
$this->headScript()->appendFile($this->basePath('js/pupil/import-pupil-csv.js?v=20161119'));
?>
<div id="showError" class="row jiem-error displaynone">
    <div class="alert import-upload-error">
        <ul>
            <li>
                <a id="showMsgFileImport" onclick="importPupilConfig.forcusfield()"></a>
            </li>
        </ul>
    </div>
</div>
<div id="showContent">
    <div class="importstd">
        <div class="box">
            <div class="box-header">
                <p><?php echo $this->translate('TitleUpload'); ?></p>
            </div>
            <div class="box-body">
                <p><?php echo $this->translate('DescriptionUpload'); ?></p>
                <div class="importstd-form">
                    <?php
                    $form->setAttribute('action', $this->url('pupil-mnt/default', array('controller' => 'import-pupil', 'action' => 'index')));
                    $form->prepare();
                    echo $this->form()->openTag($form);
                    ?>
                    <div class="fl choose-file">
                        <label><?php echo $this->translate('TitleFieldImport'); ?></label>
                        <input type="text" class="importstd-textbox" id="filename" readonly="true" value="" />
                    </div>
                    <div class="importstd-btngroup fl">
                        <a class="btn btn-small btn-file" id="csvfilefocus" href="javascript:void(0)">
                            <i class="folder-open-small"> </i><strong>参照</strong>
                            <?php echo $this->formFile($form->get('fileImport')); ?>
                        </a>
                    </div>
                    

                    <div class="importstd-btngroup fr">
                        <button class="btn btn-small btn-red importstd-button-space" id="submitForm" role="button" type="submit">
                            <i class="fa-upload-small-w"></i>
                            <strong><?php echo $this->translate('TitleUpload') ?></strong>
                        </button>
                    </div>
                    <div class="col-sm-12 seperate-description">
                        <p style="margin-bottom: 5px;">※団体サポートシステムでは、姓名を分けて保持する必要があります。</p>
                        <p style="margin-bottom: 0px;line-height: 25px;">アップロードする名簿の氏名が、姓名を分けずに一つの項目に入力してある場合は、<a href="/pupil/import-pupil/seperate-name">ここをクリックしてください。</a>大部分の姓名を自動的に分ける機能をご利用頂けます。（自動的に分割できない姓名もありますので、自動分割後にご確認ください）。</p>
                    
                    </div>
                    <?php echo $this->form()->closeTag(); ?>
                </div>
                
            </div>
        </div>
        <div class="box pupilshowhide">
            <div class="box-body">
                <div class="importstd-btngroup">
                    <a class="btn btn-large-180 showbt" href="<?php echo $this->url('pupil-mnt/default', array('controller' => 'pupil', 'action' => 'index')); ?>">
                        <strong class="text-center">キャンセル</strong>
                    </a> 
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    importPupilConfig.ready();
</script>