<meta charset="UTF-8">
<br>----------------------------------------------------------------------------------------------
<br>このメールは、英検団体サポートにご登録いただいたメールアドレス宛に自動送信しています。
<br>そのため、お問合せ等のメッセージをご返信いただいても、回答できません。
<br>※お心当たりがない場合は、お手数ですがメールの破棄をお願いいたします。
<br>----------------------------------------------------------------------------------------------
<br>
<br><?php echo $this->escapeHtml($orgItem->getOrgNameKanji()); ?><?php echo $this->escapeHtml($userItem->getFirstNameKanji()) . $this->escapeHtml($userItem->getLastNameKanji()); ?>様
<br>
<br>公益財団法人日本英語検定協会です。
<br>英検団体サポートのユーザIDの確認リクエストを受け付けました。
<br>登録されているユーザ情報は以下の通りとなります。
<br>
<br>================================================================
<br>ユーザ情報
<br>================================================================
<br>
<br>団体番号：<?php echo $this->escapeHtml($userItem->getOrganizationNo()); ?>
<br>団体名：<?php echo $this->escapeHtml($orgItem->getOrgNameKanji()); ?>
<br>ユーザID：<?php echo $this->escapeHtml($userItem->getUserID()); ?>
<br>氏名：<?php echo $this->escapeHtml($userItem->getFirstNameKanji()) . $this->escapeHtml($userItem->getLastNameKanji()); ?>
<br>
<br>================================================================
<br>公益財団法人日本英語検定協会　英検サービスセンター
<br>================================================================
<br>URL : http://www.eiken.or.jp/eiken/contact/
<br>TEL : 03-3266-8010
<br>平日9:30～17:00
<br>＜土日祝・年末年始を除く。試験前日および当日は17:30まで。＞
<br>※メール本文の複製・転送等はご遠慮願います。
<script type="text/javascript">
    
</script>