<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Report\Module'                        => __DIR__ . '/Module.php',
    'Report\Controller\ReportController' => __DIR__ . '/src/Report/Controller/ReportController.php',
);
