<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Eiken\Module'                        => __DIR__ . '/Module.php',
    'Eiken\Controller\EikenOrgController' => __DIR__ . '/src/Eiken/Controller/EikenOrgController.php'
);
