<?php
echo $this->doctype(), PHP_EOL;
$invitationLetter = $this->invitationLetter; /* @var $invitationLetter \Application\Entity\InvitationLetter */
?>
<html lang="en">
    <head>
        <meta http-equiv="content-type" content="text/html; charset=UTF-8">
        <meta charset="utf-8">
        <style>
            .cl0 {
                border: 6px solid #e8c5c7;
                margin-top: 15px;
                width: 2350px;
            }

            .cl0-other {
                border: 6px solid #e8c5c7;
                width: 2350px;
            }

            .cl1 {
                background-color: #a41f24;
                text-align: center;
                font-size: 37px;
                border-right: 4px solid #e8c5c7;
                line-height: 80px;
                color: white;
                height: 81px;
            }

            .cl2 {
                width: 579px;
                float: left;
                border-right: 4px solid #e8c5c7;
                border-left: 2px solid #e8c5c7;
            }

            .cl3 {
                background-color: #f4dadd;
                text-align: center;
                font-size: 35px;
            }

            .number {
                background-color: #a41f24;
                color: white;
                padding: 0 15px 0 15px;
            }

            .cl4 {
                background-color: #f4dadd;
                font-size: 37px;
                margin-top: 5px;
                padding-left: 20px;
            }

            .cl5-list {
                float: left;
                width: 325px;
                padding-right: 10px;
                border-right: 4px dotted #e8c5c7;
                margin: 20px 0 20px 10px;
                text-align: center;
                font-size: 24px;
            }

            .last {
                border-right: none;
            }

            .cl5-for {
                background-color: #f4dadd;
                border-right: 3px solid white;
                padding: 20px 10px 20px 10px;
                vertical-align: middle;
                font-size: 22px;
            }

            .rect {
                margin: 0 30px 30px 30px;
                background-color: white;
                height: 180px;
                position: relative;
            }
        </style>
    </head>
    <body style="padding: 30px 60px 50px 55px; font-family: Meiryo; margin: 0px auto;">

        <div style="border:4px solid #e8c5c7;width: 2355px; margin-top: 30px;float: left; margin-bottom: 20px;clear: both ">
            <div style="display: block;float: left; height: 61px;">
                <div style="display: block;float: left;width: 195px; color: white;background-color: #a41f24;border:5px solid #a7262b; text-align: center;font-size: 37px;padding-top:5px;line-height:48px">
                    学校名
                </div>
                <div style="display: block;float: left;width: 601px; font-size:37px; padding-left: 25px;padding-top:5px">
                    <?php echo $this->escape($invitationLetter->getOrganizationName()); ?>
                </div>
                <div style="display: block;float: left;width: 118px; color: white;background-color: #a41f24; border:5px solid #a7262b; text-align: center;font-size: 37px;padding-top:5px;line-height:48px">
                    年
                </div>
                <div style="display: block;float: left;width: 300px; font-size:37px; padding-top:5px;text-align: center;">
                    <?php echo $this->escape($this->callIfCallable($invitationLetter->getPupil(), array('getOrgSchoolYear', 'getDisplayName'))); ?>
                    <?php // echo $this->escape($this->callIfCallable($invitationLetter->getEikenSchedule(),array('getYear','getYear'))) ?>
                </div>
                <div style="display: block;float: left;width: 115px; color: white;background-color: #a41f24; border:5px solid #a7262b; text-align: center;font-size: 37px;padding-top:5px;line-height:48px">
                    組
                </div>
                <div style="display: block;float: left;width: 193px; font-size:37px;padding-top:5px;text-align: center;">
                    <?php echo $this->escape($this->callIfCallable($invitationLetter->getPupil(), array('getClass', 'getClassName'))) ?>
                </div>
                <div style="display: block;float: left;width: 118px; color: white;background-color: #a41f24; border:5px solid #a7262b; text-align: center;font-size: 37px;padding-top:5px;line-height:48px">
                    番号
                </div>
                <div style="display: block;float: left;width: 105px; font-size:37px; padding-top:5px;text-align: center;">
                    <?php echo $invitationLetter->getNumberPupil() != Null ? $this->escape($invitationLetter->getNumberPupil()) : '&nbsp;&nbsp;' ?>
                    <?php // echo $this->escape($this->callIfCallable($invitationLetter->getPupil(),'getNumber'))?>
                </div>
                <div style="display: block;float: left;width: 117px; color: white;background-color: #a41f24; border:5px solid #a7262b; text-align: center;font-size: 37px;padding-top:5px;line-height:48px">
                    氏名
                </div>
                <div style="display: block;float: left;width: 390px; font-size:37px; padding-left: 28px;padding-top:5px">
                    <?php echo $this->escape($this->callIfCallable($invitationLetter->getPupil(), 'getFirstNameKanji') . $this->callIfCallable($invitationLetter->getPupil(), 'getLastNameKanji')) ?>
                </div>
            </div>
        </div>
        <div style="margin-top: 100px;">

            <div style="clear: both;"></div>


            <div class="cl0" style="border-top: none;">
                <div class="cl4">受験者サポートシステム（申込登録・クレジットカード支払・英ナビ利用登録）へのアクセス方法</div>

                <div style="font-size: 30px; margin: 20px;">
                    <p style="height: 50px; margin-bottom: 10px;margin-top: 10px;">
                        <span class="number">1</span> <span style="margin-left: 10px;">
                            スマートフォンもしくはPCより下記のURLにアクセスしてください。 </span>
                    </p>
                    <div class="cl4">
                        <div style="width: 15%; float: left;">
                            <p style="margin: 10px 0 0 25px;">QRコード</p>
                            <div style="height: 245px; width: 245px;" class="rect">
                                <img
                                    src="<?php echo $this->imageToBase64('img/tpl-payment-qrcode.png'); ?>"
                                    style="border: none; height: 245px; width: 245px;" />
                            </div>
                        </div>

                        <div style="width: 85%; float: right;">
                            <p style="margin: 10px 0 0 25px;">URL</p>
                            <div class="rect" style="height: 250px;">
                                <span style="margin-left: 20px; position: absolute; top: 82px;">
                                    <a style="text-decoration: none; color: black;"
                                       href="https://jukensha-support.eiken.or.jp">https://jukensha-support.eiken.or.jp</a>
                                </span><br />
                            </div>
                        </div>
                        <div style="clear: both;"></div>
                    </div>
                </div>


                <div style="font-size: 30px; margin: 20px;">
                    <p style="height: 80px; margin-bottom: 10px;">
                        <span class="number">2</span> <span style="margin-left: 10px;">画面の案内に従って必要事項を入力の上、送信してください。</span><br />
                        <span style="margin-left: 60px;">受験お申し込みページの「団体ID」「認証キー」欄には以下の番号を入力してください。</span>
                    </p>
                    <div class="cl4">
                        <div style="width: 25%; float: left;">
                            <p style="margin: 10px 0 0 25px;">団体ID</p>
                            <div style="height: 100px" class="rect">
                                <span style="position: absolute; top: 20px; left: 15px;"><?php echo dechex($this->escape($invitationLetter->getPupil()->getOrganization()->getOrganizationNo())) ?></span>
                            </div>
                        </div>

                        <div style="width: 20%; float: left;">
                            <p style="margin: 10px 0 0 25px;">認証キー</p>
                            <div class="rect" style="height: 100px;">

                                <span style="position: absolute; top: 20px; left: 15px;"><?php echo $this->authenKey ?></span>
                            </div>
                        </div>
                        <div style="width: 55%; float: left;">
                            <p style="margin: 60px 0 0 25px; font-size: 35px;">
                                ※認証キーはあなた専⽤の番号です。他の⼈の受験案内状に記載された番号は使⽤できません
                            </p>
                        </div>
                        <div style="clear: both;"></div>
                    </div>
                </div>
            </div>
            <div style="width: 2350px">
                <p style="font-size: 48px; margin-top: 10px; margin-bottom:10px; text-align:center">
                    上記のURLにアクセスした後、「英ナビ！を使⽤する」から英ナビ！にログインして学習できます
                </p>
                <hr style="border-style: inset; border-width: 1px;">
                <center style="font-size: 30px; margin-bottom: 10px;">
                    【お申し込みに関するお問い合わせ】英検サービスセンター（個人受付）　電話番号：03-3266-8311 受付時間：9:30〜17:00（⼟・⽇・祝⽇を除く）
                </center>
            </div>
        </div>
    </body>
</html>