<?php
if($isMobile)
    echo '<style> #commercial-law { padding: 30px; } #commercial-law table { margin: auto; } #commercial-law .box-header { margin-left: -15px; margin-bottom: 10px; } </style>';
?>
<style> #commercial-law a:hover{ color: red !important; text-decoration: underline; } </style>
<div id="commercial-law" class="box">
    <div class="box-header">
        <span><b>特定商取引法に基づく表記</b></span>
    </div>
    <div class="box-body">
        <div class="row">
            <table class="table table-bordered">
                <tbody>
                <tr>
                    <td>団体名、住所、代表者名</td>
                    <td>公益財団法人 日本英語検定協会<br>
                        162-8055　東京都新宿区横寺町５５<br>
                        代表者 松川 孝一
                    </td>
                </tr>
                <tr>
                    <td>お問い合わせ先</td>
                    <td>英検サービスセンター　個人受付<br>
                        電話番号　03-3266-8311<br>
                        <img src="/img/other/icon_window.gif"> <a style="color: inherit;" href="http://step-eiken.org/newyork/contact/" target="_blank">お問い合わせフォーム</a><br>
                        平日10:00－17:00(土・日曜日、祝日を除く、ただし試験前日は正午まで)
                    </td>
                </tr>
                <tr>
                    <td>販売価格</td>
                    <td>各級ごとに記載しています。</td>
                </tr>
                <tr>
                    <td>お支払い方法</td>
                    <td>クレジットカード<br>
                        以下のクレジットカードがご利用いただけます。<br>
                        VISA、MasterCard、JCB、AMEX，Diners
                    </td>
                </tr>
                <tr>
                    <td>お申し込み期限</td>
                    <td>クレジットカード払いは決済完了時に課金されます。</td>
                </tr>
                <tr>
                    <td>返金について</td>
                    <td>返金はできません。</td>
                </tr>
                <tr>
                    <td>キャンセルについて</td>
                    <td>決済完了後のキャンセルはできません。</td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>