<?php $this->headScript()->prependFile($this->basePath('js/messages/common-message.js')); ?>
<div class="login-description" style="color: red; font-size: 18px; margin-top: 10px;">
</div>
    <?php
if ($errors) {
    $form->get('organizationNo')->removeAttribute('autofocus');
    ?>
    <div class="text-left error-form-login ver-center" id="show_error">
        <ul>
            <?php foreach ($errors as $key => $error): ?>
                <li class='msg' style="cursor: pointer;"
                    onclick="$('<?php echo $key == "all" ? '#orgNo' : '#' . $key; ?>').focus()"><?php echo $this->translate($error); ?></li>
                <?php endforeach; ?>
        </ul>
    </div>
    <style>
        .fa-sign-in:before {
            content: "\f090";
        }
    </style>
<?php }else { ?>
    <script>
        $(document).ready(function () {
            $('form:first *:input[type!=hidden]:first').focus();
        });
    </script>
<?php } ?>

<?php
$form->setAttribute('action', $this->url('satellite', array(
            'controller' => 'Satellite',
            'action' => 'index'
)));
$form->setAttribute('class', 'form-horizontal fix-width-620 ver-center');
$form->setAttribute('id', 'frmLogin');
$form->setAttribute('action', 'login');
$form->prepare();
?>
<?php echo $this->form()->openTag($form); ?>
<div class="box">
    <div class="box-header ver-center">
        <div class="login-description">団体ID・認証キーを入力して、【ログイン】ボタンを押してください。</div> 
    </div>
    <div class="box-body">
        <div class="col-sm-1 col-xs-1 login-label-body ver-center">
            <p style="color:red;margin-bottom: 30px;font-weight: normal;" class="text-center">個人支払（コンビニ・クレジット）は5月9日（火）締切となります。</p>
            <div class="row">
                <div class="col-sm-1 col-xs-1 label-field-login">
                    <strong><?php echo $this->translate('OrganizationNo'); ?></strong>
                    <span class="star">*</span>
                </div>
                <div class="col-sm-1 col-xs-1 width180">
                    <?php
                    if (isset($errors["organizationNo"]) || isset($errors["all"])) {
                        $form->get('organizationNo')->setAttributes(array(
                            "class" => "form-control error"
                        ));
                    }
                    echo $this->formElement($form->get('organizationNo'));
                    ?>					
                </div>
                <div class="comment-note">（半角英数字）</div>
            </div>
            <div class="row">
                <div class="col-sm-1 col-xs-1 label-field-login">
                    <strong><?php echo $this->translate('authenKey'); ?></strong> <span
                        class="star">*</span>
                </div>
                <div class="col-sm-1 col-xs-1 width275">
                    <?php
                    if (isset($errors["authenKey"]) || isset($errors["all"])) {
                        $form->get('authenKey')->setAttributes(array(
                            "class" => "form-control error"
                        ));
                    }
                    echo $this->formElement($form->get('authenKey'));
                    ?>
                </div>
                <div class="comment-note">（半角数字）</div>
            </div>

        </div>
    </div>
    <div class="box-footer text-center">
        <div>
            <button class="btn btn-red btn-login login-control fix-font-16"
                    role="button" type="submit">
                <i class="sign-in"></i> <strong><?php echo $this->translate('ログイン'); ?></strong>
            </button>

        </div>
    </div>
</div>
<?php echo $this->form()->closeTag(); ?>
