<div class="new-schoolyear">
<?php
$form->setAttribute('action', $this->url('org-mnt/default', array(
    'controller' => 'schoolyear',
    'action' => 'save'
)));
$form->prepare();
?>
	<?php  echo $this->form()->openTag($form); ?>
		<input type="hidden" value="<?php echo $id;?>" name="id">
	<div class="box">
		<div class="box-header">
			<strong><?php echo $this->translate('学年追加') ;?></strong>
		</div>
		<div class="box-body">
			<div data-example-id="bordered-table">
				<div class="row">
					<div class="fl col3">
						<label><b><?php echo $this->translate('学年') ;?></b></label>
					</div>
					<div class="fl col4">
						  <?php echo $this->formRow($form->get('name')); ?>
					   </div>

					<div class="fl col4">
						  <?php echo $this->formRow($form->get('schoolYear')); ?>
					   </div>

				</div>
			</div>
		</div>
		<div class="box-footer text-right">
			<a class="btn btn-large-180 margin-right-4"
				href="<?php echo $this->url('org-mnt/default', array('controller' => 'schoolyear', 'action' => 'index')) ?>">
				<i></i> <b><?php echo $this->translate('キャンセル') ;?></b>
			</a>
			<button type="submit" class="btn btn-red  btn-large-180 margin_edit">
				<i class="fa-download-w"></i> <b><?php echo $this->translate(' 保存') ;?></b>
			</button>
		</div>
	</div>
	<?php echo $this->form()->closeTag(); ?>
</div>