<div class="edit-schoolyear">
<?php
$form->setAttribute('action', $this->url('org-mnt/default', array(
    'controller' => 'schoolyear',
    'action' => 'update',
    'id' => $id
)));
$form->prepare();
?>
	<?php  echo $this->form()->openTag($form); ?>
		<input type="hidden" value="<?php echo $id;?>" name="id">
	<div class="box">
		<div class="box-header">
			<strong>'学年情報編集</strong>
		</div>
		<div class="box-body">
			<div data-example-id="bordered-table">
				<div class="row">
					<div class="fl col1">
						<b><?php echo $this->translate('学年（旧）') ;?></b>
					</div>
					<div class="fl col2"><?php echo $schoolyearName;?></div>
					<div class="fl col3">
						<label><b><?php echo $this->translate('学年（新）') ;?></b></label>
					</div>
					<div class="fl col4 text-input">
						  <?php echo $this->formRow($form->get('displayName')); ?>
					</div>

				</div>
			</div>
		</div>
		<div class="box-footer text-right">
			<a class="btn btn-large-180 margin-right-4"
				href="<?php echo $this->url('org-mnt/default', array('controller' => 'schoolyear', 'action' => 'index')) ?>">
				<i></i> <b><?php echo $this->translate('キャンセル') ;?></b>
			</a>
			<button id="org-school-year-save" type="submit" class="btn btn-red  btn-large-180 margin_edit">
				<i class="fa-download-w"></i> <b><?php echo $this->translate(' 保存') ;?></b>
			</button>
		</div>
	</div>
	<?php echo $this->form()->closeTag(); ?>
</div>
<script type="text/javascript">
    var jsMessages = <?php echo $jsMessages;?>;
    $(document).ready(function() { 
        COMMON.showCrossEditMessage('#org-school-year-save'); 
    });
</script>