<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Satellite\Module' => __DIR__ . '/Module.php',
    'Satellite\Controller\SatelliteController' => __DIR__ . '/src/Satellite/Controller/SatelliteController.php'
);
