<?php
if ($isMobile) {
    $this->headLink()->prependStylesheet($this->basePath('css/detail-apply-eiken-mobile.css'));
}
else {
    $this->headLink()->prependStylesheet($this->basePath('css/detail-apply-eiken.css'));
};

 $isNeedTestSiteExemption = $exemptionData['examGrade2'] !== null;
?>
<script>
    var translate = <?php echo empty($translate) ? 0 : $translate; ?>;
    var hallTypeInv = 1;
</script>
<style> #apply-eiken-detail a:hover { color: red !important; text-decoration: underline; } </style>
<div id="apply-eiken-detail" class="box <?php echo ($isMobile) ? 'mobile' : 'pc' ?>">
    <?php if (!$isMobile) { ?>
        <div class="box-header">
            <span><b><?php echo $this->translate('applyEikenInfoConfirm'); ?></b></span>
        </div>
    <?php } ?>
    <div class="box-body">
        <!--eiken grade fee table-->
        <div class="row">
            <div class="col-xs-12 col-md-12">
                <label class="text-bold"><?php echo $this->translate('eikenGradeFeeTable') ?></label></div>
            <div class="col-xs-12 col-md-12">
                <table class="table table-bordered table-striped col-xs-12 col-md-12 text-center" style="margin-bottom:5px;">
                    <thead>
                    <td class="wp12"><?php echo $this->translate('eikenGradeFeeTableColumn1') ?></td>
                    <td><?php echo $this->translate('eikenGradeFeeTableColumn2') ?></td>
                    <td><?php echo $this->translate('eikenGradeFeeTableColumn3') ?></td>
                    <td>実施会場の選択</td>
                    </thead>
                    <tbody>
                    <?php foreach ($kyu as $kyuId => $val) { ?>
                        <tr>
                            <td><?php echo $val['name']; ?></td>
                            <td><?php echo $val['priceName']; ?></td>
                            <td class="round2date"><?php echo $val['examDate2Round'] ?></td>
                            <td><?php echo $listHallType[$val['hallType']] ?></td>
                        </tr>
                    <?php } ?>
                    </tbody>
                </table>
            </div>
        </div>
        <!--end exam grade fee table-->
         <?php if($data['exemption'] == 1) { ?>
        <div>

            <div class="row">
                <div class="col-md-4 col-xs-5">
                    <label class="text-bold"><?php echo $this->translate('nameKanjiLabel') ?></label></div>
                <div class="col-md-8 col-xs-7"><?php echo $data['txtFirstNameKanji'] . $data['txtLastNameKanji']; ?></div>
            </div>
            <div class="row">
                <div class="col-md-4 col-xs-5">
                    <label class="text-bold"><?php echo $this->translate('nameKanaLabel') ?></label></div>
                <div class="col-md-8 col-xs-7"><?php echo $data['txtFirstNameKana'] . $data['txtLastNameKana']; ?></div>
            </div>
            <div class="row">
                <div class="col-md-4 col-xs-5">
                    <label class="text-bold"><?php echo $this->translate('genderLabel') ?></label></div>
                <div class="col-md-8 col-xs-7"><?php echo $this->translate($data['rdSex'] == 1 ? 'maleLabel' : 'femaleLabel'); ?></div>
            </div>
            <div class="row">
                <div class="col-md-4 col-xs-5">
                    <label class="text-bold"><?php echo $this->translate('birthDayLabel') ?></label></div>
                <div class="col-md-8 col-xs-7"><?php echo $data['ddlYear'] . '年 ' . $data['ddlMonth'] . '月 ' . $data['ddlDay'] . '日'; ?></div>
            </div>
            <div class="row">
                <div class="col-md-4 col-xs-5">
                    <label class="text-bold"><?php echo $this->translate('postalCodeLabel') ?></label></div>
                <div class="col-md-8 col-xs-7"><?php echo $data['txtPostalCode1'] . ' - ' . $data['txtPostalCode2']; ?></div>
            </div>
            <div class="row">
                <div class="col-md-4 col-xs-5"><label class="text-bold"><?php echo $this->translate('cityLabel') ?></label>
                </div>
                <div class="col-md-8 col-xs-7"><?php echo $data['cityName']; ?></div>
            </div>
            <div class="row">
                <div class="col-md-4 col-xs-5">
                    <label class="text-bold"><?php echo $this->translate('districtLabel') ?></label></div>
                <div class="col-md-8 col-xs-7"><?php echo $data['txtDistrict']; ?></div>
            </div>
            <div class="row">
                <div class="col-md-4 col-xs-5"><label class="text-bold"><?php echo $this->translate('townLabel') ?></label>
                </div>
                <div class="col-md-8 col-xs-7"><?php echo $data['txtTown']; ?></div>
            </div>
            <div class="row">
                <div class="col-md-4 col-xs-5">
                    <label class="text-bold"><?php echo $this->translate('phoneNoLabel') ?></label></div>
                <div class="col-md-8 col-xs-7"><?php echo preg_replace('/-/',') ','('.$data['txtPhoneNo'], 1); ?></div>
            </div>
            <div class="row">
                <div class="col-md-4 col-xs-5"><label class="text-bold"><?php echo $this->translate('emailLabel') ?></label>
                </div>
                <div class="col-md-8 col-xs-7"><?php echo $data['txtEmail']; ?></div>
            </div>
            <div class="row">
                <div class="col-md-4 col-xs-5">
                    <label class="text-bold"><?php echo $this->translate('jobNameLabel') ?></label></div>
                <div class="col-md-8 col-xs-7"><?php echo empty($data['ddlJobName']) ? '' : $listJob[$data['ddlJobName']]; ?></div>
            </div>
            <?php if($data['ddlJobName'] == '1'){ ?>
                <div class="row">
                    <div class="col-md-4 col-xs-5">
                        <label class="text-bold"><?php echo $this->translate('SchoolCode') ?></label></div>
                    <div class="col-md-8 col-xs-7"><?php echo empty($data['ddlSchoolCode']) ? '' : array_key_exists($data['ddlSchoolCode'], $listSchoolCode) ? $listSchoolCode[$data['ddlSchoolCode']] : ''; ?></div>
                </div>
            <?php } ?>
        </div>
         <?php } ?>
        <!--test side and exemption table-->
        <?php if($data['exemption'] == 1) { ?>
        <div class="row mt20">
            <div class="col-xs-12 col-md-12">
                <table class="table table-bordered table-striped col-xs-12 col-md-12">
                <thead>
                     <td class="label-column"></td>
                     <td><?php echo $listLevel[$exemptionData['examGrade1']] ?></td>
                    <?php if ($isNeedTestSiteExemption) { ?>
                    <td><?php echo $listLevel[$exemptionData['examGrade2']] ?></td>
                    <?php } ?>
                </thead>
                <tbody>
                    <tr>
                        <td class="text-bold"><?php echo $this->translate('exemptionLabel1'); ?></td>
                        <td class="wp30"><?php echo $this->formElement($form->get('examGrade1')->setValue($exemptionData['examGrade1'])) ?></td>
                         <?php if ($isNeedTestSiteExemption) { ?>
                        <td class="wp30"><?php echo $this->formElement($form->get('examGrade2')->setValue($exemptionData['examGrade2'])) ?></td>
                        <?php } ?>
                    </tr>
                    <tr>
                        <td><?php echo $this->translate('exemptionLabel2'); ?></td>
                        <td>
                            <div><?php echo $this->translate(isset($exemptionData['exemption1']) && $exemptionData['exemption1'] == 1 ? 'yesLabel' : 'noLabel') ?></div>
                        </td>
                        <?php if ($isNeedTestSiteExemption) { ?>
                        <td>
                            <div><?php echo $this->translate(isset($exemptionData['exemption2']) && $exemptionData['exemption2'] == 1 ? 'yesLabel' : 'noLabel') ?></div>
                        </td>
                        <?php } ?>
                    </tr>
                    <tr>
                        <td><?php echo $this->translate('passedKaiLabel'); ?></td>
                        <td>
                            <div><?php echo !empty($exemptionData['passedKai1']) ? $passKaiText['passedKaiText1'] : '' ?></div>
                        </td>
                        <?php if ($isNeedTestSiteExemption) { ?>
                        <td>
                            <div><?php echo !empty($exemptionData['passedKai2']) ? $passKaiText['passedKaiText2'] : '' ?></div>
                        </td>
                        <?php } ?>
                    </tr>
                    <tr>
                        <td><?php echo $this->translate('passedExamCityLabel'); ?></td>
                        <td>
                            <div><?php echo !empty($exemptionData['passedCity1']) ? $listCity[$exemptionData['passedCity1']]['cityName']: '' ?></div>
                       </td>
                        <?php if ($isNeedTestSiteExemption) { ?>
                        <td>
                            <div><?php echo !empty($exemptionData['passedCity2']) ? $listCity[$exemptionData['passedCity2']]['cityName'] : '' ?></div>
                       </td>
                        <?php } ?>
                    </tr>
                    <tr>
                        <td><?php echo $this->translate('passedExamPlaceLabel'); ?></td>
                        <td>
                            <div><?php echo !empty($exemptionData['passedPlace1']) ? $listDistrictByCode[$exemptionData['passedPlace1']]['name']: '' ?></div>
                       </td>
                        <?php if ($isNeedTestSiteExemption) { ?>
                        <td>
                            <div><?php echo !empty($exemptionData['passedPlace2']) ? $listDistrictByCode[$exemptionData['passedPlace2']]['name'] : '' ?></div>
                       </td>
                        <?php } ?>
                    </tr>
                    <tr>
                        <td><?php echo $this->translate('personalIdLabel'); ?></td>
                        <td>
                            <div><?php echo isset($exemptionData['personalId1']) ? $exemptionData['personalId1'] : '' ?></div>
                       </td>
                        <?php if ($isNeedTestSiteExemption) { ?>
                        <td>
                            <div><?php echo isset($exemptionData['personalId2']) ? $exemptionData['personalId2'] : '' ?></div>
                       </td>
                        <?php } ?>
                    </tr>
                    <tr>
                        <td class="text-bold"><?php echo $this->translate('testSiteLabel'); ?></td>
                        <td></td>
                         <?php if ($isNeedTestSiteExemption) { ?>
                        <td></td>
                        <?php } ?>
                    </tr>
                    <tr>
                        <td><?php echo $this->translate('firstTestCityLabel'); ?></td>
                        <td>
                            <div><?php echo isset($exemptionData['firstTestCity1']) ? $listCity[$exemptionData['firstTestCity1']]['cityName'] : '' ?></div>
                        </td>
                        <?php if ($isNeedTestSiteExemption) { ?>
                        <td>
                           <div><?php echo isset($exemptionData['firstTestCity2']) ? $listCity[$exemptionData['firstTestCity2']]['cityName'] : '' ?></div>
                        </td>
                        <?php } ?>
                    </tr>
                    <tr>
                        <td><?php echo $this->translate('firstExamPlaceLabel'); ?></td>
                        <td>
                            <div><?php echo isset($exemptionData['firstExamPlace1']) ? $listDistrict[$exemptionData['firstExamPlace1']]['name'] : '' ?></div>
                        </td>
                        <?php if ($isNeedTestSiteExemption) { ?>
                        <td>
                            <div><?php echo isset($exemptionData['firstExamPlace2']) ? $listDistrict[$exemptionData['firstExamPlace2']]['name'] : '' ?></div>
                        </td>
                        <?php } ?>
                    </tr>
                    <tr>
                        <td><?php echo $this->translate('secondTestCityLabel'); ?></td>
                        <td>
                           <div><?php echo isset($exemptionData['secondTestCity1']) ? $listCity[$exemptionData['secondTestCity1']]['cityName'] : '' ?></div>
                        </td>
                        <?php if ($isNeedTestSiteExemption) { ?>
                        <td>
                            <div><?php echo isset($exemptionData['secondTestCity2']) ? $listCity[$exemptionData['secondTestCity2']]['cityName'] : '' ?></div>
                         </td>
                         <?php } ?>
                    </tr>
                    <tr>
                        <td><?php echo $this->translate('secondExamPlaceLabel'); ?></td>
                        <td>
                            <div><?php echo isset($exemptionData['secondExamPlace1']) ? $listDistrict[$exemptionData['secondExamPlace1']]['name'] : '' ?></div>
                        </td>
                        <?php if ($isNeedTestSiteExemption) { ?>
                        <td>
                            <div><?php echo isset($exemptionData['secondExamPlace2']) ? $listDistrict[$exemptionData['secondExamPlace2']]['name'] : '' ?></div>
                        </td>
                         <?php } ?>
                    </tr>
                </tbody>
                </table>
            </div>
        </div>
         <?php } ?>
            <p class="text-right popicy-apply">実用英語技能検定　<a href="http://www.eiken.or.jp/eiken/apply/private/eiken_disclaimer.html" target="_blank">受験規約</a></p>
            <p class="text-right popicy-apply">4級・5級スピーキングテスト　<a href="http://www.eiken.or.jp/eiken/apply/private/eiken_disclaimer4s5s.html" target="_blank">受験規約</a></p>
    </div>
   
    <div class="box-footer">
        <button type="button" onclick="window.location.href = '<?php echo empty($_SERVER['HTTP_REFERER']) ? '/' : $_SERVER['HTTP_REFERER']; ?>'" id="btnBack" class="btn pull-left mw120"><i class="arrow-circle-left"></i> <?php echo $this->translate('Back') ?></button>
        <button type="button" id='btnApply' class="btn pull-right mw120 btn-red width-185"><i class="arrow-circle-right-w"></i> <?php echo $this->translate('applyAgreeBtn') ?></button>
        <button type="button" onclick="window.location.href = '/'" id="btnCancel" class="btn pull-right mr20 mw120"><?php echo $this->translate('cancel') ?></button>
        <div class="clearfix"></div>
    </div>
</div>
<?php $this->headScript()->appendFile($this->basePath('js/apply-eiken.js')) ?>
<script type="text/javascript">
    $(document).ready(function () {
        APPLY_EIKEN.init();
    });
</script>