<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
//     'DantaiApi\Module'                        => __DIR__ . '/Module.php',
//     'DantaiApi\Controller\DantaiApiController' => __DIR__ . '/src/DantaiApi/Controller/DantaiApiController.php',
//     'DantaiApiTest\Framework\TestCase'        => __DIR__ . '/tests/DantaiApi/Framework/TestCase.php',
//     'DantaiApiTest\SampleTest'                => __DIR__ . '/tests/DantaiApi/SampleTest.php',
);
