<?php $this->headLink()->appendStylesheet($this->basePath('css/list_org_style.css')) ?>
<?php $this->headScript()->appendFile($this->basePath('js/login/edit-password.js?v=0.1')) ?>
<?php
$form->setAttribute('action', $this->url('changePasswordFirst', array('controller' => 'Uac', 'action' => 'changePasswordFirst')));
$form->setAttribute('id', 'frmChangeProfile');
$form->prepare();
?>

<div style="display: none;" class="row jiem-error" id="show_error">
    <div role="alert" class="alert">
        <ul id="show_error_content">
        </ul>
    </div>
</div>
<div class="box">
    <div class="box-header">
        <?php echo $this->translate("ChangePassword"); ?>
    </div>

    <?php echo $this->form()->openTag($form); ?>
    <div class="box-body register-body">
        <div class="notice-password">
            <label class="font-mark">
                <label class="font-mark col-sm-12">現在のパスワードは仮パスワードです。新しいパスワードを設定してください。</label>
                <label class="font-mark"></br>
                パスワードは以下の条件を満たしてください。<br/>
                ・半角英数字<br/>
                ・7～31桁<br/>
                ・大文字、小文字、数字を少なくとも一つは含む<br/>
                ・ユーザIDと同じ値は不可<br/>
                ・直近のパスワードと同じ値は不可<br/><br/>
                <span class="star"> *</span>必須入力項目</label>
            </label>
        </div>
        <div class="row margin-bottom-register">
            <div class="col-sm-3">
                <p>
                    <?php echo $this->translate("UserId"); ?><span class="star"> *</span>
                </p>
            </div>
            <div class="col-sm-5 input-user-id">
                <p style="font-weight: normal;"><?php echo $this->formElement($form->get('txtUserID')); ?></p>
            </div>
        </div>
        <div class="row margin-bottom-register-name">
            <div class="col-sm-3">
                <p>
                    <?php echo $this->translate("Name (Kanji)"); ?><span class="star">*</span>
                </p>
            </div>

            <div class="col-sm-8">
                <?php echo $this->formElement($form->get('txtFistname')); ?>
                <?php echo $this->formElement($form->get('txtlastname')); ?>
            </div>
        </div>

        <div class="row email-row">
            <div class="col-sm-3">
                <p>
                    <?php echo $this->translate("Email Address"); ?><span class="star">
                        *</span>
                </p>
            </div>
            <div class="col-sm-5">
                <p class="email-info" style="font-weight: normal;"><?php echo $this->formElement($form->get('txtEmailAddress')); ?></p>
            </div>
        </div>

        <div class="row password-row">
            <div class="col-sm-3">
                <label><?php echo $this->translate('OldPassword') ?><span
                        class="star"> *</span></label>
            </div>
            <div class="col-sm-5">
                <?php echo $this->formElement($form->get('oldPassword')); ?></div>
        </div>

        <div class="row password-row">
            <div class="col-sm-3">
                <label><?php echo $this->translate('NewPassword') ?><span
                        class="star"> *</span></label>
            </div>
            <div class="col-sm-5">
                <?php echo $this->formElement($form->get('newPassword')); ?></div>
        </div>

        <div class="row password-row">
            <div class="col-sm-3">
                <label><?php echo $this->translate('ConfirmNewPassword') ?><span
                        class="star"> *</span></label>
            </div>
            <div class="col-sm-5">
                <?php echo $this->formElement($form->get('confirmNewPassword')); ?></div>
        </div>

        <!-- Button -->
        <div class="box-footer user-detail-footer">
            <div class="row">
                <div class="col-sm-12 text-right">
                    <button type="submit"
                            class="btn btn-large-180 div-button-change btn-red">
                        <i class="fa-download-w"></i><?php echo $this->translate('Save') ?>
                    </button>

                </div>
            </div>
        </div>

    </div>
    <?php echo $this->form()->closeTag(); ?>
</div>
<script type="text/javascript">
    $(document).ready(function () {
        $('form:first *:input[type!=hidden]:first').focus();
        $("#frmChangeProfile").validate({
            submitHandler: function () {
                EDIT_PASSWORD.ajaxChangePasswordFirst();
            }
        });
    });
</script>