<?php echo $this->headLink()->appendStylesheet($this->basePath('css/Changepass.css')); ?>
<?php $this->headScript()->appendFile($this->basePath('js/login/edit-password.js?v=0.1')) ?>
<?php
$form->setAttribute('action', $this->url('basic-construction/default', array(
            'controller' => 'Uac',
            'action' => 'changePassword'
)));
$form->setAttribute('id', 'frmChangePass');
$form->setAttribute('class', 'form-horizontal fix-width-620 ver-center');
$form->prepare();
?>

<div style="display: none;" class="row jiem-error" id="show_error">
    <div role="alert" class="alert">
        <ul id="show_error_content">
        </ul>
    </div>
</div>
<?php echo $this->form()->openTag($form); ?>
<div class="box frm-changepass">
    <!-- Header -->
    <div class="box-header">
        <b><?php echo $this->translate('ChangePassword'); ?></b>
    </div>
    <!-- Body -->
    <div class="box-body">

        <div class="row firstrow">
            <div class="col-sm-3">
                <label><?php echo $this->translate('OldPassword') ?><span
                        class="star"> *</span></label>
            </div>
            <div class="col-sm-5">      
                <?php echo $this->formElement($form->get('oldPassword')); ?></div>
        </div>

        <div class="row">
            <div class="col-sm-3">
                <label><?php echo $this->translate('NewPassword') ?><span
                        class="star"> *</span></label>
            </div>
            <div class="col-sm-5">
                <?php echo $this->formElement($form->get('newPassword')); ?></div>
        </div>

        <div class="row lastrow">
            <div class="col-sm-3">
                <label><?php echo $this->translate('ConfirmNewPassword') ?><span
                        class="star"> *</span></label>
            </div>
            <div class="col-sm-5">
                <?php echo $this->formElement($form->get('confirmNewPassword')); ?></div>
        </div>
    </div>

    <!-- Button -->
    <div class="box-footer ">
        <div class="text-right">
            <a
                href="<?php echo $redirectUrl; ?>"
                class="btn btn-large-180 btn-footer-1"><?php echo $this->translate('Cancel') ?></a>
            <button type="submit" class="btn btn-large-180 div-button-change btn-red">
                <i class="fa-download-w"></i><?php echo $this->translate('Save') ?>      
            </button>
        </div>
    </div>
</div>
<?php echo $this->form()->closeTag(); ?>

<script type="text/javascript">
    $(document).ready(function () {
        $('form:first *:input[type!=hidden]:first').focus();
        $("#frmChangePass").validate({
            submitHandler: function () {
                EDIT_PASSWORD.ajaxChangePassword('<?php echo $redirectUrl;?>');
            }
        });
        $("#btnCancel").click(function () {
            window.history.back();
        });
    });
</script>
