<?php echo $this->headLink()->appendStylesheet($this->basePath('css/policy-login.css')); ?>
<?php if ($errors) { ?>
    <div class="row jiem-error" id="show_error">
        <div role="alert" class="alert">
            <ul>
                <?php foreach ($errors as $key => $error): ?>
                    <li class='msg' style="cursor: pointer;" onclick="$('<?php echo $key == "all" ? '#agreePolicy' : '#' . $key; ?>').focus()"><?php echo $this->translate($error); ?></li>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
<?php } ?>
<script>
    $(document).ready(function () {
        var errors = <?php echo json_encode($errors); ?>;
        if (errors == false) {
            $('form:first *:input[type!=hidden]:first').focus();
        }
        $('#samplePolicy').click(function () {
            window.open("/basicConstruction/uac/samplePolicy", "_blank", "location=1,status=1,scrollbars=1,width=900, height=1000");
        });
    });
</script>
<div class="box">

    <div align="center" class="box-body">
        <div class="policy text-left mrg10">
            <div class="text-center">
                英検 団体サポートシステム利用規約
            </div>
            <br/>
            <p class="content-policy">
                「英検 団体サポートシステム」および各コンテンツ（以下「本WEBサイト」という）は、公益財団法人日本英語検定協会（以下、「当協会」という）が株式会社教育測定研究所（以下「教育測定研究所」といい当協会と合わせて「協会ら」といいます。）の協力のもと共同で運営・管理しています。本WEBサイトは、以下の規約（以下「本規約」という）に基づいて、お客様にサービス（以下「本サービス」という）を提供します。
            </p>
            <br/>
            <p class="content-policy">
                本WEBサイトをご利用になる方々（以下「利用者」という）には、本規約をよくお読みになり、ご同意の上、本規約に沿って行動していただきます。本規約にご同意いただけない場合は、本サービスをご利用いただけません。また、本サービスの利用に際して、「同意する」ボタンをクリックされると、本規約に同意されたものとみなします。
            </p>
            <br/>
            <p class="content-policy title-main">第１条（定義）</p>
            <p class="content-policy">本規約において、以下の用語は以下に定める意味を有するものとします。 </p>
            <p class="content-policy">（１）「ユーザ」とは、本規約に同意の上、所定の方法により本WEBサイトにユーザ登録をした個人をいいます。</p>
            <p class="content-policy">（２）「本サービス」とは、協会ら又はサービス提供者が本WEBサイトで提供する団体および個人向けの各種サービスをいいます。</p>
            <p class="content-policy">（３）「取引」とは、ユーザが本WEBサイトを利用して行う、本サービスの利用行為をいいます。</p>
            <p class="content-policy">（４）「サービス提供者」とは、本WEBサイト内で運営する、本条第2号に定めるサービスの対象となる役務を提供する者をいいます。</p>
            <p class="content-policy">（５）「本規約等」とは、本規約、本WEBサイトご利用上のご注意、実用英語技能検定のお申し込み誘導等各種行為でのご注意、その他協会らが定める規約等の総称をいいます。</p>
            <p class="content-policy">（６）「団体情報」とは、団体が協会らに開示した団体の属性に関する情報および団体の取引に関する履歴等の情報（第１２条により収集された情報を含みます）をいいます。</p>
            <br/>
            <p class="content-policy title-main">第２条（本サービス）</p>
            <p class="content-policy">「英検 団体サポートシステム」とは、協会らが運営する本WEBサイト上で展開する各種サービスの総称をいいます。</p>
            <p class="content-policy">（１）「英検 団体サポートシステム」のご利用にかかる、インターネット接続料金、通信機器等は利用者のご負担となります。</p>
            <p class="content-policy">（２）「英検 団体サポートシステム」のご利用にあたっては、協会ら指定の方法で本人確認を行います。 </p>
            <br/>
            <p class="content-policy title-main">第３条（ユーザ）</p>
            <p class="content-policy">ユーザは、協会らが定める条件に従って、本WEBサイトにおいて各サービスを利用することができます。ただし、別途協会ら又はサービス提供者が定める事項の登録を必要とする場合があります。</p>
            <p class="content-policy">ユーザは、ユーザとしての地位およびサービスの利用により協会らに対して取得した一切の権利を譲渡、転貸、担保差入その他形態を問わず処分することはできません。</p>
            <br/>
            <p class="content-policy title-main">第４条（本規約）</p>
            <p class="content-policy">本規約は、すべてのユーザに適用され、登録手続時および登録後にお守りいただく規約です。</p>
            <br/>
            <p class="content-policy title-main">第５条（ユーザ登録手続）</p>
            <p class="content-policy">ユーザ資格</p>
            <p class="content-policy">本規約に同意のうえ所定の登録手続完了後にユーザとしての資格を有します。ユーザ登録手続は、団体の管理者など責任ある立場の方が行ってください。</p>
            <br/>
            <p class="content-policy title-main">第６条（ユーザIDおよびパスワードの管理）</p>
            <p class="content-policy">ユーザIDおよびパスワードは、他人に知られることがないよう定期的に変更する等、ユーザ本人が責任をもって管理してください。入力されたユーザIDおよびパスワードが登録されたものと一致することを所定の方法により確認した場合、ユーザによる利用があったものとみなし、それらが盗用、不正使用その他の事情によりユーザ以外の者が利用している場合であっても、それにより生じた損害について協会らは一切責任を負いません。</p>
            <br/>
            <p class="content-policy title-main">第７条（登録情報の変更）</p>
            <p class="content-policy">登録した情報に変更が生じた場合は、速やかに変更登録をお願いいたします。変更登録がなされなかったことにより生じた損害について、協会らは一切責任を負いません。</p>
            <p class="content-policy">また、変更登録がなされた場合でも、変更登録前にすでに手続がなされた取引は、変更登録前の情報に基づいて行われます。 </p>
            <br/>
            <p class="content-policy title-main">第８条（ユーザの削除）</p>
            <p class="content-policy">ユーザの削除を希望する場合には、団体の管理者など責任ある立場の方がユーザの削除行ってください。またはサービスセンターまでお問い合わせください。</p>
            <br/>
            <p class="content-policy title-main">第９条（本WEBサイトにおける取引）</p>
            <p class="content-policy">ユーザが本WEBサイトのサーバを通して行う各種サービス提供者との取引は、ユーザとサービス提供者間の直接取引となります。協会らは、当該取引についてサービス提供者となる場合を除き、取引の当事者とはならず、取引に関する責任は負いません。したがって、取引に際し万一トラブルが生じた際には、ユーザとサービス提供者との間で解決していただくことになります。</p>
            <br/>
            <p class="content-policy title-main">第１０条（協会らの免責）</p>
            <p class="content-policy">
                協会らは、ユーザが本サービスもしくは本サービスを通じた他のサービスを利用したことにより、または利用できなかったことにより発生した一切の損害について、協会らの故意または重過失に基づくものを除き、いかなる責任も負わないものとします。
            </p>
            <p class="content-policy">協会らは、ユーザが本サービスや本サービスの設備に蓄積した、またはユーザが第三者に蓄積することを承認した情報やデータに対する、第三者による削除や改ざんについて、いかなる責任も負わないものとします。</p>
            <p class="content-policy">本サービスの提供、変更、遅滞、中止もしくは廃止、本サービスを利用して登録、提供される情報等の流失もしくは消失等、その他本サービスに関連して発生したユーザの損害について、協会らの故意または重過失に基づくものを除き、協会らは、いかなる責任も負わないものとします。協会らは、いかなる場合も、ユーザの逸失利益または特別な事情から生じた損害（損害発生につき協会らが予見し、または予見し得た場合を含む）について、いかなる責任も負わないものとします。</p>
            <br/>
            <p class="content-policy title-main">第１１条（禁止事項）</p>
            <p class="content-policy">本WEBサイトおよび本サービスの利用に際して、ユーザに対し次の各号の行為を行うことを禁止します。</p>
            <p class="content-policy">（１）本規約等又は法令に違反すること</p>
            <p class="content-policy">（２）協会ら、サービス提供者およびその他の第三者の権利、利益、名誉等を損ねること</p>
            <p class="content-policy">（３）青少年の心身に悪影響を及ぼす恐れがある行為、その他公序良俗に反する行為を行うこと</p>
            <p class="content-policy">（４）他の利用者その他の第三者に迷惑となる行為や不快感を抱かせる行為を行うこと</p>
            <p class="content-policy">（５）虚偽の情報を入力すること</p>
            <p class="content-policy">（６）有害なコンピュータプログラム、メール等を送信または書き込むこと</p>
            <p class="content-policy">（７）協会らのサーバその他のコンピュータに不正にアクセスすること</p>
            <p class="content-policy">（８）ユーザIDおよびパスワードを第三者に貸与・譲渡すること、または第三者と共用すること</p>
            <br/>
            <p class="content-policy title-main">第１２条（クッキー等について）</p>
            <p class="content-policy">本WEBサイトでは、利用者が再度本WEBサイトを訪問された際に、より便利に本WEBサイトをご利用いただくためにクッキーを使用することがあります。ご使用のブラウザで設定変更することにより、クッキーの受取りを拒否することもできますが、その際は、本WEBサイトの機能を十分に利用できなくなる場合があります。ブラウザの設定変更は各ソフト製造元へお問合せください。</p>
            <br/>
            <p class="content-policy title-main">第１３条（掲載内容について）</p>
            <p class="content-policy">本WEBサイトでは、掲載内容について細心の注意を払っておりますが、その内容の正確性・妥当性、ご利用目的への適合性、安全性について保証するものではありません。協会らは予告なしに掲載内容を変更・削除することがあります。 また、本WEBサイト自体の運営を場合により中断させていただくことがあります。</p>
            <br/>
            <p class="content-policy title-main">第１４条（個人情報）</p>
            <p class="content-policy">本WEBサイトおよび本サービスにおいて収集させていただいた個人情報は、以下のＵＲＬに掲載する各社「個人情報保護方針」に基づき、厳重に管理します。</p> 
            <p class="content-policy">●公益財団法人日本英語検定協会： http://www.eiken.or.jp/privacy.html</p>
            <p class="content-policy">●株式会社教育測定研究所： http://www.jiem.co.jp/privacy/index.html</p>
            <p class="content-policy">協会らは、収集させていただいた個人情報を以下の目的以外に利用しないものとします。</p> 
            <p class="content-policy">（１）検定料の支払管理（個人支払者の特定）</p>
            <p class="content-policy">（２）英検、英検IBA等の成績管理</p>
            <p class="content-policy">（３）個人別英検受験案内状への氏名等および受験結果の表示</p>
            <p class="content-policy">（４）各種状況照会画面への表示</p>
            <p class="content-policy">本WEBサイトおよび本サービスにおける個人情報の取扱いについて</p> 
            <p class="content-policy">［事業者の氏名または名称〕</p>
            <p class="content-policy">公益財団法人日本英語検定協会　／　株式会社教育測定研究所</p>
            <p class="content-policy">〔個人情報保護管理者〕</p>
            <p class="content-policy">公益財団法人日本英語検定協会　個人情報保護管理者</p>
            <p class="content-policy">株式会社教育測定研究所　個人情報保護管理者</p>
            <p class="content-policy">〔個人情報の第三者提供について〕</p>
            <p class="content-policy">取得した個人情報を当該利用目的達成の範囲内において第三者に提供することがあります。</p>
            <p class="content-policy">（１）第三者提供の目的</p>
            <p class="content-policy">上記に定める個人情報の利用目的を達成するため</p>
            <p class="content-policy">（２）提供する個人情報の項目</p>
            <p class="content-policy">生徒管理において入力された情報</p>
            <p class="content-policy">（３）提供の手段または方法</p>
            <p class="content-policy">書類の送付または電子的もしくは電磁的な方法等</p>
            <p class="content-policy">（４）当該情報の提供を受ける者または提供を受ける組織</p>
            <p class="content-policy">株式会社教育測定研究所</p>
            <p class="content-policy">（５）個人情報の取扱いに関する契約について</p>
            <p class="content-policy">協会は、当個人情報の提供を受ける組織との間で個人情報の目的外利用の禁止及び非開示契約を締結しております。</p>
            <p class="content-policy">〔個人情報を入力するにあたっての注意事項〕</p>
            <p class="content-policy">生徒本人及び保護者への周知徹底を行った上での対応をお願いしますが、貴団体が協会に対して個人情報を提供することは任意となります。</p>
            <p class="content-policy">ご参考までに、保護者との確認用の文書も準備しております。必要に応じご活用ください。</p>
            <p class="content-policy icon-link-term"><a href="<?php echo $this->basePath('/サンプル_個人情報確認(学校→保護者).docx') ?>" class="link-term">個人情報確認(学校→保護者)</a></p>
            <p class="content-policy">〔安全対策の実施〕</p>
            <p class="content-policy">当協会は、個人情報が社外に流出する、不当に改ざんされるなどといったトラブルを引き起こさないように社内規定を整備し、安全対策の実施に努めます。</p>
            <p class="content-policy">〔個人情報の開示等の求めおよびお問合せ窓口について〕</p>
            <p class="content-policy">協会らが保有する個人情報の利用目的の通知、開示、訂正・追加または削除、利用・消去および第三者への提供の停止に関するお問合せは以下のとおりです。</p>
            <p class="content-policy">《個人情報苦情及び相談窓口》</p>
            <p class="content-policy">〒162-8055　東京都新宿区横寺町55</p>
            <p class="content-policy">公益財団法人日本英語検定協会・広報課</p>
            <p class="content-policy">株式会社教育測定研究所　個人情報取り扱いに関する苦情・相談窓口</p>
            <p class="content-policy">電話：03-5775-9093</p>
            <p class="content-policy">E-mail： contact@jiem.co.jp</p>
            <p class="content-policy">午前9時30分～午後5時30分（土・日曜日、祝祭日、年末年始は除く）</p>
            <br/>
            <p class="content-policy title-main">第１５条（本サービスの中断・停止等）</p>
            <p class="content-policy">協会らは、データのバックアップなど、本サービスに必要なメンテナンスを定期的に実施し、その間、本サービスの提供を停止することがあります。</p>
            <p class="content-policy">前項に基づき本サービスの提供を停止する場合には、協会らは、停止する時期を本サービスのサイトに予め記載するものとします。但し、以下のいずれかの事由が発生した場合には、協会らは、停止する時期を本サービスのサイトに予め記載することなく、本サービスの全部または一部の提供 を停止することができるものとします。</p> 
            <p class="content-policy">（１）天災、事変、その他の非常事態が発生し、または発生する恐れがある場合</p>
            <p class="content-policy">（２）協会らのシステムやネットワークの保守を緊急に行う場合</p>
            <p class="content-policy">（３）協会らが設置する電気通信設備の障害その他やむを得ない事由が発生した場合</p>
            <p class="content-policy">（４）その他、協会らが本サービスの提供の全部または一部を停止する必要があると判断した場合</p>
            <br/>
            <p class="content-policy title-main">第１６条（特定ユーザの利用停止・ユーザ資格取消）</p>
            <p class="content-policy">以下のいずれかの事由が発生した場合には、協会らは、当該ユーザによる本サービスの利用停止、利用禁止またはユーザ登録の抹消をすることができるものとします。</p> 
            <p class="content-policy">（１）ユーザが虚偽の情報を申告または申請した場合</p>
            <p class="content-policy">（２）ユーザが過去に本サービスの利用停止、利用禁止または登録抹消をされていた場合</p>
            <p class="content-policy">（３）ユーザが本サービスの提供や運営等に支障を与え、または他のユーザもしくは協会らの権利・利益等を害するおそれがあると協会らが判断した場合</p>
            <p class="content-policy">（４）ユーザが本規約に違反した場合</p>
            <p class="content-policy">協会らは、前項各号のいずれかに該当するか否かを確認するため、いつでも、電子メール、電話その他の手段により、ユーザに対して、問合せをすることができるものとします。当該問合せに応じない場合等には、協会らは、当該ユーザの利用停止、利用禁止またはユーザ登録の抹消をすることができるものとします。</p>
            <br/>
            <p class="content-policy title-main">第１７条（サービスの変更・廃止）</p>
            <p class="content-policy">協会らは、その判断により本WEBサイトおよび本サービスの全部または一部を適宜変更・廃止できるものとします。</p>
            <br/>
            <p class="content-policy title-main">第１８条（知的財産権・著作権について）</p> 
            <p class="content-policy">本WEBサイトに掲載されている商号・商標をはじめとし、文書、イラスト、コンテンツ画像等の内容に関する著作権などの知的財産権の全ての権利は協会ら又は固有の権利所有者に帰属し、各関連法律・条例などによって保護されています。事前に協会らから文書による承諾を得ることなく、私的利用その他法律によって明示的に認められる範囲を超えて、これらの一部又は全部をそのままあるいは改変して転用、複製などをすることは一切禁止します。</p>
            <br/>
            <p class="content-policy title-main">第１９条（本規約の改定）</p>
            <p class="content-policy">協会らは、本規約を任意に改定できるものとし、また、協会らにおいて本規約を補充する規約（以下「補充規約」といいます）を定めることができます。本規約の改定または補充は、改定後の本規約または補充規約を協会ら本サイトに掲示したときにその効力を生じるものとします。この場合、ユーザは、改定後の規約および補充規約に従うものといたします。</p>
            <br/>
            <p class="content-policy title-main">第２０条（準拠法、合意管轄）</p>
            <p class="content-policy">本WEBサイトおよび本サービスの利用並びに本規約等の解釈・運用は、別段の定めのない限り、日本法に準拠するものといたします。また、この本規約等は日本語によって解釈されるものといたします。本WEBサイトの利用にかかわる全ての紛争については、別段の定めのない限り、東京地方裁判所または東京簡易裁判所を第一審の専属管轄裁判所とするものといたします。</p>
            <br/>
            <p class="content-policy">【協会ら】</p>
            <p class="content-policy">●公益財団法人日本英語検定協会</p>
            <p class="content-policy">●株式会社教育測定研究所</p>

        </div>
        <form id="frmPolicy" method="POST">
            <div class="text-center agree-policy">
                <input id="agreePolicy" name="agreePolicy" type="checkbox" value="1" class="<?php echo isset($errors['agreePolicy']) ? 'error' : '' ?>" /> <span>英検団体サポートシステム利用規約について確認しました</span>
            </div>

            <div class="box-footer text-center">
                <button type="submit"
                        class="btn btn-large-180 div-button-change btn-red">同意する</button>
            </div>
        </form>
    </div>
</div>



