<?php $this->headLink()->appendStylesheet($this->basePath('css/list_org_style.css')) ?>
<script>
    $(document).ready(function () {
        $("#return_page").focus();
    });
</script>
<div class="box">
    <div class="box-header">ユーザ情報詳細</div>
    <div class="box-body register-body user-detail">
        <div class="row org-number-view">
            <div class="col-sm-2">
                <p><?php echo $this->translate("OrganizationNo"); ?></p>
            </div>
            <div class="col-sm-5 input-org">
                <p><?php echo $this->escapeHtml($user->getOrganizationNo()) ?></p>
            </div>
        </div>
        <div class="row org-userid-view">
            <div class="col-sm-2">
                <p><?php echo $this->translate("UserId"); ?></p>
            </div>
            <div class="col-sm-5 input-user-id">
                <p><?php echo $this->escapeHtml($user->getUserId()); ?></p>
            </div>
        </div>
        <div class="row org-name-view">
            <div class="col-sm-2">
                <p><?php echo $this->translate("Name (Kanji)"); ?></p>
            </div>
            <div class="col-sm-8">
                <p><?php echo $this->escapeHtml($user->getFirstNameKanji() . $user->getLastNameKanji()); ?></p>
            </div>
        </div>

        <div class="row email-row">
            <div class="col-sm-2">
                <p><?php echo $this->translate("Email Address"); ?></p>
            </div>
            <div class="col-sm-10 class-inline-email">
                <p class="email-info"><?php echo $user->getEmailAddress(); ?></p>
            </div>
        </div>

        <div class="row org-author-view">
            <div class="col-sm-2">
                <p><?php echo $this->translate("Role"); ?></p>
            </div>
            <div class="col-sm-5 select-role styled-select">
                <p><?php echo $user->getRole()->getRoleName(); ?></p>
            </div>
        </div>

        <hr />

        <div class="row status-row">
            <div class="col-sm-2">
                <p><?php echo $this->translate("Status"); ?></p>
            </div>
            <div class="col-sm-10 class-inline-email">
                <p class="email-info"><?php echo $this->translate($user->getStatus()); ?></p>
            </div>
        </div>

        <div class="box-footer">
            <div class="text-left col-sm-4">
                <a id="return_page" href="<?php echo $redirectUrl; ?>"
                   class="btn btn-large-180"> <i class="arrow-circle-left"></i><?php echo $this->translate('Back') ?>
                </a>
            </div>
            <div class="text-right col-sm-8">
                <a href="<?php echo $this->url('editProfile'); ?>"
                   class="btn btn-large-180"> <i class="pencil-square"></i><?php echo $this->translate("Edit"); ?>
                </a>
            </div>
        </div>
    </div>
</div>