<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html>
    <head>
        <title>TODO supply a title</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <?php echo $this->headLink()->appendStylesheet($this->basePath('css/policy-login.css')); ?>
    </head>
    <body style="font-size: 20px;">
        <div>
            <p class="content-right">201●年●月●日</p>
            <div class="content-left">
                <p style="margin: 3px;">生徒の皆様へ</p>
                <p style="margin: 3px;">保護者の皆様へ</p>
            </div>
            <div class="content-right">
                <p style="margin: 3px;">公益財団法人日本英語検定協会</p>
                <p style="margin: 3px;">株式会社教育測定研究所</p>
                <p style="margin: 3px;">●●県立○○学校</p>
                <p style="margin: 3px;">○○○○</p>
            </div>
            <div class="title">
                <p style="margin: 3px;">201●年度第●回実用英語技能検定（英検）申込における</p>
                <p style="margin: 3px;">団体受験用個人情報の提供ならびに</p>
                <p style="margin: 3px;">受験案内状への個人名および前回試験結果の表記について</p>
            </div>
            <div class="content">
                <p>このたび自校にて201●年度の実用英語技能検定（英検）を実施するにあたり、株式会社教育測定研究所（以下「教測研」）が公益財団法人日本英語検定協会（以下「英検協会」）から事務委託を受けて運用する英検団体サポートシステムにおいて、受験者の成績管理・英検検定料の支払い管理等の事務管理のため、生徒の皆様の氏名、学年、組、出席番号等の在籍情報を英検協会および教測研がお預かりすること、および生徒の皆様の英検の受験に際して、受験案内状を生徒に配布しますが、その受験案内状に氏名および前回試験結果を表記するために、生徒の皆様ならびに保護者の皆様にご理解していただきたく、大変お手数をおかけしますがよろしくお願いいたします。</p>
                <p style="margin-bottom: 3px;">【英検団体サポートシステムへの在籍情報のお預かりについて】</p>

                <div style="margin-bottom: 5px;">
                    <div style="float: left;width: 20%">1.<span style="margin-left:20px;">目的</span></div>
                    <div style="float: left;width: 5%">：</div>
                    <div style="float: left;width: 70%">英検団体サポートシステムでの事務管理のため</div>
                    <div style="clear:both"></div>
                </div>
                <div style="margin-bottom: 5px;">
                    <div style="float: left;width: 20%">2.<span style="margin-left:20px;">対象データ</span></div>
                    <div style="float: left;width: 5%">：</div>
                    <div style="float: left;width: 70%">生徒の皆様の氏名、学年、組、出席番号など（住所等は含まれません）</div>
                    <div style="clear:both"></div>
                </div>
                <div style="margin-bottom: 5px;">
                    <div style="float: left;width: 20%">3.<span style="margin-left:20px;">利用方法</span></div>
                    <div style="float: left;width: 5%">：</div>
                    <div style="float: left;width: 70%">
                        <p style="margin: 3px;">成績管理、検定料の支払い管理、受験案内状への氏名の表示</p>
                        <p style="margin: 3px;">英検団体サポートシステム内の状況照会画面への表示</p>
                    </div>
                    <div style="clear:both"></div>
                </div>
                <div style="margin-bottom: 5px;">
                    <div style="float: left;width: 20%">4.<span style="margin-left:20px;">利用範囲</span></div>
                    <div style="float: left;width: 5%">：</div>
                    <div style="float: left;width: 70%">公益財団法人日本英語検定協会、および株式会社教育測定研究所</div>
                    <div style="clear:both"></div>
                </div>

                <p style="margin-bottom: 3px;">【氏名および前回試験結果の表記について】</p>
                
                <div style="margin-bottom: 5px;">
                    <div style="float: left;width: 20%">5.<span style="margin-left:20px;">目的</span></div>
                    <div style="float: left;width: 5%">：</div>
                    <div style="float: left;width: 70%">受験前に前回の試験結果を振り返り、今回の試験合格に向けて参考にしてほしいと考えています。</div>
                    <div style="clear:both"></div>
                </div>
                <div style="margin-bottom: 5px;">
                    <div style="float: left;width: 20%">6.<span style="margin-left:20px;">対象データ</span></div>
                    <div style="float: left;width: 5%">：</div>
                    <div style="float: left;width: 70%">生徒情報 [項目]学年・クラス・出席番号・氏名（漢字、カナ）</div>
                    <div style="clear:both"></div>
                </div>
                <div style="margin-bottom: 5px;">
                    <div style="float: left;width: 20%">7.<span style="margin-left:20px;">利用方法</span></div>
                    <div style="float: left;width: 5%">：</div>
                    <div style="float: left;width: 70%">
                        <p style="margin: 3px;">各自に配布する受験案内状に上記の項目を表示します。</p>
                        <p style="margin: 3px;">過去に英検の受験履歴がある場合は、受験案内状へ前回の試験結果を表示します。</p>
                    </div>
                    <div style="clear:both"></div>
                </div>
                <div style="margin-bottom: 5px;">
                    <div style="float: left;width: 20%">8.<span style="margin-left:20px;">データ利用</span></div>
                    <div style="float: left;width: 5%">：</div>
                    <div style="float: left;width: 70%">
                        <p style="margin: 3px;">生徒情報（学年・クラス・出席番号・氏名（漢字、カナ））を公益財団法人日本英語検定協会（英検協会）に提出し、過去試験結果が表記された受験案内状を作成していただきます。</p>
                        <p style="margin: 3px;">また英検協会とは、当該目的のために必要な作業終了後は提出した生徒情報を自校に返却または消去できることを文書にて取り交わしています。</p>
                    </div>
                    <div style="clear:both"></div>
                </div>
                <br/>
                <p style="margin: 3px;">受験案内状は、●月●旬に学校より生徒へ配布する予定です。</p>
                <p style="margin: 3px;">保護者の皆様にも生徒に配布した受験案内状を是非ご確認してくださいますようよろしくお願いいたします。</p>
                <br/>
                <p style="margin: 3px;">氏名および前回試験結果の表記に賛同いただけない場合は、○○先生に申し出てください。</p>
                <p style="margin: 3px;">表記しないようにいたします。</p>
            </div>
            <div class="content-right">－以上－</div>
        </div>
        <br/>
        <br/>
    </body>
</html>
