<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'OrgMnt\Module'                        => __DIR__ . '/Module.php',
    'OrgMnt\Controller\OrgController' => __DIR__ . '/src/OrgMnt/Controller/OrgController.php',
);
