<style type="text/css">
    #table1>tbody>tr>td.classwhite{
        padding: 0;
    }

    #table1>tbody>tr>td.classwhite{
        text-align: center !important;
    }
    .pointer {
        cursor: pointer;
        color: #3c8dbc;
    }
    .pointer:hover{
        outline: none;
        text-decoration: none;
        color: #72afd2;
        cursor: pointer;
    }
</style>
<?php
if ($intanceOf['case3']) {
    ?>
    <style type="text/css">
        .table>thead>tr th.money p{
            padding: 0;
            text-align: center;
        }

        .table>thead>tr th.number-of-people{
            width: 78px;
        }
        .table>thead>tr th.unit-price{
            width: 92px;
        }

        .table>thead>tr th.level{
            width: 81px;
            padding: 0;
            margin: 0;
        }

        .table>thead>tr th.total-discounted{
            padding: 0;
            margin: 0;
            width: 95px;
            padding:0;
        }

        .table>thead>tr th.total-discounted p{
            margin: 0 !important;
            text-align: center;
        }

        .table>thead>tr th.discounted{
            padding: 0;
            margin: 0;
            width: 90px;
        }
        .table>thead>tr th.money{
            width: 108px;
        }

        .table>thead>tr th.discounted p{
            margin: 0;
            padding: 0;
        }

        #table>thead>tr>td{
            padding: 0;
            margin: 0;
        }
        .table td.text-right.total {
            padding: 0;
            margin: 0;
        }
    </style>
    <?php
} else {
    ?>
    <style type="text/css">
        .table>thead>tr th.first{
            width: 70px;
        }
        .table>thead>tr th.number-of-people{
            width: 100px;
        }
    </style>
    <?php
}
?>
<style type="text/css">
    p{
        padding-right: 0px !important;
    }
    .reset-padding{
        padding-left: 0px !important;
        padding-right: 0px !important;
    }
</style>

