<div class="col-sm-2">
    <label>検定料合計 </label>
</div>
<?php if($isSpecialOrg == 1){ 
        echo '<div class="col-sm-10">';
        echo $this->translate('specialSummary');
        echo '</div>';
    }else{ ?>
<div class="clearfix"></div>
<div class="col-sm-8">
    <table class="table table-bordered" id="table1">
        <thead>
            <tr>
                <th class="first"></th>
                <th class="level"><p class="text-center">受験級</p></th>
                <th class="unit-price"><p class="text-center">単価</p></th>
                <?php if ($intanceOf['case3']) echo '<th class="discounted"><p>' . $this->translate('discountedFee') . '</p></th>'; ?>
                <th width="60" class="number-of-people"><p class="text-center">人数</p></th>
                <th class="money"><p class="text-center">金額</p></th>
                <?php if ($intanceOf['case3']) echo '<th class="total-discounted"><p>' . $this->translate('totalDiscountedFee') . '</p></th>'; ?>
            </tr>
        </thead>
        <tbody>
            <?php
            if (!empty($detailPrice['mainHall'])) {
                foreach ($detailPrice['mainHall'] as $k => $detail) {
                    ?>
                    <tr>
                        <?php
                        if ($k == 0) {
                            ?>
                            <td rowspan="7" class="text-right classwhite"><p>本会場</p></p></td>
                            <?php
                        }
                        ?>
                        <!--Column 受験級-->
                        <td class="text-right"><p class="text-right"><?php echo $detail['name']; ?></p></td>
                        <?php
                        // Collumn 単価
                        if (!$intanceOf['case4']) {
                            echo '<td class="text-right"><p class="text-right">' . $detail['price'] . '</p></td>';
                        }

                        // Collumn Discounted Fee
                        if ($intanceOf['case3'] || $intanceOf['case4']) {
                            echo ($k == 0 || $k == 1) ?
                                    '<td class="text-right"><p class="text-right">' . $detail['price'] . '</p></td>' :
                                    '<td class="text-right"><p class="text-right">' . $detail['discountPrice'] . '</p></td>';
                        }
                        ?>
                        <td class="text-right"><p class="text-right"><?php echo $detail['total']; ?></p></td>
                        <?php
                        if (!$intanceOf['case4']) {
                            echo '<td class="text-right"><p class="text-right">' . $detail['totalPrice'] . '</p></td>';
                        } else {
                            echo '<td class="text-right"><p class="text-right">' . $detail['totalDiscountPrice'] . '</p></td>';
                        }
                        ?>
                        <?php
                        if ($intanceOf['case3']) {
                            echo '<td class="text-right"><p class="text-right">' . $detail['totalDiscountPrice'] . '</p></td>';
                        }
                        ?>
                    </tr>
                    <?php
                }
            }
            ?>

            <?php if (!empty($eikenOrgDetail['cd'])): ?>
                <?php if (!empty($detailPrice['standardHall'])): ?>
                    <?php
                    $i = 1;
                    foreach ($detailPrice['standardHall'] as $detail):
                        ?>
                        <?php
                        if (in_array($i, array(1, 2))) {
                            $i++;
                            continue;
                        }
                        ?>
                        <tr>
                            <?php if ($i == 3): ?>
                                <td rowspan="5"
                                    class="text-right classwhite"><p>準会場</p>
                                    </p></td>
                            <?php endif; ?>
                            <td class="text-right"><p class="text-right"><?php echo $detail['name']; ?></p></td>
                            <td class="text-right"><p class="text-right"><?php echo $detail['price']; ?></p></td>
                            <?php if ($intanceOf['case3']) { ?> <td class="text-right"><p class="text-right"><?php echo $detail['discountPrice']; ?></p></td>  <?php } ?>
                            <td class="text-right"><p class="text-right"><?php echo $detail['total']; ?></p></td>
                            <td class="text-right"><p class="text-right"><?php echo $detail['totalPrice']; ?></p></td>
                            <?php if ($intanceOf['case3']) { ?> <td class="text-right"><p class="text-right"><?php echo $detail['totalDiscountPrice']; ?></p></td>  <?php } ?>
                        </tr>
                        <?php
                        $i++;
                    endforeach;
                    ?>
                <?php endif; ?>
            <?php endif; ?>
            <?php
            if (!$intanceOf['case3'] && !$intanceOf['case4']) {
                ?>
                <tr style="background: #f2f2f2;">
                    <td class="text-left" colspan="4">検定料合計 <i class="color-red">①</i></td>
                    <td class="text-right"><p class="text-right"><?php echo number_format($detailPrice['totalPrice'], 0, '', ','); ?>円</p></td>
                </tr>       
                <?php
            }

            if ($intanceOf['case3']) {
                ?>
                <tr>
                    <td class="text-left total" colspan="5"><p>検定料合計</p></td>

                    <td class="text-right"><p><?php echo number_format($detailPrice['totalPrice'], 0, '', ','); ?>円</p></td>
                    <td class="text-center reset-padding"><p><?php echo number_format($detailPrice['totalDiscountPrice'], 0, '', ','); ?>円<i class="color-red">①</i></p></td>
                </tr>
    <!--                <tr>
                    <td class="text-left" colspan="5"><p><?php echo $this->translate('refundForSemiMainVenue'); ?></p></td>
                    <td class="text-right" colspan="2"><p class="text-right"><?php echo number_format($detailPrice['totalDecreasePrice'], 0, '', ','); ?>円</p></td>
                </tr>    -->
                <?php
            }
            if ($intanceOf['case4']) {
                ?>
                <tr>
                    <td class="text-left" colspan="4">検定料合計 <i class="color-red">①</i></td>
                    <td class="text-right"><p class="text-right"><?php echo number_format($detailPrice['totalDiscountPrice'], 0, '', ','); ?>円</p></td>
                </tr>       
                <?php
            }
            ?>
        </tbody>
    </table>
</div>

<div class="col-sm-4">
    <table class="table table-bordered"
           style="margin-left: 10px;" id="table2">
        <thead>
            <tr>
                <th colspan="2" class="text-left" style="padding-left: 10px !important;">英検よりお支払いする費用</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td width="185" class="classcenter ">本会場運営費</td>
                <td class="classcenter"><p class="text-right"><?php echo number_format($detailFee['TotlalFeeSt'], 0, '', ','); ?>円</p></td>
            </tr>
            <?php
            //Nếu trọn thi lưu trú thì toàn bộ fee = 0
            if (!empty($eikenOrgDetail['locationType1']) && $eikenOrgDetail['locationType1'] == 2) {
                $detailFee['TotlalFeeMa'] = 0;
                $detailFee['ProcessFee'] = 0;
                $detailFee['ClassFee'] = 0;
                $detailFee['ManagementFee'] = 0;
                $detailFee['OtherFee'] = 0;
            }
            ?>
            <tr>
                <td class="classcenter "><p>準会場実施経費合計</p></td>
                <td class="classcenter"><p class="text-right"><?php echo number_format($detailFee['TotlalFeeMa'], 0, '', ','); ?>円</p></td>
            </tr>
            <tr>
                <td class="classcenter "><p style="margin-left: 30px;">運営費</p></td>
                <td class="classcenter"><p class="text-right"><?php echo number_format($detailFee['ProcessFee'], 0, '', ','); ?>円</p></td>
            </tr>
            <tr>
                <td class="classcenter "><p style="margin-left: 30px;">教室使用料</p></td>
                <td class="classcenter"><p class="text-right"><?php echo number_format($detailFee['ClassFee'], 0, '', ','); ?>円</p></td>
            </tr>
            <tr>
                <td class="classcenter "><p style="margin-left: 30px;">監督費</p></td>
                <td class="classcenter"><p class="text-right"><?php echo number_format($detailFee['ManagementFee'], 0, '', ','); ?>円</p></td>
            </tr>
            <tr>
                <td class="classcenter "><p style="margin-left: 30px;">放送設備使用料</p></td>
                <td class="classcenter"><p class="text-right"><?php echo number_format($detailFee['OtherFee'], 0, '', ','); ?>円</p></td>
            </tr>
        </tbody>
    </table>

    <table class="table table-bordered table-striped-grey"
           style="margin-left: 10px;">
        <tbody>
            <tr>
                <td width="185" class="classcenter "><p>費用合計 <i class="color-red">②</i></p></td>
                <td class="classcenter"><p class="text-right"><?php
                        $totalLDD = !empty($eikenOrgDetail['cd']) ? $detailFee['TotlalFeeMa'] : 0;
                        $totalLDD += $detailFee['TotlalFeeSt'];
                        echo number_format($totalLDD, 0, '', ',');
                        ?>円</p></td>
            </tr>
        </tbody>
    </table>
    <span style="margin-left: 12px; display: block;">英検にお支払い頂く額 （<i class="color-red">①</i>ー<i class="color-red">②</i>）</span>
    <table class="table table-bordered"
           style="margin-left: 10px;">
        <tbody>
            <tr>
                <td width="185" class="classcenter "><p>支払額合計</p></td>
                <?php
                $totalPrice = ($intanceOf['case4'] || $intanceOf['case3']) ?
                        $detailPrice['totalDiscountPrice'] : $detailPrice['totalPrice'];
                ?>
                <td class="classcenter"><p class="text-right"><?php echo number_format($totalPrice - $totalLDD, 0, '', ','); ?>円</p></td>
            </tr>
        </tbody>
    </table>
    <?php if ($grandTotal < 10 && $settingFields['semi'] !== 1) : ?>
        <div class="eik-confirmation-table-description">申込人数（合同実施の場合は吸収校との合計申込人数）が10名に満たない場合は、準会場経費は発生しません。</div>
    <?php endif; ?>
</div>
<?php } ?>
