<div class="clearfix"></div>

<div class="col-sm-2">
    <label>支払額</label>
</div>
<?php if($isSpecialOrg == 1){ 
        echo '<div class="col-sm-10">';
        echo $this->translate('specialSummary');
        echo '</div>';
}else{ ?>

<div class="col-sm-4" style="margin-left: -40px;">

    <table class="table table-bordered table-striped-grey">
        <tbody>
        <tr>
            <td width="185" class="classcenter "><p class="pointer" data-toggle="modal" data-target="#myModal">検定料合計 <span><i class="color-red">①</i></span></p></td>
            <td class="text-right"><p class="text-right">

                    <?php echo number_format($detailPrice['totalDiscountPrice'], 0, '', ','); ?>円</p>
            </td>
        </tr>
        </tbody>
    </table>
    <span>&nbsp;</span>
    <table class="table table-bordered" id="table2">
        <tbody>
            <tr class="tr-backgroud-grey">
                <td width="185" class="classcenter "><p>費用合計 <i class="color-red">②</i></p></td>
                <td class="classcenter"><p class="text-right"><?php
                        $totalLDD = !empty($eikenOrgDetail['cd']) ? $detailFee['TotlalFeeMa'] : 0;
                        $totalLDD += $detailFee['TotlalFeeSt'];
                        echo number_format($totalLDD, 0, '', ',');
                        ?>円</p></td>
            </tr>
            <tr>
                <td width="185" class="classcenter ">本会場運営費</td>
                <td class="classcenter"><p class="text-right"><?php echo number_format($detailFee['TotlalFeeSt'], 0, '', ','); ?>円</p></td>
            </tr>
            <?php
            //Nếu trọn thi lưu trú thì toàn bộ fee = 0
            if (!empty($eikenOrgDetail['locationType1']) && $eikenOrgDetail['locationType1'] == 2) {
                $detailFee['TotlalFeeMa'] = 0;
                $detailFee['ProcessFee'] = 0;
                $detailFee['ClassFee'] = 0;
                $detailFee['ManagementFee'] = 0;
                $detailFee['OtherFee'] = 0;
            }
            ?>
            <tr>
                <td class="classcenter "><p>準会場実施経費合計</p></td>
                <td class="classcenter"><p class="text-right"><?php echo number_format($detailFee['TotlalFeeMa'], 0, '', ','); ?>円</p></td>
            </tr>
            <tr>
                <td class="classcenter "><p style="margin-left: 30px;">運営費</p></td>
                <td class="classcenter"><p class="text-right"><?php echo number_format($detailFee['ProcessFee'], 0, '', ','); ?>円</p></td>
            </tr>
            <tr>
                <td class="classcenter "><p style="margin-left: 30px;">教室使用料</p></td>
                <td class="classcenter"><p class="text-right"><?php echo number_format($detailFee['ClassFee'], 0, '', ','); ?>円</p></td>
            </tr>
            <tr>
                <td class="classcenter "><p style="margin-left: 30px;">監督費</p></td>
                <td class="classcenter"><p class="text-right"><?php echo number_format($detailFee['ManagementFee'], 0, '', ','); ?>円</p></td>
            </tr>
            <tr>
                <td class="classcenter "><p style="margin-left: 30px;">放送設備使用料</p></td>
                <td class="classcenter"><p class="text-right"><?php echo number_format($detailFee['OtherFee'], 0, '', ','); ?>円</p></td>
            </tr>
        </tbody>
    </table>
<!--    <table class="table table-bordered table-striped-grey">-->
<!--        <tbody>-->
<!--            <tr>-->
<!--                <td width="185" class="classcenter "><p>費用合計<i class="color-red">②</i></p></td>-->
<!--                <td class="classcenter"><p class="text-right">--><?php
//                        $totalLDD = !empty($eikenOrgDetail['cd']) ? $detailFee['TotlalFeeMa'] : 0;
//                        $totalLDD += $detailFee['TotlalFeeSt'];
//                        echo number_format($totalLDD, 0, '', ',');
//                        ?><!--円</p></td>-->
<!--            </tr>-->
<!--            <tr>-->
<!--                <td width="185" class="classcenter "><p class="pointer" data-toggle="modal" data-target="#myModal">検定料合計<i class="color-red">①</i></p></td>-->
<!--                <td class="text-right"><p class="text-right">-->
<!---->
<!--                        --><?php //echo number_format($detailPrice['totalDiscountPrice'], 0, '', ','); ?><!--円</p>-->
<!--                </td>-->
<!--            </tr>-->
<!--        </tbody>-->
<!--    </table>-->
    <span style="display: block;margin: 15px 0 0 10px;">英検にお支払いいただく額（<i class="color-red">①</i>ー<i class="color-red">②</i>）</span>
    <table class="table table-bordered">
        <tbody>
            <tr class="tr-backgroud-pink">
                <td width="185" class="classcenter "><p>支払額合計
                        <a href="javascript:void(0);" class="href-black" data-toggle="tooltip" title="マイナス金額の場合は、英検よりお支払いする額となります">
                            <i class="glyphicon glyphicon-info-sign"></i>
                        </a></p>
                </td>
                <?php
                $totalPrice = ($intanceOf['case4'] || $intanceOf['case3']) ?
                        $detailPrice['totalDiscountPrice'] : $detailPrice['totalPrice'];
                ?>
                <td class="classcenter"><p class="text-right"><?php echo number_format($totalPrice - $totalLDD, 0, '', ','); ?>円</p></td>
            </tr>
        </tbody>
    </table>
    <?php if ($grandTotal < 10 && $settingFields['semi'] !== 1) : ?>
        <div style="margin-left: 0;" class="eik-confirmation-table-description">申込人数（合同実施の場合は吸収校との合計申込人数）が10名に満たない場合は、準会場経費は発生しません。</div>
    <?php endif; ?>
</div>
<?php
echo $this->partial('partial/collective-partials/modal-dialog-partial', array(
    'detailPrice' => $detailPrice,
    'detailFee' => $detailFee,
    'grandTotal' => $grandTotal,
    'eikenOrgDetail' => $eikenOrgDetail,
    'settingFields' => $settingFields,
    'intanceOf' => $intanceOf
));
}
?>