<?php
$this->headLink()
    ->prependStylesheet($this->basePath('css/OrgInforManagement.css?v=20161119'))
    ->prependStylesheet($this->basePath('css/studentandclass.css?v=20161119'));

$this->headScript()->appendFile($this->basePath('js/jquery-ui.js?v=20161119'));

?>
<div class="new-schoolyear">
<?php
$form->setAttribute('action', $this->url('org-mnt/default', array(
    'controller' => 'orgschoolyear',
    'action' => 'save'
)));
$form->prepare();
?>
 <?php  echo $this->form()->openTag($form); ?>
	<div class="box">
		<div class="box-header">
			<strong><?php echo $this->translate('学年情報登録') ;?></strong>
		</div>
		<div class="box-body">
			<div class="top-mark">
				<label class="font-mark"> 各学年の名称を登録します。<br>
                                    <?php
                                        $url = $this->url('org-mnt/default', array(
                                                'controller' => 'org',
                                                'action' => 'policy-grade-class'
                                            ));
                                        printf($this->translate('DescWarningGrade'),$url);
                                    ?>

				</label>

			</div>


			<div data-example-id="bordered-table">
				<div class="row">
					<div class="fl col3">
						<label><b><?php echo $this->translate('学年一般名称') ;?></b></label><span
							style="color: red;">*</span>
					</div>
					<div class="fl cl2 styled-select">
        <?php echo $this->formRow($form->get('schoolYear')); ?>
        </div>
					<div class="fl col3 2nd-label">
						<label><b><?php echo $this->translate('学年') ;?></b></label>
					</div>
					<div class="fl col4 styled-input">
        <?php echo $this->formRow($form->get('displayName')); ?>
        </div>
				</div>
			</div>
		</div>
		<div class="box-footer text-right">
			<a class="btn btn-large-180 margin-right-4"
				href="<?php echo $this->url('org-mnt/default', array('controller' => 'orgschoolyear', 'action' => 'index')) ?>">
				<i></i> <b><?php echo $this->translate('キャンセル') ;?></b>
			</a> <a id="submitform" href="#"
				class="btn btn-red  btn-large-180 margin_edit"><i
				class="fa-download-w"></i> <b><?php echo $this->translate('保存') ;?></b>
			</a>
		</div>
	</div>
    <input type="hidden" id="confirmSave" name="confirmSave" value="0">
 <?php echo $this->form()->closeTag();?>
</div>
<script type="text/javascript">
var jsMessages   = <?php echo $jsMessages; ?>;
var urlPolicy    = '<?php echo $url; ?>';
var isNotShowMSG = <?php echo isset($isNotShowMSG) ? $isNotShowMSG : 1; ?>;
var mSGPopupGradeClass = '<?php printf($this->translate('MSGPopupWarningGradeClass'),$url); ?>';

if(!jsMessages.success){
	// TODO: Review this again $('#schoolYear').addClass('error');
	ERROR_MESSAGE.show(jsMessages.data, function(){}, 'inline');
	$.each(jsMessages.data, function(){
		$('#' + this.id).addClass('error');
	})
}

var validator = $("#form").validate({
	onfocusout: false,
    onkeyup: false,
    onclick : false,
    focusInvalid: false,
	rules: {
		schoolYear : {
			required: true
		},
		displayName : {
			maxlength: 10
		}
	},
	messages: {
		schoolYear : {
		},
		displayName : {
		}
	},
	onfocusout:function (element) {
    },
    errorPlacement: function(error, element){},
	showErrors: function(errorMap, errorList) {
		this.defaultShowErrors();
		ERROR_MESSAGE.show(errorList, function(){}, 'inline');
    }
});

$(document).ready(function() {
	$('schoolYear').blur();

	 $('form:first *:input[type!=hidden][disabled!=disabled]:first').focus();

    $("#submitform").click(function(){
    	$("#form").submit();
    });
    
    if(isNotShowMSG === 0){
        CONFIRM_MESSAGE.show(mSGPopupGradeClass,function(){
                                                    $("#confirmSave").val(1);
                                                    $("#form").submit();
                                                },function(){ 
                                                    return false; 
                                                }, null , '保存', '編集に戻る');
        $('#confirmPopupModal #btnCancelConfirm').addClass('btn-red');
        $('#confirmPopupModal #btnAgreeConfirm').removeClass('btn-red');
    }
});

</script>
