<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'IBA\Module'                        => __DIR__ . '/Module.php',
    'IBA\Controller\IBAController' => __DIR__ . '/src/IBA/Controller/IBAController.php',
);
