<?php echo $this->headLink()->prependStylesheet($this->basePath('css/standard-level-recommended.css')); ?>


<div class="box frm-std-add">
    <?php
				$form->setAttribute ( 'action', $this->url ( 'invitation-mnt/default', array (
						'controller' => 'standard',
						'action' => 'update',
						'id' => $id 
				) ) );
				echo $this->form ()->openTag ( $form );
				?>
    <div class="box-header">基準級編集</div>

	<div class="box-body">
		<div class="top-mark">
				<label class="font-mark"> 各学年における取得すべき（基準となる）英検級を設定してください。 </label>
			</div>
		<div class="row">
			<div class="col-sm-1">
				<div class="rcm-bold">
					年度<span class="star">*</span>
				</div>
			</div>
			<div class="col-sm-3 styled-select">
                <?php echo $id?>
         </div>
		</div>
		<hr class="border-bot">
<?php

$count = count ( $schoolyear );
if ($count > 0) {
	?>
		<div class="col-sm-6 ">
			<div class="row row-1">
				<div class="col-sm-4 rcm-bold">学年</div>
				<div class="col-sm-7 rcm-bold">基準級</div>
			</div>
       <?php
	$i = 1;
	foreach ( $schoolyear as $key => $value ) {
		if ($i <= ceil ( $count / 2 )) {
			?>
               <div class="row row-2 styled-select">
				<div class="col-sm-4 rcm-bold">
				<?php echo $this->formlabel($form->get('hidden')->setOptions(array('label' => '' . $schoolyear[$key])));?><span
						class="star">*</span>
                <?php
			
			echo $this->formrow ( $form->get ( 'hidden' )->setAttributes ( array (
					'id' => 'hd' . $i,
					'name' => 'hdname' . $i,
					'value' => $key 
			) ) );
			?>
				</div>
				<div class="col-sm-7 ">
				<?php
			if (! empty ( $standardlevel [$key] )) {
				$form->get ( 'ddbRecommenLevel1' )->setAttribute ( 'value', $standardlevel [$key] );
			} else {
				$form->get ( 'ddbRecommenLevel1' )->setAttribute ( 'value', '' );
			}
			echo $this->formrow ( $form->get ( 'ddbRecommenLevel1' )->setAttributes ( array (
					'id' => 'ddb' . $i,
					'name' => 'name' . $i 
			) )->setValueOptions ( $eikenlevel ) );
			?>
              </div>
			</div>
           <?php }$i ++;}?>

       </div>
       <?php
}
if ($count > 1) {
	?>
		<div class="col-sm-6 ">
			<div class="row row-1">
				<div class="col-sm-4 rcm-bold">学年</div>
				<div class="col-sm-7 rcm-bold">基準級</div>
			</div>
       <?php
	$i = 1;
	foreach ( $schoolyear as $key => $value ) {
		if ($i > ceil ( $count / 2 ) and $i <= $count) {
			?>
                   <div class="row row-2 styled-select">
				<div class="col-sm-4 rcm-bold">
    				<?php echo $this->formlabel($form->get('hidden')->setOptions(array('label' => '' . $schoolyear[$key])));?><span
						class="star">*</span>
               <?php
			
			echo $this->formrow ( $form->get ( 'hidden' )->setAttributes ( array (
					'id' => 'hd' . $i,
					'name' => 'hdname' . $i,
					'value' => $key 
			) ) );
			?>
				</div>
				<div class="col-sm-7 ">
				<?php
			if (! empty ( $standardlevel [$key] )) {
				$form->get ( 'ddbRecommenLevel1' )->setAttribute ( 'value', $standardlevel [$key] );
			} else {
				$form->get ( 'ddbRecommenLevel1' )->setAttribute ( 'value', '' );
			}
			echo $this->formrow ( $form->get ( 'ddbRecommenLevel1' )->setAttributes ( array (
					'id' => 'ddb' . $i,
					'name' => 'name' . $i 
			) )->setValueOptions ( $eikenlevel ) );
			
			?>
              </div>
			</div>
           <?php
		}
		$i ++;
	}
	?>
     </div>
     <?php }?>
	</div>
    <?php echo $this->form()->closeTag(); ?>
    <div class="box-footer">
		<div class="row">
			<a class="btn btn-large-180 margin-right-10" id="btnCancel"
				href="<?php echo $this->url('invitation-mnt/default', array('controller' => 'standard', 'action' => 'index'));?>">
			  <?php echo $this->translate('Cancel')?>
	  </a> <a id="submitform" class="btn btn-red btn-large-180"
				href="javascript:void(0);"> <i class="fa-download-w"></i>
              <?php echo $this->translate('Save')?>
			</a>
		</div>
	</div>
</div>
<?php if(!empty($mess)){?>
<script type="text/javascript">
ERROR_MESSAGE.show([{id: 'ddbYear', message: '<?php echo $mess; ?>'}],function(){},'inline')
</script>
<?php }?>
<script type="text/javascript">
var errorMessages = <?php echo $error;?>;
if(typeof errorMessages != 'undefined' && !errorMessages.success)
    ERROR_MESSAGE.show(errorMessages.messages, null , 'inline');

$(document).ready(function() {
    $('form:first *:input[type!=hidden][disabled!=disabled]:first').focus();

    var validator = $("#setstandard").validate({
    	onfocusout: false,
        onkeyup: false,
        onclick: false,
        focusInvalid: false,
        errorPlacement: function(error, element){},
    	showErrors: function(errorMap, errorList) {
            this.defaultShowErrors();
            ERROR_MESSAGE.show(errorList, function(){}, 'inline');
        }
    });

    $("#submitform").click(function () {
        $("#setstandard").submit();
    });
});
</script>
