<?php use Dantai\PublicSession;

echo $this->headLink()->prependStylesheet($this->basePath('css/standard-level-recommended.css')); ?>
<?php $isViewer = PublicSession::isViewerRole(); ?>

<div class="box frm-std-show">
	<div class="box-header">基準級詳細</div>
	<form action="show" method="get" id="">
		<div class="box-body">
			<div class="row ">
				<div class="col-sm-1">
					<div class="rcm-bold">
						年度<span class="star">*</span>
					</div>
				</div>
				<div class="col-sm-3">
                    <?php echo $id; ?>
            </div>
			</div>
			<hr class="border-bot">
<?php

$count = count($standardlevel);
if ($count > 0) {
    ?>
			<div class="col-sm-6 ">
				<div class="row row-1">
					<div class="col-sm-4 rcm-bold">学年</div>
					<div class="col-sm-7 rcm-bold">基準級</div>
				</div>
       <?php
    $i = 1;
    foreach ($standardlevel as $key => $value) {
        if ($i <= round($count / 2)) {
            ?>
               <div class="row row-2 styled-select">
					<div class="col-sm-4 "><?php
            
            echo $this->formlabel($form->get('hidden')
                ->setOptions(array(
                'label' => '' . $value->getOrgSchoolYear()
                    ->getDisplayName()
            )));
            ?><span class="star">*</span>
					</div>
					<div class="col-sm-7 std-show"><?php
            
            echo $this->formlabel($form->get('ddbRecommenLevel1')
                ->setAttributes(array(
                'id' => 'ddb' . $i,
                'name' => 'name' . $i
            ))
                ->setOptions(array(
                'label' => '' . $eikenlevel[$value->getEikenLevel()
                    ->getID()]
            )));
            ?>
              </div>
				</div>
           <?php
        }
        $i ++;
    }
    ?>

       </div>
       <?php
}
if ($count > 1) {
    ?>
			<div class="col-sm-6 ">
				<div class="row row-1">
					<div class="col-sm-4 rcm-bold">学年</div>
					<div class="col-sm-7 rcm-bold">基準級</div>
				</div>
       <?php
    $i = 1;
    foreach ($standardlevel as $key => $value) {
        if ($i > round(count($standardlevel) / 2) and $i <= count($standardlevel)) {
            ?>
               <div class="row row-2 styled-select">
					<div class="col-sm-4 "><?php
            
            echo $this->formlabel($form->get('hidden')
                ->setOptions(array(
                'label' => '' . $value->getOrgSchoolYear()
                    ->getDisplayName()
            )));
            ?><span class="star">*</span>
					</div>
					<div class="col-sm-7 std-show"><?php
            
            echo $this->formlabel($form->get('ddbRecommenLevel1')
                ->setAttributes(array(
                'id' => 'ddb' . $i,
                'name' => 'name' . $i
            ))
                ->setOptions(array(
                'label' => '' . $eikenlevel[$value->getEikenLevel()
                    ->getID()]
            )));
            ?>
              </div>
				</div>
           <?php
        }
        $i ++;
    }
    ?>
     </div>
     <?php }?>
		</div>

		<div class="box-footer">
			<div class="text-left col-sm-4">
				<a class="btn btn-large-180" id=btnCancel
					href="<?php echo $this->url('invitation-mnt/default',array('controller' => 'standard','action' => 'index'));?>">
					<i class="arrow-circle-left"></i>
				<?php echo $this->translate('戻る') ;?></a>
			</div>
			<div class="text-right col-sm-8">
				<a id="btn-edit" class="btn btn-large-180" <?php echo $isViewer ? 'disabled' :'' ?>
					data-id="<?php echo $id; ?>"
					<?php if($id >= date('Y')) echo 'href="'.$this->url('invitation-mnt/default', array('controller' => 'standard', 'action' => 'edit', 'id' => '' . $id)).'"';?>>
					<i class="pencil-square"></i>編集
				</a>
			</div>
		</div>
	</form>
</div>
<?php if(!empty($mess)){?>
<script type="text/javascript">
ERROR_MESSAGE.show([{id: 'ddbYear', message: '<?php echo $mess; ?>'}],function(){},'inline')
</script>
<?php }?>
<script>
$(document).ready(function() {
	$("#btnCancel").focus();
});

       var id = ($("#btn-edit").data('id'));
       var year = new Date().getFullYear()
       if(id < year){
    	   $("#btn-edit").attr("disabled","disabled");
       }
</script>
