<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'InvitationMnt\Module'                          => __DIR__ . '/Module.php',
    'InvitationMnt\Controller\InvitationController' => __DIR__ . '/src/InvitationMnt/Controller/InvitationController.php'
);
