<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'BasicConstruction\Module'                        => __DIR__ . '/Module.php',
    'BasicConstruction\Controller\BasicConstructionController' => __DIR__ . '/src/BasicConstruction/Controller/BasicConstructionController.php',
);
