<?php $this->headLink ()->prependStylesheet ( $this->basePath ( 'css/studentandclass.css?v=20161119' ) )?>
<?php $this->headScript()->prependFile( $this->basePath ( 'js/org/class.js?v=20161119' ) )?>
<script type="text/javascript">
    var jsMessages = <?php echo $jsMessages; ?>;
    var $mess = '<?php echo $mess;?>';
</script>
<div class="detailclass">

	<?php
$form_class->setAttribute('action', $this->url('org-mnt/default', array(
    'controller' => 'class',
    'action' => 'update'
)));
echo $this->form()->openTag($form_class);
?>
 <input type="hidden" value="<?php echo $id;?>" name="id">
	<div class="box">
		<div class="box-header">
			<strong><?php echo $this->translate('クラス情報編集') ;?></strong>
		</div>
		<div class="box-body">
	
				<label class="font-mark"> 各学年のクラスの名称を登録します。<br>
					<?php
                                            $url = $this->url('org-mnt/default', array(
                                                    'controller' => 'org',
                                                    'action' => 'policy-grade-class'
                                                ));
                                            printf($this->translate('DescWarningClass'),$url);
                                        ?>

				</label>

			<div data-example-id="bordered-table">
				<div class="row">
					<div class="fl col1">
						<label><b><?php echo $this->translate('年度') ;?></b><span
							class="star">*</span></label>
					</div>
					<div class="fl col4 styled-select">
							<?php echo $this->formRow($form_class->get('year')); ?>
						</div>
				</div>
				<div class="row">
					<div class="fl col1">
						<label><b><?php echo $this->translate('学年') ;?></b><span
							class="star">*</span></label>
					</div>
					<div class="fl col3 styled-select">
							<?php echo $this->formRow($form_class->get('school_year')); ?>
						</div>
				</div>
				<div class="row">
					<div class="fl col1">
						<b><?php echo $this->translate('クラス') ;?><span class="star">*</span></b>
					</div>
					<div class="fl col3">
							<?php echo $this->formRow($form_class->get('classname')); ?>
						</div>
				</div>
				<div class="row">
					<div class="fl col1">
						<label><b><?php echo $this->translate('生徒数') ;?></b></label>
					</div>
					<div class="fl col4">
							<?php echo $this->formRow($form_class->get('sizes')); ?>
						</div>
				</div>
			</div>
		</div>
		<div class="box-footer text-right">
			<a class="btn btn-large-180 margin-right-4"
				href="<?php echo $this->url('org-mnt/default', array('controller' => 'class', 'action' => 'index'));?>">
				<i></i> <b><?php echo $this->translate('キャンセル') ;?></b>
			</a> <a id="org-class-save" onclick="ORG_EDITCLASS.edit()"
				class="btn btn-red  btn-large-180 margin_edit"
				href="javascript:void(0)"><i class="fa-download-w"></i> <b><?php echo $this->translate(' 保存') ;?></b>
			</a>
		</div>
	</div>
	<?php echo $this->form()->closeTag(); ?>
</div>