<?php $paging = $this->paginationHelper($classj, $page, '/org/class/index', $numPerPage, (empty($param)) ? '' : '/search/'.$param); ?>
<?php $this->headLink ()->prependStylesheet ( $this->basePath ( 'css/studentandclass.css' ) )?>
<script type="text/javascript">
	var jsMessages = <?php echo $jsMessages; ?>;
</script>
<?php //$this->headScript()->prependFile( $this->basePath ( 'js/classj.js' ) )?>
<div class="classmanaer">
	<div class="list-classmanaer">
	<?php
$form->setAttribute('action', $this->url('org-mnt/default', array(
    'controller' => 'class',
    'action' => 'index'
)));
echo $this->form()->openTag($form);
?>
		<div class="box">
		<div class="box-header collapsed" data-toggle="collapse" data-target="#search-box">
                <div class="search-header  sorting-field">
                    <i class="search-chevron-down"></i>
                    <?php echo $this->translate('検索条件'); ?>
                </div>
            </div>
                            <div id="search-box" aria-expanded="true" class="collapse in">
				<div class="box-body box-search-std">
					<div class="row seacrch-row">
						<div class="col-sm-1 ">
							<label> <?php echo $this->translate('年度') ;?> </label>
						</div>
						<div class="col-sm-2 styled-select">
							<?php echo $this->formRow($form->get('year')); ?>
						</div>
						<div class="col-sm-3  ">
							<label><?php echo $this->translate('学年') ;?></label>
						</div>
						<div class="col-sm-4 styled-select fix-width-380">
							<?php echo $this->formRow($form->get('school_year_add')); ?>
						</div>
						<div class="col-sm-5">
							<div class="fl cl2">
								<a href="javascript:void(0)" onclick="resetclass()"
									class="btn btn-small"><?php echo $this->translate("クリア"); ?></a>
							</div>
							<div class="fl cl3">
								<a class="btn btn-small" href="javascript:void(0)"
									onclick="searchsubmit()"><i class="fa-search"></i><?php echo $this->translate("検索"); ?></a>
							</div>
						</div>

					</div>
				</div>
                            </div>
			</div>
		</div>
		<?php echo $this->form()->closeTag(); ?>
		<div class="box">
			<div class="box-header">
				<strong><?php echo $this->translate('クラス情報') ;?></strong>
			</div>
			<div class="box-body">
				<div class="student_manager">
					<div class="std_list">
						<div class="row padding_row">
							<div class="col-sm-7 title-list class-tite">
								<label class="font-mark">登録されているクラスの名称と生徒数の一覧になります。<br>
									追加する場合は「追加」ボタンを押してください。
								</label>

							</div>
							<?php $isDisableBtn = \Dantai\PublicSession::isViewerRole(); ?>
							<div class="col-sm-5 text-right">
								<span class="seacrh_list"> <a class="btn btn-higher" <?php echo $isDisableBtn ? 'disabled' : '' ?>
									href="<?php echo $this->url('org-mnt/default', array('controller' => 'class', 'action' => 'add'))?>"><i
										class="plus-circle"></i> <?php echo $this->translate("追加"); ?></a>
								</span>
								<button class="btn btn-higher" onclick="deleteclass()" <?php echo $isDisableBtn ? 'disabled' : '' ?>>
									<i class="trash"></i> <?php echo $this->translate("削除"); ?>
								</button>
							</div>
						</div>
						<!-- 					list -->
						<div class="row">
							<form
								action="<?php echo $this->url('org-mnt/default', array('controller' => 'class', 'action' => 'delete'))?>"
								method="post" id="deleteclasss">
								<table class="table table-bordered text-center table-striped">
									<thead>
										<tr class="checkbox_list">
											<th class="checkbox-class"><input id="select_all"
												type="checkbox"></th>
											<th class="year-class text-center jyear"><?php echo $this->translate('年度') ;?></th>
											<th class="year-school-class jschool-year"><?php echo $this->translate('学年') ;?></th>
											<th class="class-class"><?php echo $this->translate('クラス') ;?></th>
											<th class="number-class"><?php echo $this->translate('生徒数') ;?></th>
											<th class="space-class"></th>
											<th class="view-class"><?php echo $this->translate('操作') ;?></th>
										</tr>
									</thead>
									<tbody id="load_dt_std">
                                        <?php if(isset($classj) && $classj->count() > 0):?>
                                		<?php foreach ($classj as $k => $v) :?>
                                		<tr id="<?php echo $v->getId();?>">
											<td><input class="checkbox1" type="checkbox"
												<?php if(isset($mess->{$v->getId()})){ ?> checked="checked"
												<?php }?> id="<?php echo $v->getId();?>"
												name="input[<?php echo $v->getId();?>]"></td>
											<td><?php echo $v->getYear();?></td>
											<td><?php echo $this->escapeHtml($v->getOrgSchoolYear()->getDisplayName());?></td>
											<td><?php echo $this->escapeHtml($v->getClassName());?></td>
											<td  class="text-right"><?php echo $v->getNumberOfStudent();?></td>
											<td></td>
											<td class="text-center"><a class="btn btn-view"
												href="<?php
                                                echo $this->url('org-mnt/default', array(
                                                    'controller' => 'class',
                                                    'action' => 'show',
                                                    'id' => $v->getId()
                                                ));
                                                ?>"><?php echo $this->translate('詳細表示') ;?></a></td>
										</tr>
                                		 <?php endforeach;
                                         endif;?>
							    </tbody>
								</table>

	   	                       <?php if(isset($classj) && $classj->count() < 1){?>
                                 <p><?php echo $this->translate("MSGnoresult");?></p>
                               <?php }?>
							</form>
						</div>
						<?php if ($classj->count() > $numPerPage) {?>
						<div class="box_padding text-center pagination_student_color">
							<nav>
								<ul class="pagination">
                                    <?php echo $paging?>
								</ul>
							</nav>
						</div>
						<?php }?>
					</div>

					<div class="bottom-mark">
						<div>
							<label class="font-mark">全ての学年におけるクラス名、生徒数（任意）の登録が完了できましたら、生徒を登録します。<br>
								生徒を登録するために、「<span>次へ</span>」を押してください。
							</label>
						</div>
						<div>
							<a class="btn btn-red btn-large-180" href="/pupil/pupil/index"> <i
								class="arrow-circle-right-w"></i> 次へ
							</a>
						</div>
					</div>


				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
$(document).ready(function() {
	if ($('input.checkbox1').not(':checked').length < 1 && $('input.checkbox1').length > 0 ){
	    $("#select_all").prop("checked", true);
	}
	COMMON.showCrossEditMessage();
    
	$('#year').focus();
	<?php if(!empty($mess)){?>
    ERROR_MESSAGE.show([{id: 'blabal', message: jsMessages.MSG1063}], function(){}, 'inline');
	<?php }?>
    $('#select_all').click(function(event) {
        if(this.checked) {
            $('.checkbox1').each(function() {
                this.checked = true;
            });
        }else{
            $('.checkbox1').each(function() {
                this.checked = false;
            });
        }
    });
});
function  searchsubmit(){
	$('#classmanager').submit();
}
function resetclass(){
	var d = new Date();
	var n = d.getFullYear();
	$('#year').val(n);
	$('#school_year_add').val('');
	$('#classmanager').submit();
}
function deleteclass(){
	var checked = $('#deleteclasss :checkbox:checked').length > 0;
	    if(checked) {
	    	CONFIRM_MESSAGE.show( jsMessages.MSG1003, function(){$('#deleteclasss').submit();});
	    } else {
		    ERROR_MESSAGE.show(jsMessages.MSG1004);
	        //ERROR_MESSAGE.show($.jiem_msg.org_msg.MSG1004,function(){alert();});
	    }
}
$('.checkbox1').click(function(event) {  //on click
  var check_checked = true;
  if(this.checked) { // check select status
      $('.checkbox1').each(function() { //loop through each checkbox
    	  if($(this).is(':checked')){

          }else{
        	  check_checked= false;
          }
      });
      if(check_checked==true){
    	  $('.table .checkbox_list #select_all').prop('checked', true);
      }
  }else{
	  $('.table .checkbox_list #select_all').prop('checked', false);
  }
});
</script>
