<?php $this->headLink ()->prependStylesheet ( $this->basePath ( 'css/studentandclass.css' ) )?>
<div class="box detailclass">
	<div class="box-header">
		<strong><?php echo $this->translate('クラス情報詳細') ;?></strong>
	</div>
	<div class="box-body">
		<div data-example-id="bordered-table">
			<div class="row">
				<div class="fl col1">
					<label><b><?php echo $this->translate('年度') ;?></b></label>
				</div>
				<div class="fl col2"><?php echo $detail->getYear();?></div>
			</div>
			<div class="row">
				<div class="fl col1">
					<b><?php echo $this->translate('学年') ;?></b>
				</div>
				<div class="fl col2"><?php echo $this->escapeHtml($detail->getOrgSchoolYear()->getDisplayName());?></div>
			</div>
			<div class="row">
				<div class="fl col1">
					<label><b><?php echo $this->translate('クラス') ;?></b></label>
				</div>
				<div class="fl col2"><?php echo $this->escapeHtml($detail->getClassName());?></div>
			</div>
			<div class="row">
				<div class="fl col1">
					<label class="lable-number-student"><b><?php echo $this->translate('生徒数') ;?></b></label>
				</div>
				<div class="fl col2"><?php echo $detail->getNumberOfStudent();?></div>
			</div>
		</div>
	</div>
	<div class="box-footer">
		<div class="text-left col-sm-4">
			<a class="btn btn-large-180" id="focusback"
			   href="<?php echo $this->url('org-mnt/default', array('controller' => 'class', 'action' => 'index')); ?>">
				<i class="arrow-circle-left"></i>
				<?php echo $this->translate('戻る'); ?>
			</a>
		</div>
		<div class="text-right col-sm-8">
			<?php
			$link = $this->url('org-mnt/default', array(
				'controller' => 'class',
				'action' => 'delete',
				'id' => $detail->getId()
			));
			$isViewerRole = \Dantai\PublicSession::isViewerRole();
			?>
			<a class="btn btn-large-180" <?php echo $isViewerRole ? 'disabled' : '' ?>
			   href="<?php echo $this->url('org-mnt/default', array('controller' => 'class', 'action' => 'edit', 'id' => $detail->getId())); ?>">
				<i class="pencil-square"></i>
				<?php echo $this->translate('編集'); ?>
			</a>
			<button class="btn btn-large-180 margin_edit" <?php echo $isViewerRole ? 'disabled' : '' ?>
			   		onclick="deleteClassDetail()"><i
					class="trash-inline"></i>
				<?php echo $this->translate('削除'); ?>
			</button>
		</div>
	</div>
</div>
<script type="text/javascript">
	$('#focusback').focus();
	var link = '<?php echo $link;?>';
	var jsMessages_detaiil = <?php echo $jsMessages; ?>;
	<?php if(!empty($mess)){?>
		ERROR_MESSAGE.show([{id: 'blabal', message: jsMessages_detaiil.MSG1005}], function () {
		}, 'inline');
	<?php }?>
	function deleteClassDetail() {
		CONFIRM_MESSAGE.show(jsMessages_detaiil.MSG1003, function () {
			window.location.replace(link);
		});
	}
</script>