<?php
$br = 0;
if (preg_match('/(?i)msie [1-8]/', $_SERVER['HTTP_USER_AGENT'])) {
    $br = 1;
} else {
    $br = 0;
}

if (isset($numDay) && $numDay == 4) {
    $bottom = '57px';
    $bottomIE9 = '52px';
} else {
    $bottom = '19px';
    $bottomIE9 = '18px';
}
?>


<style>
    .cl0 {
        border: 4px solid #e8c5c7;
        margin-top: 15px;
        width: 2350px;
    }

    .cl0-other {
        border: 4px solid #e8c5c7;
        width: 2350px;
    }

    .cl1 {
        background-color: #a41f24;
        text-align: center;
        font-size: 37px;
        border-right: 4px solid #e8c5c7;
        line-height: 80px;
        color: white;
        height: 81px;
    }

    .cl2 {
        width: 650px;
        float: left;
        border-right: 4px solid #e8c5c7;
        border-left: 2px solid #e8c5c7;
    }

    .cl3 {
        background-color: #f4dadd;
        text-align: center;
        font-size: 35px;
    }

    .number {
        background-color: #a41f24;
        color: white;
        padding: 0 15px 0 15px;
    }

    .cl4 {
        background-color: #f4dadd;
        font-size: 37px;
        margin-top: 5px;
        padding-left: 20px;
    }

    .cl5-list {
        float: left;
        width: 325px;
        padding-right: 10px;
        border-right: 4px dotted #e8c5c7;
        margin: 10px 0 10px 10px;
        text-align: center;
        font-size: 25px;
    }

    .last {
        border-right: none;
    }

    .cl5-for {
        background-color: #f4dadd;
        border-right: 3px solid white;
        vertical-align: middle;
        padding: 20px 15px;
        font-size: 30px;
    }

    .rect {
        margin: 0 30px 30px 30px;
        background-color: white;
        height: 180px;
        position: relative;
    }
</style>
<?php
/* @var $eikenScheduleDay \Application\Entity\EikenSchedule  */
$personPayment = json_decode($data["PersonalPayment"]);
?>
<div style="float: left;width: 2360px;margin-left: 83px;"><h1><?php echo $page; ?></h1></div>
<div style="width: 2360px; margin-left: 83px;">
    <div style="float: left;">
        <img style="width: 180px; height: 200px; border: none;"
             src="../../img/tpl-payment-logo.png">
    </div>
    <div style="width: 385px; margin-left: 28px; float: left;">
        <div style="font-size: 40px; font-weight: 600; margin-top: 10px">
            <?php echo $data['year']; ?>年度第<?php echo $data['EikenScheduleHidden']; ?>回
        </div>
        <div style="font-size: 39px; margin-top: 30px">
            <?php echo $hallType; ?>（団体）受験
        </div>
    </div>
    <div style="width: 1385px; float: left; margin-left: 5px;">
        <div
            style="font-size: 68px; float: left; margin-top: 20px; font-family: Meiryo;">
            <strong>実用英語技能検定</strong>
        </div>
        <div
            style="width: 300px; float: left; height: 52px; font-size: 41px; margin-left: -552px; margin-top: 120px; border: 5px solid #9e1015; border-radius: 2px; line-height: 53px">
            <strong>お申し込み方法</strong>
        </div>
    </div>
    <div
        style="width: 200px; float: right; height: 50px; background-color: black; color: white; font-size: 50px; padding: 23px 75px 40px 75px; margin: 4px 5px">
        団体専用</div>
</div>
<div style="clear: both;"></div>
<div style="width: 2360px; margin: 0 auto; margin-left: 85px">
    <div
        style="border: 4px solid #e8c5c7; display: block; height: 60px; float: left; width: 2350px;">
        <div
            style="width: 195px; float: left; color: white; background-color: #a41f24; text-align: center; font-size: 37px; line-height: 60px">
            学校名</div>
        <div
            style="width: 601px; float: left; font-size: 37px; padding-left: 25px;">
            <!-- 			団体名（漢字）  -->
            &nbsp;
        </div>
        <div
            style="width: 118px; float: left; color: white; background-color: #a41f24; text-align: center; font-size: 37px; line-height: 60px">
            年</div>
        <div
            style="width: 300px; float: left; font-size: 37px; text-align: center;">
            &nbsp;
            <!-- 			学年 -->
        </div>
        <div
            style="width: 115px; float: left; color: white; background-color: #a41f24; text-align: center; font-size: 37px; line-height: 60px">
            組</div>
        <div
            style="width: 193px; float: left; font-size: 37px; text-align: center;">
            &nbsp;
            <!-- 			クラス -->
        </div>
        <div
            style="width: 118px; float: left; color: white; background-color: #a41f24; text-align: center; font-size: 37px; line-height: 60px">
            番号</div>
        <div
            style="width: 105px; float: left; font-size: 37px; text-align: center;">
            &nbsp;
            <!-- 			1234 -->
        </div>
        <div
            style="width: 117px; float: left; color: white; background-color: #a41f24; text-align: center; font-size: 37px; line-height: 60px">
            氏名</div>
        <div
            style="width: 297px; float: left; font-size: 37px; padding-left: 28px;">
            &nbsp;
            <!-- 			氏名（漢字） -->
        </div>
    </div>

    <div style="clear: both;"></div>
    <div class="cl0" style="">
        <div style="float: left; border-right: 4px solid #f4dadd;">
            <div class="cl1" style="width: 1380px;">
                <div style="color: white;">実施要領</div>
            </div>
            <div class="cl2" style="float: left; height: 270px;">
                <div
                    style="width: 100%; background-color: #f4dadd; text-align: center; font-size: 35px; float: left;">
                    一次試験 <br> <span style="font-size: 25px;">[筆記＋リスニング]</span>
                </div>
                <div style="width: 100%; background-color: #fff; float: left;">
                    <div style="margin: 20px 10px 10px 10px; font-size: 25px;">
                        <div style="float: left; width: 21%;">試験日程:</div>
                        <div style="float: left; width: 60%;">
                            <?php
                            for ($i = 0; $i < count($examDay); $i ++) {
                                if(!empty($examDay[$i][0])){
                                $showDate = explode("-", $examDay[$i][0]);
                                ?>
                                <span style="width: 100%;"><?php echo $showDate[0] . "年" . (int) $showDate[1] . "月" . (int) $showDate[2] . "日" . "（" . $examDay[$i][1] . "）"; ?></span><br/>
                                <?php
                                }
                            }
                            ?>
                        </div>
                    </div>
                    <div
                        style="float: left; border-right: 1px solid #f4dadd; width: 100%; font-size: 25px; overflow: hidden;">
                        <div style="float: left; width: 21%; margin-left: 8px;">受験会場:</div>
                        <div
                            style="float: left; width: 75%; text-align: left; overflow: hidden; word-wrap: break-word">
                                <?php echo $this->escapeHtml($data['ExamPlace']); ?>
                        </div>
                    </div>
                </div>
            </div>
            <div class="cl2"
                 style="float: left; height: 270px; border: none; width: 725px;">
                <div
                    style="width: 100%; background-color: #f4dadd; text-align: center; font-size: 35px; float: left;">
                    二次試験<br> <span style="font-size: 25px;">[面接試験]</span>
                </div>
                <div style="width: 100%; background-color: #fff; float: left;">
                    <p style="margin: 8px 10px 0px 10px; font-size: 25px;">
                        試験日程：（A日程）<?php
                        echo $eikenScheduleDay->getRound2Day1ExamDate() != Null ?
                                ($eikenScheduleDay->getRound2Day1ExamDate()->format('Y') . '年' .
                                (int) $eikenScheduleDay->getRound2Day1ExamDate()->format('m') . '月' .
                                (int) $eikenScheduleDay->getRound2Day1ExamDate()->format('d') . '日') : ''
                        ?>（<?php echo $dayRound2A; ?>）
                    </p>
                    <p style="margin: 0px 0px 0px 135px; font-size: 25px;">
                        （B日程）<?php
                        echo $eikenScheduleDay->getRound2Day2ExamDate() != Null ?
                                ($eikenScheduleDay->getRound2Day2ExamDate()->format('Y') . '年' .
                                (int) $eikenScheduleDay->getRound2Day2ExamDate()->format('m') . '月' .
                                (int) $eikenScheduleDay->getRound2Day2ExamDate()->format('d') . '日') : ''
                        ?>（<?php echo $dayRound2B; ?>）
                    </p>
                    <p style="margin: 0px 0px 0px 10px; font-size: 25px;">
                        受験会場：英検本会場
                    </p>
                    <p style="margin: 0px 5px 0px; font-size: 25px;">※詳細は『二次受験票』にてご案内</p>
                </div>
            </div>
        </div>
        <div
            style="position: relative; float: left; height: 229px; width: 960px;">
            <div>
                <div style="width: 399px; margin-left: -3px; float: left;"
                     class="cl1">
                    検定料 <span style="font-size: 30px; color: #fff">（税込）</span>
                </div>
                <div
                    style="float: left; width: 520px; font-size: 25px; margin-left: 20px; height: auto;">
                        <?php if ($data['HallType'] != 1) { ?>
                        <div style="width: 100%; float: left;">※5級～2級は準会場での受験料金です。</div>
                    <?php } ?>
                    <div style="width: 100%; float: left;">※一次試験免除者も同額です。</div>
                </div>
            </div>
            <div
                style="float: left; font-size: 30px; margin: 0; width: 910px; margin-top: 20px;height:132px;">
                    <?php
                    //$priceOfHall = array_reverse($priceOfHall);
                    if(isset($priceOfHall))
                    {
                        $price1 = array_slice($priceOfHall, 0, 3);
                        $price2 = array_slice($priceOfHall, 3, 3);
                        $price3 = array_slice($priceOfHall, 6, 3);
                    
                    ?>
                    <div style="float: left; width: 25%; height: auto">
                        <?php foreach ($price1 as $key => $price) { ?>
                            <div style="float: left; width: 100%; margin-left: 50px;">
                                <div style="float: left; width: 35%; text-align: center;"><?php echo $price["name"]; ?></div>
                                <div style="float: left; width: 60%;">----円</div>
                            </div>
                        <?php } ?>
                    </div>
                    <div style="float: left; width: 25%; height: auto">
                        <?php
                        foreach ($price2 as $key => $price) {
                            ?>
                            <div style="float: left; width: 100%; margin-left: 50px;">
                                <div style="float: left; width: 35%; text-align: center;"><?php echo $price["name"]; ?></div>
                                <div style="float: left; width: 60%;">----円</div>
                            </div>
                            <?php
                        }
                        ?>
                    </div>
                    <div style="float: left; width: 25%; height: auto">
                        <?php
                        foreach ($price3 as $key => $price) {
                            ?>
                            <div style="float: left; width: 100%; margin-left: 50px;">
                                <div style="float: left; width: 35%; text-align: center;"><?php echo $price["name"]; ?></div>
                                <div style="float: left; width: 60%;">----円</div>
                            </div>
                            <?php
                        }
                    
                    ?>
                </div>
                <?php 
                }
                ?>

            </div>
            <div style="width: 954px; border: 4px solid #a41f24; margin-top: <?php echo ($br == 0) ? $bottomIE9 : $bottom ?>; line-height: 80px; float: left;">
                <div style="float:left;width: 280px; color: white; background-color: #a41f24; text-align: center; font-size: 36px;">
                    お申し込み期限
                </div>
                <div style="width: 670px; float: left; font-size: 36px; background-color: #FEFBC6;">
                    <span style="margin-left: 20px;">
                        <?php echo ($monthDeadLine != '') ? (int) $monthDeadLine : ' '; ?>月<?php echo ($dayDeadLine != '') ? (int) $dayDeadLine : ' '; ?>日（<?php echo ($deadDay != '') ? $deadDay : ' '; ?>） 厳守
                    </span>
                </div>
            </div>
            <div style="clear: both;"></div>
        </div>
        <div style="clear: both;"></div>
    </div>
    <!-- <div style="margin-top: 20px; width: 1350px;border:1px solid red;">-->
    <div
        style="margin-top: 20px; width: 2350px; border: 4px solid #e8c5c7;">

        <div style="color: white;">
            <div
                style="background-color: #a41f24; color: #fff; padding-left: 20px; padding-right: 20px; font-size: 37px; line-height: 70px; width: 15%">
                お申し込み方法</div>
        </div>

        <?php if ($data["PaymentType"] == 0 && in_array(0, $personPayment)) { ?>
            <div style="float: left;height: 80px; margin-bottom: 5px; margin-top: 10px;">
                <div style="position: relative;float: left; left: 20px;z-index: 999999">
                    <img src="../../img/tpl-payment-ico-credit.png" />
                </div>
                <div class="cl4" style="float: left; width: 2330px; margin-top: -90px;z-index: 1">
                    <span style="margin-left: 100px;"> クレジットカードでお支払いの場合 </span>
                    <span style="font-size: 25px;">※未成年者の方のお申し込みには、保護者の同意が必要です。</span>
                </div>
            </div>
            <div style="clear: both;"></div>

            <div>
                <div
                    style="margin-left: 10px; float: left; font-size: 25px; margin-top: 10px;width: 99%;">
                    <p style="margin: 0 0 0 10px;">インターネットからクレジット支払をしてお申し込みいただけます。</p>
                    <ul style="list-style-type: none; margin: 5px 0 5px 0; width: 48%; float: left;">
                        <li style="margin-bottom: 5px;">
                            <span class="number" style="float: left; width: 15px;">1</span> 
                            <span style="float: left; margin-left: 3px; width: 980px">本案内状の下部にあるQRコードを使用するか、直接URL（https://jukensha-support.eiken.or.jp）を指定して受験者サポートシステムにアクセスしてください。</span>
                            <div style="clear: both;"></div>
                        </li>

                        <li style="margin-bottom: 5px;"><span class="number" style="float: left; width: 15px;">2</span> 
                            <span style="float: left; margin-left: 3px; width: 980px"> 団体ID、認証キーを入力してログインしてください。</span>
                            <div style="clear: both;"></div>
                        </li>
                        <li style="margin-bottom: 5px;"><span class="number" style="float: left; width: 15px;">3</span> 
                            <span style="float: left; margin-left: 3px; width: 980px">画面の案内に従って「お申し込み」ボタンを押して申込ページへお進み下さい。</span>
                            <div style="clear: both;"></div>
                        </li>
                    </ul>
                    <ul style="list-style-type: none; margin: 5px 0 5px 0; width: 48%; float: left;">

                        <li style="margin-bottom: 10px;">
                            <span class="number" style="float: left; width: 15px;">4</span>
                            <span style="float: left; margin-left: 3px; width: 970px;">受験級や受験会場など必要な項目を入力して「次へ」ボタンを押し、内容を確認後「申込確定」ボタンを押します。</span>
                            <div style="clear: both;"></div>
                        </li>
                        <li style="margin-bottom: 10px;">
                            <span class="number" style="float: left; width: 15px;">5</span>
                            <span style="float: left; margin-left: 3px; width: 1026px;">「申込確定」後に支払い方法を聞かれるので、「クレジットで支払う」ボタンを押します。</span>
                            <div style="clear: both;"></div>
                        </li>
                        <li style="margin-bottom: 10px;">
                            <span class="number" style="float: left; width: 15px;">6</span>
                            <span style="float: left; margin-left: 3px; width: 1026px;">クレジットカード情報を入力して「次へ」ボタンを押し、内容をよく確認したら「確定」ボタンを押してください。</span>
                            <div style="clear: both;"></div>
                        </li>
                    </ul>
                    <!-- <p style="margin: 0 0 0 10px;">
                        <span style="background-color: #f4dadd; border: 4px solid #a41f24;">すでに本会場登録がお済みの方</span>
                        は登録したユーザーIDとパスワードでログインし、
                    </p>
                    <p style="margin: 0 0 0 10px;">トップページにある準会場（団体）受験の「お申し込みはこちら」ボタンより、申込ページへお進みください。</p>-->                
                    </div> 

                <!--<div
                    style="width: 25%; float: right; background-color: #f4dadd; text-align: center; margin: 30px 30px 0 0">
                    <p style="font-size: 60px; font-style: bold; margin: 0px">英検受験者!</p>
                    <div class="rect" style="height: 140px;">
                        <span
                            style="position: absolute; left: 20px; font-size: 45px; top: 30px;">
                                <?php //echo $this->escape($organizationNo). '' . sprintf("%'.08d", ($this->escape($pupil->getSerialId())));  ?>
                        </span>
                    </div> 
                </div>-->

                <div style="clear: both;"></div>
            </div>
        <?php } ?>
        <div style="clear: both;"></div>

        <?php if ($data["PaymentType"] == 0 && in_array(1, $personPayment)) { ?>
            <div style="position: relative; height: 80px; margin-bottom: 10px; margin-top: 10px;">
                <div style="float: left;  margin-left: 20px;margin-top: -5px;">
                    <img src="../../img/tpl-payment-ico-convenience.png" />
                </div>
                <div class="cl4" style="width: 2330px; margin-top: 16px;">
                    <span style="margin-left: 10px;">コンビニ/ゆうちょ銀行でお支払いの場合</span>
                </div>
            </div>
            <div style="clear: both;"></div>
            <?php 
            $listEikenLevelArr = $listEikenLevel ? json_decode($listEikenLevel,true) : '';
            $showDes = false;
            $arrayCompe = array(0=>"3",1=>"4",2=>"5",3=>"6",4=>"7");
            if($listEikenLevelArr){
                $showDes = true;
                foreach ($listEikenLevelArr as $kyu){
                    if(in_array($kyu, $arrayCompe)){
                        $showDes = false;
                    }
                }
            }
            //in case is main venue, don't show section combini and show guideline 
            if($data['HallType'] == 1 || ($data['HallType'] == 0 && $showDes == true) ){
                ?>
            <div style="margin-left: 10px; float: left; font-size: 25px; margin-top: 10px; margin-bottom: 10px; width: 99%;">
                <p style="margin: 0 0 0 10px;">インターネットからクレジット支払をしてお申し込みいただけます。</p>
                <ul style="list-style-type: none; margin: 5px 0 5px 0; width: 48%; float: left;">
                        <li style="margin-bottom: 5px;">
                            <span class="number" style="float: left; width: 15px;">1</span> 
                            <span style="float: left; margin-left: 3px; width: 980px">本案内状の下部にあるQRコードを使用するか、直接URL（https://jukensha-support.eiken.or.jp）を指定して受験者サポートシステムにアクセスしてください。</span>
                            <div style="clear: both;"></div>
                        </li>

                        <li style="margin-bottom: 5px;"><span class="number" style="float: left; width: 15px;">2</span> 
                            <span style="float: left; margin-left: 3px; width: 980px"> 団体ID、認証キーを入力してログインしてください。</span>
                            <div style="clear: both;"></div>
                        </li>
                        <li style="margin-bottom: 5px;"><span class="number" style="float: left; width: 15px;">3</span> 
                            <span style="float: left; margin-left: 3px; width: 980px">画面の案内に従って「お申し込み」ボタンを押して申込ページへお進み下さい。</span>
                            <div style="clear: both;"></div>
                        </li>
                    </ul>
                    <ul style="list-style-type: none; margin: 5px 0 5px 0; width: 48%; float: left;">

                        <li style="margin-bottom: 10px;">
                            <span class="number" style="float: left; width: 15px;">4</span>
                            <span style="float: left; margin-left: 3px; width: 970px;">受験級や受験会場など必要な項目を入力して「次へ」ボタンを押し、内容を確認後「申込確定」ボタンを押します。</span>
                            <div style="clear: both;"></div>
                        </li>
                        <li style="margin-bottom: 10px;">
                            <span class="number" style="float: left; width: 15px;">5</span>
                            <span style="float: left; margin-left: 3px; width: 1026px;">「申込確定」後に支払い方法を聞かれるので、「コンビニで支払う」ボタンを押します。</span>
                            <div style="clear: both;"></div>
                        </li>
                        <li style="margin-bottom: 10px;">
                            <span class="number" style="float: left; width: 15px;">6</span>
                            <span style="float: left; margin-left: 3px; width: 1026px;">入力番号①と入力番号②が表示されます。この番号は、コンビニでの支払い時に必要ですので必ずメモを取ってください。この番号を持って、コンビニにて支払いを行ってください。</span>
                            <div style="clear: both;"></div>
                        </li>
                    </ul>
            </div>
            <div style="clear: both;"></div>
            <?php }?> 
           <div style="margin-left: 10px; font-size: 25px;">
                <p style="margin: 0 0 0 10px;">以下のコンビニエンスストア情報端末、またはゆうちょ銀行ATMよりお申し込みいただけます。</p>
                <p style="margin: 0 0 0 10px;">以下の説明をご参照の上、店頭にてお手続きください。（コンビニ各店頭/郵便局により端末に表示されるご案内が異なります。）</p>
                <div>
                    <span
                        style="border: 4px solid #a41f24; background-color: #FEFBC6; margin-left: 10px; padding-left: 10px;">
                        セブンイレブンからのお申し込みはできません。 </span>
                </div>
            </div>
            <?php
            $countCombini = count($combini);
            $percent = 98 / $countCombini;
            $count = 0;
            $fontBigWord = 31 - $countCombini;
            $fontSmallWord = 24 - $countCombini;
            $fontSmallWordGeneral = 26 - $countCombini;
            $fontSize = 0;
            ?>
            <div
                style="width: 100%; margin: 0 auto; margin-top: 20px; height: auto; margin-left: 10px;">
                    <?php
                    foreach ($combini as $key => $value) {
                        $count++;
                        ?>
                    <div style="float:left;width: <?php echo ($count == $countCombini) ? $percent : $percent; ?>%; border-right: <?php echo ($count == $countCombini) ? 'none' : '4px dotted #e8c5c7'; ?>;">
                        <?php
                        if (!empty($value["subName1"])) {
                            $fontSize = $fontSmallWord;
                            ?>
                            <div
                                style="float: left; margin-left: 1%; width: 47%; height: 100px; background: #f4dadd; padding-top: 10px;">
                                <p
                                    style="text-align: center; font-size: <?php echo $fontBigWord; ?>px; vertical-align: middle; margin-top: <?php echo (!empty($value["subName"]) ? '14px' : '25px'); ?>;"><?php echo $value["name"]; ?><br />
                                    <span style="font-size: 25px;"><?php echo!empty($value["subName"]) ? '＜' . $value["subName"] . '＞' : '' ?></span>
                                </p>
                            </div>
                            <div
                                style="float: left; margin-left: 1%; width: 48.5%; height: 100px; background: #f4dadd; padding-top: 10px;">
                                <p
                                    style="text-align: center; font-size:  <?php echo $fontBigWord; ?>px; vertical-align: middle; margin-top: <?php echo (!empty($value["subName1"]) ? '14px' : '25px'); ?>;"><?php echo $value["name1"]; ?><br />
                                    <span style="font-size:  <?php echo $fontSize; ?>px;"><?php echo!empty($value["subName1"]) ? '＜' . $value["subName1"] . '＞' : '' ?></span>
                                </p>
                            </div>
                            <?php
                        } else {
                            $fontSize = $fontSmallWordGeneral;
                            ?>
                            <div
                                style="margin: 0 auto; width: 96%; height: 100px; background: #f4dadd; padding-top: 10px;">
                                <p
                                    style="text-align: center; font-size:<?php echo $fontBigWord; ?>px; vertical-align: middle; margin-top: <?php echo (!empty($value["subName"]) ? '14px' : '25px'); ?>;"><?php echo $value["name"]; ?><br />
                                    <span style="font-size:  <?php echo $fontSize; ?>px;"><?php echo!empty($value["subName"]) ? '＜' . $value["subName"] . '＞' : '' ?></span>
                                </p>
                            </div>
                        <?php } ?>
                        <div
                            style="float: left; margin-top: 5px; margin-left: 2%; text-align: left; font-size: 25px;">
                            <ul style="list-style-type: none; padding: 0">
                                <li style="margin-bottom: 5px;">
                                    <div style="clear: both;"></div>
                                    <ul style="list-style-type: none; margin-left: -40px;">
                                        <li style="float: left;"><span class="number">1</span></li>
                                    </ul>
                                    <ul style="list-style-type: none; margin-left: 10px;">
                                        <li style="float: left;"><span><?php echo!empty($value["step1"]) ? $value["step1"] : '' ?></span></li>
                                    </ul>
                                    <div style="clear: both;"></div>
                                </li>
                                <li style="margin-bottom: 5px;">
                                    <ul style="list-style-type: none; margin-left: -40px;">
                                        <li style="float: left;"><span class="number">2</span></li>
                                    </ul>
                                    <ul style="list-style-type: none; margin-left: 10px;">
                                        <li style="float: left;"><span><?php echo!empty($value["step2"]) ? $value["step2"] : '' ?></span></li>
                                    </ul>
                                    <div style="clear: both;"></div>
                                </li>
                                <li style="margin-bottom: 5px;">
                                    <ul style="list-style-type: none; margin-left: -40px;">
                                        <li style="float: left;"><span class="number">3</span></li>
                                    </ul>
                                    <ul style="list-style-type: none; margin-left: 10px;">
                                        <li style="float: left;"><span><?php echo!empty($value["step3"]) ? $value["step3"] : '' ?></span></li>
                                    </ul>
                                    <div style="clear: both;"></div>
                                </li>
                                <li style="margin-bottom: 5px;">
                                    <ul style="list-style-type: none; margin-left: -40px;">
                                        <li style="float: left;"><span class="number">4</span></li>
                                    </ul>
                                    <ul style="list-style-type: none; margin-left: 10px;">
                                        <li style="float: left;"><span><?php echo!empty($value["step4"]) ? $value["step4"] : '' ?></span></li>
                                    </ul>
                                    <div style="clear: both;"></div>
                                </li>
                                <?php if (!empty($value["step5"])) { ?>
                                    <li style="margin-bottom: 5px;">
                                        <ul style="list-style-type: none; margin-left: -40px;">
                                            <li style="float: left;"><span class="number">5</span></li>
                                        </ul>
                                        <ul style="list-style-type: none; margin-left: 10px;">
                                            <li style="float: left;"><span><?php echo $value["step5"] ?></span></li>
                                        </ul>
                                        <div style="clear: both;"></div>
                                    </li>
                                <?php } ?>
                            </ul>
                        </div>
                    </div>
                <?php } ?>
            </div>
            <?php
            $countCombini = count($combini);
            $percent = ceil(90 / $countCombini);
            foreach ($combini as $key => $value) {
                
            }
            ?>
            <div style="clear: both;"></div>
            <?php 
            $listEikenLevelArr = !empty($listEikenLevel) ? json_decode($listEikenLevel,true) : '';
            $arrayCompe = array(0=>"1",1=>"2");
            $showCombini = false;
            if(!empty($listEikenLevelArr) && !empty(array_diff($listEikenLevelArr,$arrayCompe))){
                $showCombini = true;
            }
            
            
            //in case is main venue, don't show section combini and show guideline
            if($data['HallType'] != 1 && $showCombini == true){
                
                ?>
                
                <div class="cl4" style="margin: 20px;">
                    <div style="width: 80%; float: left;">
                    <p style="margin: 10px 0 0 25px;">入力番号①<span style="margin: 0 0 0 25px; font-size: 25px;">( 受験を希望する級の「6桁の番号」を入力してください。)</span></p>
                    <p style="margin: 2px 0 0 25px; font-size: 25px;">※準1級、1級を受験される方は、本案内状の下部にあるQRコードを使⽤するか、URL（https://jukensha-support.eiken.or.jp）から受験者サポートシステムにアクセスし、申込情報を登録するとコンビニの支払番号が発番されます。</p>
                        <div class="rect" style="height: 130px;">
                            <div
                                style="font-size: 30px; position: relative; top: 15px; left: 15px;">
                                <span style="margin-right: 30px; margin-left: 30px;"><?php //echo $val;     ?></span>
                            </div>
                        </div>
                    </div>

                    <div style="width: 20%; float: right;">
                        <p style="margin: 10px 0 0 25px;">入力番号②</p>
                        <p style="margin: 0 0 0 25px; font-size: 25px;">以下の番号を入力してください。</p>
                        <div class="rect" style="height: 130px;margin-top: 38px;">
                            <span
                                style="position: relative; top: 35px; left: 15px; font-size: 35px;"><?php //echo $telNo;        ?></span>
                        </div>
                    </div>
                    <div style="clear: both;"></div>
                </div>
                <p style="margin: 0 0 0 25px; font-size: 25px; color: red">※入力番号①②は、あなた専用の番号です。他の人の受験案内状に記載された番号は使用できませんので、ご注意ください。</p>
            <?php }?>
        <?php } ?>

        <div class="cl4">お支払い手続きのご注意</div>
        <div class="rect" style="height: auto; line-height: 30px;">
            <span style="position: relative; top: 15px; font-size: 25px;">
                ●上記以外の店舗では、お支払いいただけません。●本用紙をコンビニエンスストアのレジに提出してもお支払いできません。お支払い期限を過ぎた支払用紙はご利用できません。●コンビニエンスストアでのお支払いは現金のみとなります。●コンビニ端末で入力する情報は本用紙に印刷された番号のみです。住所・氏名などを入力する必要はありません。●お支払い後の返金は一切できません。また、次回以降の検定料への充当もできません。あらかじめご了承ください。
            </span>
        </div>
        <div style="clear: both;"></div>
    </div>
    <div style="width: 2354px;">
        <div class="cl4" style="margin-top: 30px;">ダブル受験について</div>
        <div class="rect" style="font-size: 30px;">
            <?php echo ($data['DoubleEikenMessage'] != '') ? $this->escapeHtml($data['DoubleEikenMessage']) : ''; ?>
        </div>
    </div>
    <div class="cl0-other"
         style="border-top: none; margin-top: 0px; font-size: 25px;">
        <div class="cl4">受験者サポートシステム（申込登録・クレジットカード支払・英ナビ利用登録）へのアクセス方法</div>
        <div
            style="float: left; width: 48%; margin-left: 30px; margin-bottom: 20px;">
            <p style="height: 100px; margin-bottom: 10px; margin-top: 10px;">
                <span class="number">1</span><span style="margin-left: 10px;">
                    スマートフォンもしくはPCより下記のURLにアクセスしてください。 </span>
            </p>
            <div class="cl4">
                <div style="width: 20%; float: left;">
                    <p style="margin: 10px 0 0 25px;">QRコード</p>
                    <div style="height: 180px; width: 180px;" class="rect">
                        <img style="border: none; height: 180px; width: 180px;"
                             src="../../img/tpl-payment-qrcode.png">
                    </div>
                </div>

                <div style="width: 80%; float: right;">
                    <p style="margin: 10px 0 0 25px;">URL</p>
                    <div style="height: 180px;" class="rect">
                        <span style="margin-left: 20px; position: absolute; top: 60px;">https://jukensha-support.eiken.or.jp</span><br>
                    </div>
                </div>
                <div style="clear: both;"></div>
            </div>
        </div>

        <div
            style="float: right; width: 48%; margin-right: 30px; margin-bottom: 20px;">
                <p style="height: 100px; margin-bottom: 10px; margin-top: 10px;">
                    <span class="number">2</span> 
                    <span style="margin-left: 10px;">画面の案内に従って必要事項を入力の上、送信してください。</span><br>
                    <span style="margin-left: 60px;">受験お申し込みページの「団体ID」「認証キー」欄に以下の番号を入力して「ログイン」ボタ</span><br>
                    <span style="margin-left: 60px;">ンを押して下さい。 </span>
                </p>
            <div class="cl4">
                <div style="width: 35%; float: left;">
                    <p style="margin: 10px 0 0 25px;">団体ID</p>
                    <div style="height: 80px;" class="rect">
                        <span style="position: absolute; top: 20px; left: 15px;"><?php //echo $this->escape($pupil->getOrganization()->getOrganizationNo());        ?></span>
                    </div>
                </div>

                <div style="width: 65%; float: right;">
                    <p style="margin: 10px 0 0 25px;">認証キー</p>
                    <div style="height: 80px;" class="rect">
                        <span style="position: absolute; top: 15px; left: 15px;"><?php //echo sprintf("%'.08d", ($this->escape($pupil->getSerialId())));         ?></span>
                    </div>
                </div>
                <div style="clear: both;"></div>
                <div style="margin: 0 0 0 25px; font-size: 25px; height: 100px;">
                    <p style="margin: 0">※認証キーはあなた専⽤の番号です。他の⼈の受験案内状に記載された番号は使⽤できません</p>
                    <p>&nbsp;</p>
                </div>
            </div>
        </div>


        <div style="clear: both;"></div>
    </div>

    <div style="width: 2350px">
        <p
            style="font-size: 48px; margin-top: 10px; margin-bottom: 10px; text-align: center; border-bottom: 1px solid #B8B8B8">
            上記のURLにアクセスした後、「英ナビ！を使⽤する」から英ナビ！にログインして学習できます</p>
        <center style="font-size: 30px; margin-bottom: 10px;">
            【お申し込みに関するお問い合わせ】英検サービスセンター（個人受付）　電話番号：03-3266-8311 受付時間：9:30〜17:00（⼟・⽇・祝⽇を除く）</center>
    </div>
</div>
