<?php
$br = 0;
if (preg_match('/(?i)msie [1-8]/', $_SERVER['HTTP_USER_AGENT'])) {
    $br = 1;
} else {
    $br = 0;
}
if (isset($numDay) && $numDay == 4) {
    $bottom = '57px';
    $bottomIE9 = '52px';
} else {
    $bottom = '19px';
    $bottomIE9 = '18px';
}
?>
<style type="text/css">
    .cl0 {
        border: 4px solid #e8c5c7;
        margin-top: 20px;
        width: 2350px;
    }

    .cl0-other {
        border: 4px solid #e8c5c7;
        width: 2350px;
    }

    .cl1 {
        background-color: #a41f24;
        text-align: center;
        font-size: 37px;
        border-right: 4px solid #e8c5c7;
        line-height: 80px;
        color: white;
        height: 81px;
    }

    .cl2 {
        width: 650px;
        float: left;
        border-right: 4px solid #e8c5c7;
    }

    .cl3 {
        background-color: #f4dadd;
        text-align: center;
        font-size: 35px;
    }

    .number {
        background-color: #a41f24;
        color: white;
        padding: 0 15px 0 15px;
    }

    .cl4 {
        background-color: #f4dadd;
        font-size: 37px;
        margin-top: 5px;
        padding-left: 20px;
        /*font-weight: 600;*/
    }

    .cl5-list {
        float: left;
        width: 325px;
        padding-right: 15px;
        border-right: 4px dotted #e8c5c7;
        margin: 20px 0 20px 20px;
        text-align: center;
        font-size: 25px;
    }

    .last {
        border-right: none;
    }

    .cl5-for {
        background-color: #f4dadd;
        border-right: 3px solid white;
        padding: 20px 10px 20px 10px;
        vertical-align: middle;
        font-size: 22px;
    }

    .rect {
        margin: 0 30px 30px 30px;
        background-color: white;
        height: 180px;
        position: relative;
    }
</style>
<?php
/* @var $eikenScheduleDay \Application\Entity\EikenSchedule  */
?>
<div style="float: left;width: 2360px;margin-left: 83px;"><h1><?php echo $page; ?></h1></div>
<div style="width: 2360px;margin-left: 83px;">
    <div style="float: left;">
        <img style="width: 180px; height: 200px; border: none;"
             src="../../img/tpl-payment-logo.png">
    </div>
    <div style="width: 385px; margin-left: 28px; float: left;">
        <div style="font-size: 40px; font-weight: 600; margin-top: 10px">
            <?php echo $data['year']; ?>年度第<?php echo $data['EikenScheduleHidden']; ?>回
        </div>
        <div style="font-size: 39px; margin-top: 30px">
            <?php echo $hallType; ?>（団体）受験
        </div>
    </div>
    <div style="width: 1385px; float: left; margin-left: 5px;">
        <div
            style="font-size: 68px; float: left; margin-top: 20px; font-family: Meiryo Reguler;">
            <strong>実用英語技能検定</strong>
        </div>
        <div
            style="width: 300px; float: left; height: 52px; font-size: 41px; margin-left: -552px; margin-top: 120px; border: 5px solid #9e1015; border-radius: 2px; line-height: 53px">
            <strong>お申し込み方法</strong>
        </div>
    </div>
    <div
        style="width: 200px; float: right; height: 50px; background-color: black; color: white; font-size: 50px; padding: 23px 75px 40px 75px; margin: 4px 5px">
        団体専用</div>
</div>
<div style="clear: both;"></div>
<div style="width: 2360px; margin: 0 auto; margin-left: 83px;">
    <div
        style="border: 4px solid #e8c5c7; display: block; height: 60px; float: left; width: 2350px;">
        <div
            style="width: 195px; float: left; color: white; background-color: #a41f24; text-align: center; font-size: 37px; line-height: 60px">
            学校名</div>
        <div
            style="width: 601px; float: left; font-size: 37px; padding-left: 25px;">
            <!-- 			団体名（漢字）  -->
            &nbsp;
        </div>
        <div
            style="width: 118px; float: left; color: white; background-color: #a41f24; text-align: center; font-size: 37px; line-height: 60px">
            年</div>
        <div
            style="width: 300px; float: left; font-size: 37px; text-align: center;">
            &nbsp;
            <!-- 			学年 -->
        </div>
        <div
            style="width: 115px; float: left; color: white; background-color: #a41f24; text-align: center; font-size: 37px; line-height: 60px">
            組</div>
        <div
            style="width: 193px; float: left; font-size: 37px; text-align: center;">
            &nbsp;
            <!-- 			クラス -->
        </div>
        <div
            style="width: 118px; float: left; color: white; background-color: #a41f24; text-align: center; font-size: 37px; line-height: 60px">
            番号</div>
        <div
            style="width: 105px; float: left; font-size: 37px; text-align: center;">
            &nbsp;
            <!-- 			1234 -->
        </div>
        <div
            style="width: 117px; float: left; color: white; background-color: #a41f24; text-align: center; font-size: 37px; line-height: 60px">
            氏名</div>
        <div
            style="width: 297px; float: left; font-size: 37px; padding-left: 28px;">
            &nbsp;
            <!-- 			氏名（漢字） -->
        </div>
    </div>
    <div style="clear: both;"></div>
    <div class="cl0" style="">
        <div style="float: left; border-right: 4px solid #f4dadd;">
            <div class="cl1" style="width: 1380px;">
                <div style="color: white;">実施要領</div>
            </div>
            <div class="cl2" style="float: left; height: 270px;">
                <div
                    style="width: 100%; background-color: #f4dadd; text-align: center; font-size: 35px; float: left;">
                    一次試験 <br> <span style="font-size: 25px;">[筆記＋リスニング]</span>
                </div>
                <div style="width: 100%; background-color: #fff; float: left;">
                    <div style="margin: 20px 10px 10px 10px; font-size: 25px;">
                        <div style="float: left; width: 21%;">試験日程:</div>
                        <div style="float: left; width: 60%;">
                            <?php
                            for ($i = 0; $i < count($examDay); $i ++) {
                                if(!empty($examDay[$i][0])){
                                $showDate = explode("-", $examDay[$i][0]);
                                ?>
                                <span style="width: 100%;"><?php echo $showDate[0] . "年" . (int) $showDate[1] . "月" . (int) $showDate[2] . "日" . "（" . $examDay[$i][1] . "）"; ?></span><br/>
                                <?php
                                }
                            }
                            ?>
                        </div>
                    </div>
                    <div
                        style="float: left; border-right: 1px solid #f4dadd; width: 100%; font-size: 25px; overflow: hidden;">
                        <div style="float: left; width: 21%; margin-left: 8px;">受験会場:</div>
                        <div
                            style="float: left; width: 75%; text-align: left; overflow: hidden; word-wrap: break-word">
                                <?php echo $this->escapeHtml($data['ExamPlace']); ?>
                        </div>
                    </div>
                </div>
            </div>
            <div class="cl2"
                 style="float: left; height: 270px; border: none; width: 725px;">
                <div
                    style="width: 100%; background-color: #f4dadd; text-align: center; font-size: 35px; float: left;">
                    二次試験<br> <span style="font-size: 25px;">[面接試験]</span>
                </div>
                <div style="width: 100%; background-color: #fff; float: left;">
                    <p style="margin: 8px 10px 0px 10px; font-size: 25px;">
                        試験日程：（A日程）<?php
                        echo $eikenScheduleDay->getRound2Day1ExamDate() != Null ?
                                ($eikenScheduleDay->getRound2Day1ExamDate()->format('Y') . '年' .
                                (int) $eikenScheduleDay->getRound2Day1ExamDate()->format('m') . '月' .
                                (int) $eikenScheduleDay->getRound2Day1ExamDate()->format('d') . '日') : ''
                        ?>（<?php echo $dayRound2A; ?>）
                    </p>
                    <p style="margin: 0px 0px 0px 135px; font-size: 25px;">
                        （B日程）<?php
                        echo $eikenScheduleDay->getRound2Day2ExamDate() != Null ?
                                ($eikenScheduleDay->getRound2Day2ExamDate()->format('Y') . '年' .
                                (int) $eikenScheduleDay->getRound2Day2ExamDate()->format('m') . '月' .
                                (int) $eikenScheduleDay->getRound2Day2ExamDate()->format('d') . '日') : ''
                        ?>（<?php echo $dayRound2B; ?>）
                    </p>
                    <p style="margin: 0px 0px 0px 10px; font-size: 25px;">
                        受験会場：英検本会場
                    </p>
                    <p style="margin: 0px 5px 0px; font-size: 25px;">※詳細は『二次受験票』にてご案内</p>
                </div>
            </div>
        </div>
        <div
            style="position: relative; float: left; height: 229px; width: 960px;">
            <div>
                <div style="width: 399px; margin-left: -3px; float: left;"
                     class="cl1">
                    検定料 <span style="font-size: 30px; color: #fff">（税込）</span>
                </div>
                <div
                    style="float: left; width: 520px; font-size: 25px; margin-left: 20px; height: auto;">
                        <?php if ($data['HallType'] != 1) { ?>
                        <div style="width: 100%; float: left;">※5級～2級は準会場での受験料金です。</div>
                    <?php } ?>
                    <div style="width: 100%; float: left;">※一次試験免除者も同額です。</div>
                </div>
            </div>
            <div
                style="float: left; font-size: 30px; margin: 0; width: 910px; margin-top: 20px;height:132px;">
                    <?php
                    //$priceOfHall = array_reverse($priceOfHall);
                    if(isset($priceOfHall))
                    {
                        $price1 = array_slice($priceOfHall, 0, 3);
                        $price2 = array_slice($priceOfHall, 3, 3);
                        $price3 = array_slice($priceOfHall, 6, 3);
                    
                    ?>
                    <div style="float: left; width: 25%; height: auto">
                        <?php foreach ($price1 as $key => $price) { ?>
                            <div style="float: left; width: 100%; margin-left: 50px;">
                                <div style="float: left; width: 35%; text-align: center;"><?php echo $price["name"]; ?></div>
                                <div style="float: left; width: 60%;">----円</div>
                            </div>
                        <?php } ?>
                    </div>
                    <div style="float: left; width: 25%; height: auto">
                        <?php
                        foreach ($price2 as $key => $price) {
                            ?>
                            <div style="float: left; width: 100%; margin-left: 50px;">
                                <div style="float: left; width: 35%; text-align: center;"><?php echo $price["name"]; ?></div>
                                <div style="float: left; width: 60%;">----円</div>
                            </div>
                            <?php
                        }
                        ?>
                    </div>
                    <div style="float: left; width: 25%; height: auto">
                        <?php
                        foreach ($price3 as $key => $price) {
                            ?>
                            <div style="float: left; width: 100%; margin-left: 50px;">
                                <div style="float: left; width: 35%; text-align: center;"><?php echo $price["name"]; ?></div>
                                <div style="float: left; width: 60%;">----円</div>
                            </div>
                            <?php
                        }
                    
                    ?>
                </div>
                <?php 
                }
                ?>

            </div>
            <div style="width: 954px; border: 4px solid #a41f24; margin-top: <?php echo ($br == 0) ? $bottomIE9 : $bottom ?>; line-height: 80px; float: left;">
                <div style="float:left;width: 280px; color: white; background-color: #a41f24; text-align: center; font-size: 36px;">
                    お申し込み期限
                </div>
                <div style="width: 670px; float: left; font-size: 36px; background-color: #FEFBC6;">
                    <span style="margin-left: 20px;">
                        <?php echo ($monthDeadLine != '') ? (int) $monthDeadLine : ' '; ?>月<?php echo ($dayDeadLine != '') ? (int) $dayDeadLine : ' '; ?>日（<?php echo ($deadDay != '') ? $deadDay : ' '; ?>） 厳守
                    </span>
                </div>
            </div>
            <div style="clear: both;"></div>
        </div>
        <div style="clear: both;"></div>
    </div>
    <?php if ($data["PaymentType"] == 1 && $data["OrganizationPayment"] == 1) { ?>
        <div style="border: 4px solid #e8c5c7; margin-top: 20px; width: 2350px">
            <div style="color: white;">
                <div
                    style="background-color: #a41f24; color: white; padding-left: 20px; padding-right: 20px; font-size: 37px; line-height: 70px; width: 15%">
                    お申し込み方法</div>
            </div>

            <div style="position: relative; height: 80px; margin-bottom: 10px; margin-top: 10px;">
                <div style="float: left;  margin-left: 20px;margin-top: -5px;">
                    <img src="../../img/tpl-payment-ico-guide.png" />
                </div>
                <div class="cl4" style="width: 2330px; margin-top: 16px;">
                    <span style="margin-left: 10px;">スマートフォン/PCからお申し込みの場合</span>
                </div>
            </div>

            <div style="clear: both;"></div>

            <div style="font-size: 30px; margin: 20px;">
                <p style="height: 50px; margin-bottom: 10px; margin-top: 10px;">
                    <span class="number">1</span> <span style="margin-left: 10px;">スマートフォンもしくはPCより下記のURLにアクセスしてください。
                    </span>
                </p>
                <div class="cl4">
                    <div style="width: 15%; float: left;">
                        <p style="margin: 10px 0 0 25px;">QRコード</p>
                        <div style="height: 245px; width: 245px;" class="rect">
                            <img src="../../img/tpl-payment-qrcode.png"
                                 style="border: none; height: 245px; width: 245px;" />
                        </div>
                    </div>

                    <div style="width: 85%; float: right;">
                        <p style="margin: 10px 0 0 25px;">URL</p>
                        <div class="rect" style="height: 250px;">
                            <span style="margin-left: 20px; position: absolute; top: 82px;"><a
                                    style="text-decoration: none; color: black;"
                                    href="https://jukensha-support.eiken.or.jp">https://jukensha-support.eiken.or.jp</a>
                            </span> <br />
                        </div>
                    </div>
                    <div style="clear: both;"></div>
                </div>
            </div>

            <div style="font-size: 30px; margin: 20px;">
                <p style="height: 80px; margin-bottom: 25px; margin-top: 10px;">
                    <span class="number">2</span> <span style="margin-left: 10px;">画面の案内に従って必要事項を入力の上、送信してください。</span><br />
                    <span style="margin-left: 60px;">受験お申し込みページの「団体ID」「認証キー」欄には以下の番号を入力してください。</span>
                </p>
                <div class="cl4">
                    <div style="width: 25%; float: left;">
                        <p style="margin: 10px 0 0 25px;">団体ID</p>
                        <div style="height: 100px" class="rect">
                            <span style="position: absolute; top: 20px; left: 15px;"><?php //echo $this->escape($pupil->getOrganization()->getOrganizationNo());     ?></span>
                        </div>
                    </div>

                    <div style="width: 20%; float: left;">
                        <p style="margin: 10px 0 0 25px;">認証キー</p>
                        <div class="rect" style="height: 100px;">
                            <span style="position: absolute; top: 20px; left: 15px;"><?php //echo sprintf("%'.08d", ($this->escape($pupil->getSerialId())));     ?></span>
                        </div>
                    </div>
                    <div style="width: 55%; float: left;">
                        <p style="margin: 80px 0 0 25px; font-size: 35px;">
                            ※認証キーはあなた専⽤の番号です。他の⼈の受験案内状に記載された番号は使⽤できません</p>
                    </div>
                    <div style="clear: both;"></div>
                </div>
            </div>
        </div>
    <?php } ?>
<!--    <div class="cl0" style="border-top: none;">
        <div class="cl4">お支払い手続きのご注意</div>
        <div style="font-size: 30px; margin: 20px;">
            <span style="position: relative; font-size: 25px;">
                ●上記以外の店舗では、お支払いいただけません。●本用紙をコンビニエンスストアのレジに提出してもお支払いできません。お支払い期限を過ぎた支払用紙はご利用できません。●コンビニエンスストアでのお支払いは現金のみとなります。●コンビニ端末で入力する情報は本用紙に印刷された番号のみです。住所・氏名などを入力する必要はありません。●お支払い後の返金は一切できません。また、次回以降の検定料への充当もできません。あらかじめご了承ください。
            </span>
        </div>
    </div>-->
    <div style="width: 2354px">
        <div style="margin-top: 30px;" class="cl4">ダブル受験について</div>
        <div style="height: 180px; font-size: 30px;" class="rect">
            <?php echo $this->escapeHtml($data['DoubleEikenMessage']); ?>
        </div>
    </div>

    <div class="cl0-other"
         style="border-top: none; margin-top: 0px; font-size: 25px;">
        <div class="cl4">受験者サポートシステム（申込登録・クレジットカード支払・英ナビ利用登録）へのアクセス方法</div>
        <div style="clear: both;"></div>

        <div style="font-size: 30px; margin: 20px;">
            <p style="height: 50px; margin-bottom: 10px; margin-top: 10px;">
                <span class="number">1</span> <span style="margin-left: 10px;">
                    スマートフォンもしくはPCより下記のURLにアクセスしてください。 </span>
            </p>
            <div class="cl4">
                <div style="width: 15%; float: left;">
                    <p style="margin: 10px 0 0 25px;">QRコード</p>
                    <div style="height: 245px; width: 245px;" class="rect">
                        <img src="../../img/tpl-payment-qrcode.png"
                             style="border: none; height: 245px; width: 245px;" />
                    </div>
                </div>

                <div style="width: 85%; float: right;">
                    <p style="margin: 10px 0 0 25px;">URL</p>
                    <div class="rect" style="height: 250px;">
                        <span style="margin-left: 20px; position: absolute; top: 82px;"><a
                                style="text-decoration: none; color: black;"
                                href="https://jukensha-support.eiken.or.jp">https://jukensha-support.eiken.or.jp</a>
                        </span>
                    </div>
                </div>
                <div style="clear: both;"></div>
            </div>
        </div>

        <div style="font-size: 30px; margin: 20px;">
            <p style="height: 80px; margin-bottom: 25px;">
                <span class="number">2</span> <span style="margin-left: 10px;">画面の案内に従って必要事項を入力の上、送信してください。</span><br />
                <span style="margin-left: 60px;">受験お申し込みページの「団体ID」「認証キー」欄には以下の番号を入力してください。</span>
            </p>
            <div class="cl4">
                <div style="width: 25%; float: left;">
                    <p style="margin: 10px 0 0 25px;">団体ID</p>
                    <div style="height: 100px" class="rect">
                        <span style="position: absolute; top: 20px; left: 15px;"><?php //echo $this->escape($pupil->getOrganization()->getOrganizationNo());     ?></span>
                    </div>
                </div>

                <div style="width: 20%; float: left;">
                    <p style="margin: 10px 0 0 25px;">認証キー</p>
                    <div class="rect" style="height: 100px;">

                        <span style="position: absolute; top: 20px; left: 15px;"><?php //echo sprintf("%'.08d", ($this->escape($pupil->getSerialId())))     ?></span>
                    </div>
                </div>
                <div style="width: 55%; float: left;">
                    <p style="margin: 60px 0 0 25px; font-size: 35px;">
                        ※認証キーはあなた専⽤の番号です。他の⼈の受験案内状に記載された番号は使⽤できません</p>
                </div>
                <div style="clear: both;"></div>
            </div>
        </div>
    </div>
    <div style="width: 2350px">
        <p
            style="font-size: 48px; margin-top: 10px; margin-bottom: 10px; text-align: center; border-bottom: 1px solid #B8B8B8;">
            上記のURLにアクセスした後、「英ナビ！を使⽤する」から英ナビ！にログインして学習できます</p>

        <center style="font-size: 30px; margin-bottom: 10px;">
            【お申し込みに関するお問い合わせ】英検サービスセンター（個人受付）　電話番号：03-3266-8311 受付時間：9:30〜17:00（⼟・⽇・祝⽇を除く）</center>
    </div>
    <?php if ($data['PaymentType'] == 1 && ($data["OrganizationPayment"] == 2 /* || $data["OrganizationPayment"] == 3 */)) { ?>
        <div style="width: 2350px">
            <p style="margin: 20px; font-size: 30px; text-align: center">
                ------------キリトリ—-----------------------------------------キリトリ—----------------------------キリトリ--------------------------------------------キリトリ---------
            </p>
        </div>
        <div style="width: 2354px">
            <div style="margin-top: 30px; font-size: 37px; margin-top: 5px;">
                <strong>申込表</strong>
            </div>
        </div>
        <div style="border: 1px solid; font-size: 30px; width: 2354px">
            <div
                style="height: 90px; float: left; width: 300px; text-align: right; border-right: 1px solid; padding-top: 30px; padding-right: 20px;">
                <strong>年</strong>
            </div>
            <div
                style="height: 90px; float: left; width: 300px; text-align: right; border-right: 1px solid; padding-top: 30px; padding-right: 20px;">
                <strong>組</strong>
            </div>
            <div
                style="height: 90px; float: left; width: 300px; text-align: right; border-right: 1px solid; padding-top: 30px; padding-right: 20px;">
                <strong>番</strong>
            </div>
            <div style="height: 90px; float: right; text-align: right"></div>
            <div style="clear: both;"></div>
            <div style="height: 375px; border-top: 1px solid" align="center">
                <p style="margin-left: 90px; text-align: left">申し込み受験級にチェックしてください</p>
                <div style="margin: 40px;">
                    <ul style="list-style-type: none; margin-bottom: 40px;">
                        <li style="width: 14%; float: left">
                            <p>1級</p>
                            <div style="border: 1px solid; height: 50px; width: 50px;"></div>
                        </li>
                        <li style="width: 14%; float: left">
                            <p>準1級</p>
                            <div style="border: 1px solid; height: 50px; width: 50px;"></div>
                        </li>
                        <li style="width: 14%; float: left">
                            <p>2級</p>
                            <div style="border: 1px solid; height: 50px; width: 50px;"></div>
                        </li>
                        <li style="width: 14%; float: left">
                            <p>準2級</p>
                            <div style="border: 1px solid; height: 50px; width: 50px;"></div>
                        </li>
                        <li style="width: 14%; float: left">
                            <p>3級</p>
                            <div style="border: 1px solid; height: 50px; width: 50px;"></div>
                        </li>
                        <li style="width: 14%; float: left">
                            <p>4級</p>
                            <div style="border: 1px solid; height: 50px; width: 50px;"></div>
                        </li>
                        <li style="width: 14%; float: left">
                            <p>5級</p>
                            <div style="border: 1px solid; height: 50px; width: 50px;"></div>
                        </li>
                        <li style="clear: both;"></li>
                    </ul>
                </div>
            </div>
        </div>
    <?php } ?>
</div>