<?php echo $this->headLink()->appendStylesheet($this->basePath('css/forgot-password.css')); ?>
<?php echo $this->headScript()->appendFile($this->basePath('js/forgot-password/forgot-password.js')); ?>
<?php
$form->setAttribute('action', $this->url('forgot', array('controller' => 'User', 'action' => 'forgot')));
$form->setAttribute('class', 'form-horizontal fix-width-620 ver-center');
$form->setAttribute('id', 'frmForgot');
$form->prepare();
?>
<div class="jiem-error layout-hidden-item fix-width-620 ver-center forgot-error"></div>
<!-- message error for validate server side -->
<?php if ($flagValid) : ?>
    <div id="validServer" class="jiem-error fix-width-620 ver-center forgot-error">
        <div class="alert">
            <ul>
                <?php
                if (!empty($form->getMessages())) {
                    foreach ($form->getMessages() as $key => $row) {
                        $form->get($key)->setAttribute('class', $form->get($key)->getAttribute('class') . ' error');
                        foreach ($row as $value) { ?>
                            <li><a onclick="forcusField(this)" href="#<?php echo $key; ?>"><?php echo nl2br($value); ?></a> </li>
                <?php } } } ?>
            </ul>
        </div>
    </div>
<?php endif; ?>
<!-- message error for validate client side -->
<?php echo $this->form()->openTag($form); ?>
<div class="box">
    <div class="title box-header">
        <strong><?php echo $this->translate('forgot-form-title'); ?></strong>
    </div>
    <div class="box-body">
        <div class="row forgot-option">
            <div class="col-sm-12 forgot-option-title">
                <p>以下のいずれかを選択し、ユーザ登録時に設定したメールアドレスを入力してください。</p>
            </div>
            <!--<div class="col-sm-1"></div>-->
        </div>
        <div class="row forgot-option">
            <div class="col-sm-4"></div>
            <div class="col-sm-8 right-5">
                <?php echo $this->formElement($form->get('radioOption')); ?>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-4 email-title">
                <strong>
                    <?php echo $this->translate('forgot-form-email-title'); ?><span class="required">*</span>
                </strong>
            </div>
            <div class="col-sm-8 right-5">
                <?php echo $this->formElement($form->get('txtEmail')); ?>
            </div>
        </div>
    </div>
    <div class="box-footer">
        <div class="col-sm-12 text-right">
            <button type="button" class="btn btn-large-180 btn-cancel">
                <strong>キャンセル</strong>
            </button>
            <button type="submit" id="submitform" class="btn btn-red btn-large-180">
                <strong>送信する</strong>
            </button>
        </div>
    </div>
</div>
<?php echo $this->form()->closeTag(); ?>
<script type="text/javascript">
    var Msg_Error_Vaild_Email = "<?php echo $this->translate('Msg_Error_Vaild_Email'); ?>";
    var MSG1 = "<?php echo $this->translate('MSG1-forgot-password-mandatory'); ?>";
    $(document).ready(function () {
        $('form:first *:input[type!=hidden]:first').focus();
        $('button.btn-cancel').click(function () {
            window.location.href = '<?php echo $this->url('login') ?>';
        });
    });

    <?php if(!empty($jsMessage)){ ?>
    ERROR_MESSAGE.show('<?php echo $jsMessage; ?>',
        function () {
            window.location.href = '<?php echo $this->url('login') ?>';
        });
    <?php } ?>
</script>
