<?php $this->headLink()->appendStylesheet($this->basePath('css/forgot-password.css')); ?>
<?php $this->headLink()->appendStylesheet($this->basePath('css/reset-password.css')); ?>
<?php $this->headScript()->appendFile($this->basePath('js/forgot-password/reset-password.js')); ?>
<?php
$form->setAttribute('action', $this->url('forgot', array('controller' => 'User', 'action' => 'reset-password')));
$form->setAttribute('class', 'form-horizontal fix-width-620 ver-center');
$form->setAttribute('id', 'frmResetPassword');
$form->prepare();
?>
<div class="jiem-error layout-hidden-item fix-width-620 ver-center forgot-error"></div>
<!-- message error for validate server side -->
<?php if (!$flagValid) : ?>
    <div id="validServer" class="jiem-error fix-width-620 ver-center forgot-error">
        <div class="alert">
        <ul>
        <?php
        if (!empty($form->getMessages())) {
            foreach ($form->getMessages() as $key => $row) {
                $form->get($key)->setAttribute('class', $form->get($key)->getAttribute('class').' error');
                foreach ($row as $value) {
                    ?>
                    <li>
                        <a onclick="forcusField(this)" href="#<?php echo $key; ?>"><?php echo nl2br($value); ?></a>
                    </li>
                    <?php
                }
            }
        }
        ?>
        </ul>
        </div>
    </div>
<?php endif; ?>
<?php if ($isExpired) : ?>
    <?php echo $this->form()->openTag($form); ?>
    <!-- message error for validate client side -->
    <div class="box">
        <div class="title box-header">
            <strong>パスワード変更</strong>
        </div>
        <div class="box-body">
            <div>
                <div class="row">
                    <div class="col-sm-1"></div>
                    <div class="col-sm-4 email-title">
                        <strong>
                            新パスワード<span class="required">*</span>
                        </strong>
                    </div>
                    <div class="col-sm-7 right-5">
                        <?php echo $this->formElement($form->get('txtPassword')); ?>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-1"></div>
                    <div class="col-sm-4 email-title">
                        <strong>
                            新パスワード（確認）<span class="required">*</span>
                        </strong>
                    </div>
                    <div class="col-sm-7 right-5">
                        <?php echo $this->formElement($form->get('txtConfirmPassword')); ?>
                    </div>
                </div>
            </div>
        </div>
        <?php 
            if(isset($token)){
                echo $this->formElement($form->get('txtToken')->setValue($token)); 
            }
        ?>
        <?php 
            if(isset($userItem)){
                echo $this->formElement($form->get('txtUserName')->setValue($userItem->getUserID())); 
                echo $this->formElement($form->get('txtOrganizationNo')->setValue($userItem->getOrganizationNo())); 
            }
        ?>
        <div class="box-footer">
            <div class="col-sm-12 text-right">
                <button type="submit" id="submitform" class="btn btn-red btn-large-180">
                    <strong><?php echo $this->translate('forgot-password-change-password-button'); ?></strong>
                </button>
            </div>
        </div>
    </div>
    <?php echo $this->form()->closeTag(); ?>
<?php endif; ?>
<script type="text/javascript">
    var resetPasswordSuccess = "<?php echo isset($resetPasswordSuccess) ? $resetPasswordSuccess : '' ?>";
    var result = <?php echo empty($result) ? 0 : 1; ?>;
    if(result && resetPasswordSuccess){
        ERROR_MESSAGE.show(resetPasswordSuccess,function(){
            window.location.href = '<?php echo $this->url('login', array('controller' => 'u-a-c', 'action' => 'index')); ?>';
        });
    }
    <?php if(!$isExpired):?>
    CONFIRM_MESSAGE.show('<?php echo isset($jsExpiredMessage) ? $jsExpiredMessage : "Error"; ?>', function () {
        window.location.href = '<?php echo $this->url('forgot', array('controller' => 'user', 'action' => 'forgot')); ?>';
    }, function () {
    }, null, '<?php echo $this->translate('MSG7-forgot-password-mail-ok-button'); ?>', '<?php echo $this->translate('MSG7-forgot-password-mail-cancel-button'); ?>');
    <?php endif; ?>
</script>
