<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'HomePage\Module'                        => __DIR__ . '/Module.php',
    'HomePage\Controller\IndexController' => __DIR__ . '/src/HomePage/Controller/IndexController.php',
);
