<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'GoalSetting\Module'                        => __DIR__ . '/Module.php',
    'GoalSetting\Controller\IndexController' => __DIR__ . '/src/GoalSetting/Controller/IndexController.php',);
