<?php
$paging = $this->paginationHelper($paginator, $page, '/history/iba/empty-name-kana', $numPerPage,$year?'?year='.$year:'');
$this->headLink()->prependStylesheet($this->basePath('css/studentandclass.css'))
?>
<div class="studentmanager">
    <div class="box">
        <div class="box-header">
            <?php echo $this->translate('生徒情報'); ?>
        </div>
        <div class="box-body">
            <table class="table table-bordered table-striped">
                <thead>
                    <tr class="checkbox_list">
                        <th class="year student-number jyear"><?php echo $this->translate('年度'); ?></th>
                        <th class="jschool-year"><?php echo $this->translate('学年'); ?></th>
                        <th class="class_name"><?php echo $this->translate('クラス'); ?></th>
                        <th class="jnumber"><?php echo $this->translate('番号'); ?></th>
                        <th class="jname"><?php echo $this->translate('氏名（漢字）'); ?></th>
                        <th class="jname"><?php echo $this->translate('氏名（カナ）'); ?></th>
                        <th width="110"><?php echo $this->translate('生年月日'); ?></th>
                        <th class="sex"><?php echo $this->translate('性別'); ?></th>
                        <th width="80"><?php echo $this->translate('詳細'); ?></th>
                    </tr>
                </thead>
                <tbody>
                    <?php if (count($listEmptyNameKana)) { ?>
                        <?php foreach ($listEmptyNameKana as $k => $v) : ?>
                            <tr>
                                <td><?php echo $this->escapehtml($v->getYear()); ?></td>
                                <td><?php
                                    if (!empty($v->getOrgSchoolYear())) {
                                        echo $this->escapehtml($v->getOrgSchoolYear()->getDisplayName());
                                    }
                                    ?></td>
                                <td>
                                    <?php
                                    if (!is_null($v->getClass())) {
                                        echo $this->escapehtml($v->getClass()->getClassName());
                                    }
                                    ?>
                                </td>
                                <td class="text-right"><?php echo $this->escapehtml($v->getNumber()); ?></td>
                                <td><?php echo $this->escapehtml($v->getFirstNameKanji() . $v->getLastNameKanji()); ?></td>
                                <td><?php echo $this->escapehtml($v->getFirstNameKana() . $v->getLastNameKana()); ?></td>
                                <td><?php
                                    if ($v->getBirthday()) {
                                        echo $this->escapehtml($v->getBirthday()->format('Y/m/d'));
                                    }
                                    ?></td>
                                <td>
                                    <?php
                                    echo $v->getGender() != -1 ? ($v->getGender() == 1 ? '男' : '女') : '';
                                    ?>
                                </td>
                                <td class="text-center">
                                    <a class="btn btn-view" href="<?php echo $this->url('pupil-mnt/default', array('controller' => 'pupil', 'action' => 'edit', 'id' => $v->getId())); ?>">
                                            <?php echo $this->translate('編集'); ?>
                                    </a></td>
                            </tr>

                            <?php endforeach;?>
                    <?php } else { ?><tr><td colspan="10"><p><?php echo $this->translate("MSGnoresult"); ?></p><?php }; ?></td></tr>
                </tbody>
            </table>
            <?php if (count($paginator) > $numPerPage) { ?>
                <div class="box_padding text-center pagination_student_color">
                    <nav>
                        <ul class="pagination">
                            <?php echo $paging; ?>
                        </ul>
                    </nav>
                </div>
            <?php } ?>
        </div>
    </div>
</div>
</div>
<?php $this->headScript()->prependFile($this->basePath('js/pupil/pupil.js')) ?>
<?php $this->headScript()->prependFile($this->basePath('js/recommend.invitation.js')) ?>

<script type="text/javascript">
    $(document).ready(function () {
        $('.breadcrumb li').remove();
    });

</script>

