<?php $this->headLink()->appendStylesheet ( $this->basePath ( 'css/history/iba-mapping-result.css' ) );
$this->headLink()->appendStylesheet($this->basePath ( 'css/history/hackIE9.css' ), 'screen', 'IE 9');
$paging = $this->paginationHelper($paginator , $page, '/history/iba/mapping-error/year/'.$year. '/jisshiId/' . $jisshiId. '/examType/' . $examType, $numPerPage);
?>
<?php $tabIndex = 1;
    ?>
 <script>
 var listPupil = <?php echo $jsonListPupil;?>;
 </script>
<div class="confirm-result">
	<!-- Nav tabs -->
	<ul class="nav nav-tabs nav-confirm-result nav-custom-grey" role="tablist">
		<li role="presentation" >
		  <a href="<?php echo '/history/iba/mapping-error/year/'.$year. '/jisshiId/' . $jisshiId. '/examType/' . $examType ;?>" >
			 <?php echo $this->translate('生徒名簿突合せ結果（IBA）：未突合') ;?>
		  </a>
		</li>
		<li role="presentation" class="active"><a href="#mapping-success" aria-controls="mapping-success"
			role="tab" data-toggle="tab"><?php echo $this->translate('生徒名簿突合せ結果（IBA）：突合済') ;?></a>
		</li>
	</ul>

	<!-- Tab panes -->
	<div class="tab-content">

		<!-- mapping-success -->
		<div role="tabpanel" class="tab-pane active" id="mapping-success">
            <!-- 2 div data-->
			<div class="row">
				<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 col-left">

					<span class="title-result-exam"><?php echo $this->translate('取込結果') ;?></span>
					<div class="data-result-exam">
						<table id="table-left-success" class="table-result-exam table table-bordered tbl-striped">
							<thead>
								<tr>
								    <th rowspan="2" class="jname"><?php echo $this->translate('氏名(カナ)') ;?></th>
									<th rowspan="2" class="jbirth-day"><?php echo $this->translate('生年月日') ;?></th>
									<th rowspan="2" class="jschool-year"><?php echo $this->translate('学年') ;?></th>
									<th rowspan="2" class="jkumi"><?php echo $this->translate('クラス') ;?></th>
									<th rowspan="2" class="jnumber"><?php echo $this->translate('番号') ;?></th>
									<th rowspan="2" class="jtestset"><?php echo $this->translate('テスト種別') ;?></th>
									<th rowspan="2" class="jtestset-no"><?php echo $this->translate('テストセット番号') ;?></th>
									<th rowspan="2" class="jscore-total"><?php echo $this->translate('総合') ;?></th>
									<th rowspan="2" class="jscore-read"><?php echo $this->translate('リーディング') ;?></th>
									<th rowspan="2" class="jscore-listen"><?php echo $this->translate('リスニング') ;?></th>
									
									<th colspan="3" class="jeiken"><?php echo $this->translate('英検級レベル判定') ;?>
								</tr>
								<tr>
								    <th class="jeiken-kyulv-total"><?php echo $this->translate('総合') ;?></th>
									<th class="jeiken-kyulv-read"><?php echo $this->translate('リーディング') ;?></th>
									<th class="jeiken-kyulv-listen"><?php echo $this->translate('リスニング') ;?></th>
								</tr>
							</thead>
							<!-- 20 row -->
							<tbody>
							     <tr><td class="td-first"></td></tr>
							    <?php if(!empty($mappingData["mappingSuccess"])):?>
							         <?php foreach ($mappingData["mappingSuccess"] as $key=>$items): ?>
							             <?php foreach ($items as $keyChild=>$item): ?>
							              <tr id="success-result-exam-<?php echo $item['id']; ?>">
    							             <!-- Name Kanji -->
    						                 <td class="jname">
    						                  <?php if(!empty($keepSession[$item['id']])): ?>
                                             <input id="input-success-result-exam-<?php echo $item['id']; ?>"
    					                       data-follow="success-pupil-manager-<?php echo $item['id']; ?>"
    					                       data-focus="success-result-exam-<?php echo $item['id']; ?>"
                                               data-value="<?php echo $this->escapehtml($keepSession[$item['id']]['nameKana']); ?>"
                                               value="<?php echo $this->escapehtml($keepSession[$item['id']]['nameKana']); ?>"
                                               data-id="<?php echo !empty($item['id']) ? $item['id'] : '&nbsp';  ?>"
                                               class="form-control mapping-error-autocomplete" type="text" tabindex="<?php echo $tabIndex++; ?>">
                                             <?php else :?>
                                               <input id="input-success-result-exam-<?php echo  $item['id']; ?>"
    						                      data-follow="success-pupil-manager-<?php echo $item['id']; ?>"
    						                      data-focus="success-result-exam-<?php echo $item['id']; ?>"
    						                      data-value="<?php 
    						                          if(!empty($item['tempNameKana'])){
    						                              echo $this->escapehtml($item['tempNameKana']);
    						                          }elseif (!empty($item['preTempNameKana'])) {
    						                              echo $this->escapehtml($item['preTempNameKana']);
    						                          }
    						                      ?>"
    						                      value="<?php 
        						                      if(!empty($item['tempNameKana'])){
        						                          echo $this->escapehtml($item['tempNameKana']);
    						                           }elseif (!empty($item['preTempNameKana'])) {
        						                          echo $this->escapehtml($item['preTempNameKana']);
        						                      } 
    						                      
    						                      ?>"
    						                      data-id="<?php echo !empty($item['id']) ? $item['id'] : '&nbsp';  ?>"
    						                      class="form-control mapping-error-autocomplete" type="text" tabindex="<?php echo $tabIndex++; ?>">
                                             <?php endif; ?>
    						                 </td>
    						                  <!-- Name Kantana -->
    						                  <!-- Birthday -->
    						                  <td class="jbirth-day"><?php echo (!empty($item['birthday'])) ? $item['birthday']->format('Y/n/j'):'&nbsp'; ?></td>
                                                <td class="jschool-year "><?php echo !empty($item['schoolYear']) ? $this->escapehtml($item['schoolYear']) : '&nbsp';  ?></td>
                                                <td class="jkumi"><?php echo !empty($item['classCode']) ? $this->escapehtml($item['classCode']) : '&nbsp'; ; ?></td>
                                                <td class="jnumber"><?php echo !empty($item['attendanceNo']) ? $this->escapehtml($item['attendanceNo']) : '&nbsp'; ; ?></td>
                                                <td class="jtestset"><?php echo !empty($item['testType']) ? $this->escapehtml($item['testType']) : '&nbsp';  ?></td>
                                                <td class="jtestset-no text-right"><?php echo !empty($item['testSetNo']) ? $this->escapehtml($item['testSetNo']) : '&nbsp';  ?></td>
                                                <td class="jscore-total text-right"><?php echo !empty($item['total']) ? $this->escapehtml($item['total']) : '&nbsp';  ?></td>
                                                <td class="jscore-read text-right"><?php echo !empty($item['read']) ? $this->escapehtml($item['read']) : '&nbsp';  ?></td>
                                                <td class="jscore-listen text-right"><?php echo !empty($item['listen']) ? $this->escapehtml($item['listen']) : '&nbsp';  ?></td>
                                               <td class="jeiken-kyulv-total text-right">
                                                <?php 
                                                    if($item['eikenLevelTotal']!==NULL){
                                                        if(!empty($iBAEikenLevelTotal[$item['eikenLevelTotal']])){
                                                            echo $this->escapehtml($iBAEikenLevelTotal[$item['eikenLevelTotal']]);
                                                        }else{
                                                            echo $this->escapehtml($item['eikenLevelTotal']);
                                                        } 
                                                    }
                                                ?>
                                                </td>
                                                <td class="jeiken-kyulv-read text-right">
                                                <?php 
                                                    if($item['ekenLevelRead']!==NULL){
                                                        if(!empty($iBAEikenLevelReadListen[$item['ekenLevelRead']])){
                                                            echo $this->escapehtml($iBAEikenLevelReadListen[$item['ekenLevelRead']]);
                                                        } else{
                                                            echo $this->escapehtml($item['ekenLevelRead']);
                                                        }
                                                    }
                                                ?>
                                                </td>
                                                <td class="jeiken-kyulv-listen text-right">
                                                <?php 
                                                if($item['eikenLevelListening']!==NULL){
                                                    if(!empty($iBAEikenLevelReadListen[$item['eikenLevelListening']])){
                                                        echo $this->escapehtml($iBAEikenLevelReadListen[$item['eikenLevelListening']]);
                                                    } else {
                                                        echo $this->escapehtml($item['eikenLevelListening']);
                                                    }
                                                }
                                                ?>
                                                </td>
    						             </tr>
							             <?php endforeach;?>
							         <?php endforeach;?>
							       <?php endif;?>
							       


							</tbody>
							<!--end 20 row -->

						</table>
					</div>

				</div>
				<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 col-right">
					<span class="title-pupil-manager"><?php echo $this->translate('生徒名簿') ;?></span>
					<div class="data-pupil-manager">
						<table id="table-right-success"
							class="table-pupil-manager table table-bordered tbl-striped">
							<thead>
								<tr>
								    <!-- NameKanji -->
									<th class="jname"><?php echo $this->translate('氏名(漢字)') ;?></th>
									<!-- NameKana -->
									<th class="jnameKana"><?php echo $this->translate('氏名(カナ)') ;?></th>
									<!-- Birthday -->
									<th class="jbirth-day"><?php echo $this->translate('生年月日') ;?></th>
                                    <!-- Pupil ID -->
									<!-- <th class="jpupil-id"><?php echo $this->translate('生徒ID') ;?></th> -->
                                    <!-- SchoolYear -->
									<th class="jschool-year"><?php echo $this->translate('学年') ;?></th>
									<!-- Class-Kumi -->
									<th class="jkumi"><?php echo $this->translate('クラス') ;?></th>
									<!-- Number ID-->
									<th class="jnumber"><?php echo $this->translate('番号') ;?></th>

								</tr>
							</thead>
							<!--20 row -->
							<tbody>
							     <tr><td class="td-first"></td></tr>
							     
							     <?php if(!empty($mappingData["mappingSuccess"])):?>
							         <?php foreach($mappingData["mappingSuccess"] as $key=>$items):?>
							             <?php foreach ($items as $keyChild=>$item):?>
							                 <?php if(!empty($keepSession[$item['id']])):?>
							                     <tr id="success-pupil-manager-<?php echo $item['id']; ?>">
                                        			<td class="jname"><?php echo (!empty($keepSession[$item['id']]['nameKanji'])) ? $this->escapehtml($keepSession[$item['id']]['nameKanji']):'&nbsp'; ?></td>
                                        			<!-- NameKana -->
                                        			<td class="jnameKana"><?php echo (!empty($keepSession[$item['id']]['nameKana'])) ? $this->escapehtml($keepSession[$item['id']]['nameKana']):'&nbsp'; ?></td>
                                        			<!-- Birthday -->
                                        			<td class="jbirth-day"><?php echo (!empty($keepSession[$item['id']]['birthday']))?$keepSession[$item['id']]['birthday']:'&nbsp'; ?></td>
                                        			<!-- SchoolYear -->
                                        			<td class="jschool-year"><?php echo ($keepSession[$item['id']]['orgSchoolYearName']!==NULL) ? $this->escapehtml($keepSession[$item['id']]['orgSchoolYearName']):'&nbsp'; ?></td>
                                        			<!-- Class-Kumi -->
                                        			<td  class="jkumi"><?php echo (!empty($keepSession[$item['id']]['className'])) ? $this->escapehtml($keepSession[$item['id']]['className']):'&nbsp'; ?></td>
                                        			<!-- Number -->
                                        			<td class="jnumber"><?php echo (!empty($keepSession[$item['id']]['number'])) ? $this->escapehtml($keepSession[$item['id']]['number']):'&nbsp'; ?></td>
                                        		</tr>
							                  <?php else :?>
							                  <tr id="success-pupil-manager-<?php echo $item['id']; ?>">
            									<td class="jname">
            									<?php
                                                                                    echo (!empty($mappingData['pupilSuccess'][$item['pupilId']]['firstNameKanji'])) ? $this->escapehtml($mappingData['pupilSuccess'][$item['pupilId']]['firstNameKanji']):'&nbsp';
                                                                                    echo (!empty($mappingData['pupilSuccess'][$item['pupilId']]['lastNameKanji'])) ? $this->escapehtml($mappingData['pupilSuccess'][$item['pupilId']]['lastNameKanji']):'&nbsp'; 

							                     ?>
            									</td>
            									<!-- NameKana -->
            									<td class="jnameKana">
            									   <?php
                                                                                    echo (!empty($mappingData['pupilSuccess'][$item['pupilId']]['firstNameKana'])) ? $this->escapehtml($mappingData['pupilSuccess'][$item['pupilId']]['firstNameKana']):'&nbsp';
                                                                                    echo (!empty($mappingData['pupilSuccess'][$item['pupilId']]['lastNameKana'])) ? $this->escapehtml($mappingData['pupilSuccess'][$item['pupilId']]['lastNameKana']):'&nbsp';

							                         ?>
            									</td>
            									<!-- Birthday -->
            									<td class="jbirth-day">
            									   <?php echo (!empty($mappingData['pupilSuccess'][$item['pupilId']]['birthday'])) ? $mappingData['pupilSuccess'][$item['pupilId']]['birthday']->format('Y/n/j'):'&nbsp'; ?>
            									</td>
            									<!-- SchoolYear -->
            									<td class="jschool-year"><?php echo (!empty($mappingData['pupilSuccess'][$item['pupilId']]['orgSchoolYearName'])) ? $this->escapehtml($mappingData['pupilSuccess'][$item['pupilId']]['orgSchoolYearName']):'&nbsp'; ?></td>
            									<!-- Class-Kumi -->
            									<td  class="jkumi"><?php echo (!empty($mappingData['pupilSuccess'][$item['pupilId']]['className'])) ? $this->escapehtml($mappingData['pupilSuccess'][$item['pupilId']]['className']):'&nbsp'; ?></td>
            									<!-- Number -->
            									<td class="jnumber"><?php echo (!empty($mappingData['pupilSuccess'][$item['pupilId']]['number'])) ? $this->escapehtml($mappingData['pupilSuccess'][$item['pupilId']]['number']):'&nbsp'; ?></td>
        
        								    </tr>
							                 <?php endif;?>
							             <?php endforeach;?>
							         <?php endforeach;?>
							     <?php endif;?>
							</tbody>
								<!--end 20 row -->


						</table>
					</div>
				</div>
			</div>
			<!-- 2 div data-->
			<!-- Paging -->
            <?php if (count($paginator) > $numPerPage ) : ?>
    			<div class="text-center paging">
    				<nav>
    					<ul class="pagination">
                            <?php  echo $paging; ?>
						</ul>
    				</nav>
    			</div>
			<?php endif;?>
			<!--End Paging -->

		</div>
		<!-- End mapping-success -->
	</div>
	<!-- Group Button -->
	<div class="box-footer">

		<div style="text-align: right;">
			<button type="button" id="btnCancel" class="btn btn-large-180"
				onclick="IBA_MAPPING_RESULT.mappingCancel()" tabindex="<?php echo $tabIndex++;?>"><?php echo $this->translate('キャンセル') ;?> </button>
			<button type="button" id="btnSubmitToMapping"
				class="btn btn-large-180 btn-red" onclick="IBA_MAPPING_RESULT.mappingSave()" tabindex="<?php echo $tabIndex++;?>">
				<i class="fa-download-w"></i><?php echo $this->translate('保存') ;?></button>
		</div>
	</div>
	<!--End Group Button -->
</div>

<?php
    $this->headScript()->appendFile($this->basePath('js/jquery-ui.js'));
    $this->inlineScript()->appendFile($this->basePath('js/history/iba-mapping-result.js'));
    echo $this->inlineScript();
?>
<script type="text/javascript">
$("document").ready(function(){
	IBA_MAPPING_RESULT.init();
});
</script>