<?php $this->headLink()->prependStylesheet($this->basePath('css/home-page.css')) ?>
<!-- Scripts -->
<?php
$this->headScript()->prependFile($this->basePath('js/highcharts.js'));
$blank = '-';
?>
<script>
    var dataGraphJ = <?php echo $dataGraphJ; ?>;
    var dataJsonB = <?php echo $dataJsonB; ?>;
    var maxRate = <?php echo $arrayMax['maxRate']; ?>;
</script>
<div class="top-page-detail detailb2">
    <div class="box">
        <div class="box-header">
            <span><b>英検取得状況</b></span>
        </div>
        <div class="box-body">
            <div class="description">
                <p>
                    試験結果情報には受験生による入力ミスなども含まれるため、以下の統計情報には不正確なデータも含まれることがあります。<br>
                    より正確な統計情報を算出するためには各試験結果データと名簿データの間の突合を行ってください。
                </p>
            </div>
            <div class="box-tools pull-left">
                <table class = "table-b">
                    <tr>
                        <td><label> 年度 &nbsp;&nbsp;</label></td>
                        <td>
                            <label class="checkbox-inline">
                                <input type="radio" class="detail-b-type-check" name="yearGraph" id="_crYear1" tabindex="1"><?php echo $year - 1; ?>
                            </label>
                            <label class="checkbox-inline">
                                <input type="radio" class="detail-b-type-check" name="yearGraph" id="_crYear2" tabindex="2" checked="checked"><?php echo $year; ?>
                            </label>
                        </td>
                    </tr>
                </table>
            </div>
            <div class="row">
            </div>
            <div class="row">
                <div id="detailb-graph" class="tab-content">

                    <div id="chartB3" style="height: 165px; margin: 0 auto"></div>
                    <div id="menu1" class="tab-pane fade in active">
                        <div class="detailb-3">
                            <table class="table1 table-bordered tb-d-3"
                                   id="_dataAll">
                                <thead>
                                    <tr>
                                        <th><?php echo $this->translate('年度'); ?></th>
                                        <th><?php echo $this->translate('都道府県'); ?></th>
                                        <th><?php echo $this->translate('1級'); ?></th>
                                        <th><?php echo $this->translate('準1級'); ?></th>
                                        <th><?php echo $this->translate('2級'); ?></th>
                                        <th><?php echo $this->translate('準2級'); ?></th>
                                        <th><?php echo $this->translate('3級'); ?></th>
                                        <th><?php echo $this->translate('4級'); ?></th>
                                        <th><?php echo $this->translate('5級'); ?></th>
                                    </tr>
                                </thead>

                                <?php
                                foreach ($dataGraph as $key => $item) {

                                    $flag = 0;
                                    ?>
                                    <tbody <?php echo empty($dataGraph['Y2'][1]['checkEmptyChart']) ? 'style="display: none"' :''; ?> class="row<?php echo $key; ?>" id="_crTable<?php echo $key; ?>" <?php if ($key != 'Y2') echo 'style="display: none"'; ?>>
                                        <tr >
                                            <th rowspan="3" class="rspYcr"><?php echo $item[7]['year']; ?></th>
                                            <td class="text-left-10"><span><i class="chart-legend legend-Y0">• </i>本校</span></td>
                                            <?php
                                            for ($i = 1; $i < 8; $i++) {
                                                echo '<td>';
                                                echo $item[$i]['orgRate'] . '%</td>';
                                                if (!empty($item[$i]['orgRate'])) {
                                                    $flag = 1;
                                                }
                                            }
                                            ?>
                                        </tr>
                                        <tr class="city">
                                            <td class="text-left-10"><span><i class="chart-legend legend-Y1">• </i><?php echo $cityName; ?></span></td>
                                            <?php
                                            for ($i = 1; $i < 8; $i++) {
                                                echo '<td>' . $item[$i]['cityRate'] . '%</td>';
                                                if (!empty($item[$i]['cityRate'])) {
                                                    $flag = 1;
                                                }
                                            }
                                            ?>
                                        </tr>
                                        <tr class="nation">
                                            <td class="text-left-10"><span><i class="chart-legend legend-Y2">• </i>全国</span></td>
                                            <?php
                                            for ($i = 1; $i < 8; $i++) {
                                                echo '<td>' . $item[$i]['nationRate'] . '%</td>';
                                                if (!empty($item[$i]['nationRate'])) {
                                                    $flag = 1;
                                                }
                                            }
                                            ?>
                                        </tr>
                                    <input type="hidden" data-year="<?php echo $item[7]['year']; ?>" data-class="row<?php echo $key; ?>" data-id="_crTable<?php echo $key; ?>" id="flg_crYear<?php echo str_replace("Y", '', $key); ?>" value="<?php echo $flag; ?>" >
                                    </tbody>
                                <?php } ?>
                            </table>
                        </div>
                    </div>
                </div>
                <script type="text/javascript">//Control for Hightchart and Table

                </script>
            </div>
        </div>
    </div>
    <div class="box">
        <form method="POST" id="detailb2">
            <div class="box-header">
                <span><b>英検取得状況（学年・クラス別）</b></span>
            </div>
            <div class="box-body">
                <div class="row">
                    <div class="col-xs-1 width48">
                        <label><b><?php echo $this->translate('年度'); ?></b></label>
                    </div>
                    <div class="col-xs-1 styled-select width140">
                        <select id="year" name="year" class="form-control width100" tabindex="4">
<?php foreach ($listYear as $year) { ?>
                                <option value="<?php echo $year ?>"<?php echo $search['year'] == $year ? 'selected' : ''; ?>><?php echo $year ?></option>
<?php } ?>
                        </select>
                    </div>
                    <div class="col-xs-1 width130">
                        <label><b><?php echo $this->translate('表示オプション'); ?></b></label>
                    </div>
                    <div class="col-xs-2 width200">
                        <div class="col-xs-6"><input type="radio" <?php echo $search['type'] == 'Deem' ? 'checked="checked"' : ''; ?> value="Deem" id="typeDeem" name="type" tabindex="5"> みなし</div>
                        <div class="col-xs-6"><input type="radio" <?php echo $search['type'] == 'Actual' ? 'checked="checked"' : ''; ?> value="Actual" id="typeActual" name="type" tabindex="6"> 実数 
                            <span tabindex="0" class="icon-description glyphicon glyphicon-question-sign"
                                  data-toggle="popover" data-trigger="hover"
                                  data-content="「みなし」を選択すると、各受験者は実際の合格級以下の級をすでに合格しているものとみなして取得率などの計算を行い表示します。"></span></div>
                    </div>
                    <div class="text right">
                        <a class="btn btn-small-180" id="btnSearch" tabindex="7"><i class="fa-search"></i>検索</a>
                    </div>
                </div>

                <div class="resultacg-table-scroll">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th rowspan="2" colspan="2">学年</th>
                                <th rowspan="2">クラス</th>
                                <th rowspan="2">生徒数</th>
                                <th colspan="2">目標</th>
                                <th rowspan="2">取得率</th>
                            </tr>
                            <tr>
                                <th width="80">目標級</th>
                                <th width="80">取得率</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php
                            $i = 8;
                            if ($listSchoolYear) {
                                if (!empty($search['orgSchoolYearId'])) {
                                    $dataSchoolYear = array($search['orgSchoolYearId'] => isset($listSchoolYear[$search['orgSchoolYearId']]) ? $listSchoolYear[$search['orgSchoolYearId']] : '');
                                } else {
                                    $dataSchoolYear = $listSchoolYear;
                                }
                                //$dataSchoolYear = $listSchoolYear;
                                foreach ($dataSchoolYear as $schoolYearId => $orgSchoolName) {
                                    $orgSchoolName = $this->escapeHtml($orgSchoolName);
                                    //$orgSchoolName = isset($listSchoolYear[$schoolYearId]) ? trim($listSchoolYear[$schoolYearId]) : $blank;
                                    $eikenLevelName = isset($resultGoal[$schoolYearId]) ? $resultGoal[$schoolYearId]['levelName'] : $blank;
                                    $eikenLevelId = isset($resultGoal[$schoolYearId]) ? $resultGoal[$schoolYearId]['eikenLevelId'] : $blank;
                                    $targetPass = isset($resultGoal[$schoolYearId]) ? intval($resultGoal[$schoolYearId]['targetPass']) : $blank;

                                    $numberOfPeople = isset($resultSchoolYear[$schoolYearId]) ? $resultSchoolYear[$schoolYearId]['numberOfPeople'] : $blank;

                                    $peoplePassLevel1 = isset($resultSchoolYear[$schoolYearId]) ? $resultSchoolYear[$schoolYearId]['peoplePassLevel1'] : $blank;
                                    $peoplePassLevelPre1 = isset($resultSchoolYear[$schoolYearId]) ? $resultSchoolYear[$schoolYearId]['peoplePassLevelPre1'] : $blank;
                                    $peoplePassLevel2 = isset($resultSchoolYear[$schoolYearId]) ? $resultSchoolYear[$schoolYearId]['peoplePassLevel2'] : $blank;
                                    $peoplePassLevelPre2 = isset($resultSchoolYear[$schoolYearId]) ? $resultSchoolYear[$schoolYearId]['peoplePassLevelPre2'] : $blank;
                                    $peoplePassLevel3 = isset($resultSchoolYear[$schoolYearId]) ? $resultSchoolYear[$schoolYearId]['peoplePassLevel3'] : $blank;
                                    $peoplePassLevel4 = isset($resultSchoolYear[$schoolYearId]) ? $resultSchoolYear[$schoolYearId]['peoplePassLevel4'] : $blank;
                                    $peoplePassLevel5 = isset($resultSchoolYear[$schoolYearId]) ? $resultSchoolYear[$schoolYearId]['peoplePassLevel5'] : $blank;

                                    $precentPassLevel1 = isset($resultSchoolYear[$schoolYearId]) ? $resultSchoolYear[$schoolYearId]['precentPassLevel1'] : $blank;
                                    $precentPassLevelPre1 = isset($resultSchoolYear[$schoolYearId]) ? $resultSchoolYear[$schoolYearId]['precentPassLevelPre1'] : $blank;
                                    $precentPassLevel2 = isset($resultSchoolYear[$schoolYearId]) ? $resultSchoolYear[$schoolYearId]['precentPassLevel2'] : $blank;
                                    $precentPassLevelPre2 = isset($resultSchoolYear[$schoolYearId]) ? $resultSchoolYear[$schoolYearId]['precentPassLevelPre2'] : $blank;
                                    $precentPassLevel3 = isset($resultSchoolYear[$schoolYearId]) ? $resultSchoolYear[$schoolYearId]['precentPassLevel3'] : $blank;
                                    $precentPassLevel4 = isset($resultSchoolYear[$schoolYearId]) ? $resultSchoolYear[$schoolYearId]['precentPassLevel4'] : $blank;
                                    $precentPassLevel5 = isset($resultSchoolYear[$schoolYearId]) ? $resultSchoolYear[$schoolYearId]['precentPassLevel5'] : $blank;

                                    switch ($eikenLevelId) {
                                        case 1:
                                            $targetPassFact = $precentPassLevel1;
                                            break;
                                        case 2:
                                            $targetPassFact = $precentPassLevelPre1;
                                            break;
                                        case 3:
                                            $targetPassFact = $precentPassLevel2;
                                            break;
                                        case 4:
                                            $targetPassFact = $precentPassLevelPre2;
                                            break;
                                        case 5:
                                            $targetPassFact = $precentPassLevel3;
                                            break;
                                        case 6:
                                            $targetPassFact = $precentPassLevel4;
                                            break;
                                        case 7:
                                            $targetPassFact = $precentPassLevel5;
                                            break;
                                        case $blank:
                                            $targetPassFact = $blank;
                                            break;
                                        default:
                                            $targetPassFact = 0;
                                            break;
                                    }
                                    ?>
                                    <tr>
                                        <td class="collapse-icon text-left">
                                            <input type="hidden" id="orgschoolyear_<?php echo $schoolYearId; ?>" value="<?php echo $orgSchoolName; ?>"/>
        <?php if (!empty($resultClass[$schoolYearId]) || !empty($allClassOfOrg[$schoolYearId])) { ?>
                                            <a style="border: 0 !important;"href="javascript:void(0)" class="toggle" data-id="<?php echo 'hidden-' . $schoolYearId; ?>" tabindex="<?php echo $i; ?>">
                                                    <span class="search-chevron-right"></span>
                                                </a>
        <?php } else { ?>
                                                <a style="border: 0 !important;" href="javascript:void(0)" tabindex="<?php echo $i; ?>"> <span class="search-chevron-right"></span></a>
        <?php } ?>
                                        </td>
                                        <td style="border-left: 0; padding-left: 0  !important;" class="text-left" onclick="ACTUAL_GOAL_LEVEL.putDataToExamHistoryList(<?php echo $schoolYearId; ?>, 0)">
                                            <input type="hidden" id="orgschoolyear_<?php echo $schoolYearId; ?>" value="<?php echo $orgSchoolName; ?>"/>
        <?php echo $orgSchoolName ?>
                                        </td>
                                        <td class="text-left"><?php echo $blank; ?></td>
                                        <td onclick="ACTUAL_GOAL_LEVEL.putDataToExamHistoryList(<?php echo $schoolYearId; ?>, 0)"><?php echo $numberOfPeople !== $blank ? $numberOfPeople . '人' : $blank; ?></td>
                                        <td onclick="ACTUAL_GOAL_LEVEL.putDataToExamHistoryList(<?php echo $schoolYearId; ?>, 0)"><?php echo!empty($eikenLevelName) ? $eikenLevelName : $blank; ?></td>
                                        <td onclick="ACTUAL_GOAL_LEVEL.putDataToExamHistoryList(<?php echo $schoolYearId; ?>, 0)" class="text-center"><?php echo $targetPass !== '-' ? $targetPass . '%' : $targetPass; ?></td>
                                        <td onclick="ACTUAL_GOAL_LEVEL.putDataToExamHistoryList(<?php echo $schoolYearId; ?>, 0)" class="text-center"><?php echo $targetPassFact !== '-' ? $targetPassFact . '%' : '-'; ?></td>
                                    </tr>
                                    <?php
                                    if (!empty($allClassOfOrg[$schoolYearId])) {
                                        foreach ($allClassOfOrg[$schoolYearId] as $classId => $cla) {
                                            $valueClass = (isset($resultClass[$schoolYearId][$classId])) ? $resultClass[$schoolYearId][$classId] : array(
                                                'precentPassLevel1' => $blank,
                                                'peoplePassLevel1' => $blank,
                                                'precentPassLevelPre1' => $blank,
                                                'peoplePassLevelPre1' => $blank,
                                                'precentPassLevel2' => $blank,
                                                'peoplePassLevel2' => $blank,
                                                'precentPassLevelPre2' => $blank,
                                                'peoplePassLevelPre2' => $blank,
                                                'precentPassLevel3' => $blank,
                                                'peoplePassLevel3' => $blank,
                                                'precentPassLevel4' => $blank,
                                                'peoplePassLevel4' => $blank,
                                                'precentPassLevel5' => $blank,
                                                'peoplePassLevel5' => $blank,
                                                'numberOfPeople' => $cla['numberOfStudent'],
                                            );
                                            $className = $cla['className'];
                                            $className = $this->escapeHtml($className);
                                            switch ($eikenLevelId) {
                                                case 1:
                                                    $targetPassFactClass = $valueClass['precentPassLevel1'];
                                                    break;
                                                case 2:
                                                    $targetPassFactClass = $valueClass['precentPassLevelPre1'];
                                                    break;
                                                case 3:
                                                    $targetPassFactClass = $valueClass['precentPassLevel2'];
                                                    break;
                                                case 4:
                                                    $targetPassFactClass = $valueClass['precentPassLevelPre2'];
                                                    break;
                                                case 5:
                                                    $targetPassFactClass = $valueClass['precentPassLevel3'];
                                                    break;
                                                case 6:
                                                    $targetPassFactClass = $valueClass['precentPassLevel4'];
                                                    break;
                                                case 7:
                                                    $targetPassFactClass = $valueClass['precentPassLevel5'];
                                                    break;
                                                case $blank:
                                                    $targetPassFactClass = $blank;
                                                    break;
                                                default:
                                                    $targetPassFactClass = 0;
                                                    break;
                                            }
                                            ?>
                                    <tr onclick="ACTUAL_GOAL_LEVEL.putDataToExamHistoryList(<?php echo $schoolYearId; ?>, <?php echo $classId; ?>)" class="<?php echo 'hidden-' . $schoolYearId; ?>" style="display: none;">
                                                <td class="bgwhite collapse-icon" style="width: 20px;">
                                                    <input type="hidden" id="class_<?php echo $classId; ?>" value="<?php echo $className; ?>"/>
                                                </td>
                                                <td class="bgwhite text-left" style="border-left: 0; padding-left: 0 !important;"><input type="hidden" id="class_<?php echo $classId; ?>" value="<?php echo $className; ?>"/></td>
                                                <td class="bgwhite text-left"><?php echo $className; ?></td>
                                                <td class="bgwhite"><?php echo $valueClass['numberOfPeople']; ?>人</td>
                                                <td class="bgwhite"><?php echo $eikenLevelName; ?></td>
                                                <td class="bgwhite text-center"><?php echo $targetPass !== '-' ? ($targetPass . '%') : $targetPass; ?></td>
                                                <td class="bgwhite text-center"><?php echo $targetPassFactClass !== '-' ? $targetPassFactClass . '%' : $targetPassFactClass; ?></td>
                                            </tr>
                                            <?php
                                        }
                                    }
                                }
                            } else {
                                ?>
                                <tr><td class="nodata" colspan="21"><?php echo $this->translate('MSG17_No_Result_Found'); ?></td></tr>          
    <?php
}
?>
                        </tbody>
                    </table>
                </div>
            </div>   
        </form>
    </div>
    <form id="searchExamHistoryList" method="POST" action="/history/eiken/exam-history-list">
        <input type="hidden" name="year" value="<?php echo $search['year'] ?>"/>
        <input type="hidden" name="orgSchoolYear" value=""/>
        <input type="hidden" name="classj" value=""/>
        <input type="hidden" name="searchVisible" value="1"/>
    </form>
</div>

<?php
$this->inlineScript()->prependFile($this->basePath('js/report/actual-goal-level.js'));
$this->inlineScript()->prependFile($this->basePath('js/homepage/detailb2.js'));
echo $this->inlineScript();
?>
<script>
    $("document").ready(function () {
        DETAIL_B.init();
        ACTUAL_GOAL_LEVEL.init();
        $('[data-toggle="popover"]').popover();
    });
</script>