<!-- Styles -->
<?php $this->headLink ()->appendStylesheet ( $this->basePath ( 'css/home-static.css' ) )?>
<!-- Scripts -->

<div class="box box-shadow-none">
    <div class="box-header border-none">サイトポリシー</div>    
</div> 

<div class="box">
    <div class="box-header title-policy-content">ウェブサイトご利用にあたって</div>
    <div class="box-body">
       <div>このウェブサイトは公益財団法人 日本英語検定協会（以下「協会」とします）またはその代理人が運営しています。</div>
       <div class=" padt10 padbt10">このウェブサイトのご利用に先立ち、以下の利用条件をよくお読みいただき、これらの条件に同意された場合のみご利用ください。</div>
       <div class=" padt10 padbt10">このウェブサイトをご利用いただく場合は、全ての条件に同意されたとみなしますので、ご了承願います。</div>
       <div class=" padt10 padbt10"> なお、協会はこのウェブサイトのご利用条件を予告なしに変更することがありますので、最新の内容をご確認いただきますよう、お願い申し上げます。</div>
    </div>
</div>

<div class="box">
    <div class="box-header title-policy-content">推奨環境について</div>
    <div class="box-body">
        <ul class="no-pad list-style-type-none">
            <li>1. OS・ブラウザは下記のものに対応しています
                <ul class="padl20 list-style-type-none">
                    <li>・ OS
                        <ul class="padl20 list-style-type-none">
                            <li>・ Windows : Vista / 7</li>
                            <li>・ Mac : OS X</li>
                            <li>・ スマートフォン : iPhone OS 最新版 / Android OS 最新版</li>
                        </ul>
                    </li>
                    <li>・ ブラウザ
                        <ul class="padl20 list-style-type-none">
                            <li>・ Windows : Internet Explorer 8～11 / FireFox 最新版 / Google Chrome 最新版 </li>
                            <li>・ Mac : FireFox 最新版 / Safari 最新版 / Google Chrome 最新版</li>
                        </ul>
                    </li>
                    <li>
                        <img src="../../img/navigator-top-icon.png" class="padr5" />
                        <a href="http://www.eiken.or.jp/association/info/2014/0226_01.html" class="link-style" target="_blank">
                            <span>Windows XP サポート終了に伴う対応についてのお知らせ</span>
                        </a>
                    </li>
                </ul>
            </li>
         </ul>   
         <div>2. 上記に記載されているバーションの「最新版」は開発時のものとします（2013/3/8 現在）</div>
         <div>3. 推奨環境下でご利用いただいても、ブラウザの設定などによっては、正しく動作しない場合があります。あらかじめご了承ください。</div>
    </div>
</div>

<div class="box">
    <div class="box-header title-policy-content">アクセスログとその利用について</div>
    <div class="box-body padt10 padbt10">
       <div>このウェブサイトでは、利用される方のアクセスのログ計測を行っております。これらのアクセスログは、利便性向上のために利用され、それ以外の目的で利用されることはございません。</div>
    </div>
    
    <div class="box-body padt10 padbt10">
       <div>また、アクセス計測・ログ解析にはGoogle Analyticsを導入しております。Google Analyticsはcookieを使用し個人情報を含まずにアクセス計測・ログ解析を行います。</div>
    </div>
    
    <div class="box-body padt10">
       <div>Google Analyticsで収集された情報について詳しくは、Googleのプライバシーポリシーをご参照ください。</div>
       <div>
           <img src="../../img/google-icon.png" class="padr5" />
           <a href="https://www.google.com/intl/ja/policies/privacy/" class="link-style" target="_blank">
               <span>Googleのプライバシーポリシー</span>
           </a>
       </div>
    </div>
</div>

<div class="box">
    <div class="box-header title-policy-content">第三者が提供する広告配信サービスについて</div>
    <div class="box-body padr10">
       <ol class="padl20">
            <li>
                <div>協会では、ヤフー株式会社をはじめとする第三者から配信される広告が掲載される場合があり、これに関連して、当該第三者が、協会HPを訪問した訪問者のクッキー情報等を取得し、利用している場合があります。</div>
            </li>
            <li>
                <div>当該第三者によって取得されたクッキー情報等は、当該第三者のプライバシーポリシーに従って取り扱われます。</div>
            </li>
            <li>
                <div>訪問者は、当該第三者のウェブサイト内に設けられたオプトアウトページにアクセスして、当該第三者によるクッキー情報等の広告配信への利用を停止することができます。</div>
            </li>
            <li>
                <div>
                    クッキーとは、ウェブページを利用したときに、ブラウザーとサーバーとの間で送受信した利用履歴や入力内容などを、訪問者のコンピューターにファイルとして保存しておく仕組みです。
                </div>
                <div>
                    次回、同じページにアクセスすると、クッキーの情報を使って、ページの運営者は訪問者ごとに表示を変えたりすることができます。訪問者がブラウザーの設定でクッキーの送受信を許可している場合、ウェブサイトは、訪問者のブラウザーからクッキーを取得できます。
                </div>
                <div>
                    なお、訪問者のブラウザーは、プライバシー保護のため、そのウェブサイトのサーバーが送受信したクッキーのみを送信します。
                </div>
            </li>
            <li>
                <div>訪問者は、クッキーの送受信に関する設定を「すべてのクッキーを許可する」、「すべてのクッキーを拒否する」、「クッキーを受信したら訪問者に通知する」などから選択できます。</div>
                <div>設定方法は、ブラウザーにより異なります。クッキーに関する設定方法は、お使いのブラウザーの「ヘルプ」メニューでご確認ください。</div>
            </li>
            <li>
                <div>すべてのクッキーを拒否する設定を選択されますと、認証が必要なサービスを受けられなくなる等、インターネット上の各種サービスの利用上、制約を受ける場合がありますのでご注意ください。</div>
            </li>
       </ol>
    </div>
</div>

<div class="box">
    <div class="box-header title-policy-content">著作権等について</div>
    <div class="box-body padt10 padbt10">
       <div>公益財団法人 日本英語検定協会の試験問題および当協会のホームページ内で提供されるすべての情報や商標、画像などの著作権は、公益財団法人 日本英語検定協会に帰属します。</div>
       <div>したがって、これらを使用される場合は、私的利用の範囲内で使用し、無断転載、無断コピーなどはおやめください。</div>
    </div>
    
    <div class="box-body padt10 padbt10">
       <div>私的利用の範囲を超えるご使用の場合は、当協会に申請書のご提出をお願いいたします。</div>
       <div> 申請書において当協会の著作権が確認された場合、および協会の判断により使用を認めた場合、協会が定める規定に基づき『使用許諾』を発行いたします。また、内容によっては使用料を頂く場合がございます。</div>
    </div>
    
    <div class="box-body padt10 padbt10">
       <div>ご利用の際は、下記までお問い合わせください。</div>
       <div>法務担当（TEL：03-3266-6065）</div>
    </div>
    
    <div class="box-body padt10 padbt10">
       <div>なお、個人のホームページに英検の試験問題等を掲載（コピー）することは、営利を目的とせず、個人の楽しみで作っている場合でも、不特定多数の人が閲覧することが可能であることから、私的利用には該当いたしませんので、ご注意ください。</div>
    </div>
</div>

<div class="box">
    <div class="box-header title-policy-content">掲載情報について</div>
    <div class="box-body padt10 padbt10">
       <div>協会はこのウェブサイトに情報を掲載する際には細心の注意を払っておりますが、その内容の正確性・妥当性、ご利用目的への適合性、安全性について保証するものではありません。 協会は予告なしに掲載内容を変更・削除することがあります。 また、ウェブサイト自体の運営を中断または中止させていただくことがあります。</div>
    </div>
</div>

<div class="box">
    <div class="box-header title-policy-content">禁止事項</div>
    <div class="box-body padt10 padbt10">
       <div>このウェブサイトのご利用に際し、次の行為を禁止します。</div>
       <div>・ 第三者または当協会の財産もしくはプライバシーを侵害する行為、または侵害するおそれのある行為。</div>
       <div>・ 第三者または当協会に、不利益もしくは損害を与える行為、またはそのおそれがある行為。</div>
       <div>・ 第三者または当協会の名誉もしくは信用を毀損する行為。</div>
       <div>・ 公序良俗に反する行為、またはそのおそれのある行為。</div>
       <div>・ 犯罪行為または犯罪に結びつく行為、またはそのおそれがある行為。</div>
       <div>・ 他人の電子メールアドレスを登録する等、虚偽の申告、届出を行う行為。</div>
       <div>・ 営業活動または営利を目的とする行為、またはその準備を目的とする行為。</div>
       <div>・ コンピュータウィルス等有害なプログラムを使用もしくは提供する行為、またはそのおそれのある行為。</div>
       <div>・ その他、法律、法令または条例に違反する行為、またはそのおそれのある行為。</div>
       <div>・ その他、協会が不適切と判断する行為。</div>
    </div>
</div>

<div class="box">
    <div class="box-header title-policy-content">リンクについて</div>
    <div class="box-body padt10 padbt10 padr5">
       <div>事前に協会からの文書による承諾を得ない限り、このウェブサイトへリンクをはることはできません。このウェブサイトへのリンクを希望する場合は、必ずリンク元のURL、協会ホームページの希望リンク先のURLをこちらへご連絡ください。リンクの際のURLは、http://www.eiken.or.jp/を基準に公益財団法人 日本英語検定協会のウェブサイトである旨を明示してください。</div>
       <div>なお、このウェブサイトへのリンクとして相応しくないと判断した場合は、リンクをお断りすることがあります。</div>
       <div>このウェブサイトからもしくはこのウェブサイトへリンクをはっている、協会以外の第三者のウェブサイト（以下「リンクサイト」といいます）はそれぞれ第三者の責任で管理されているものであり、協会の管理下にあるものではありません。 リンクサイトはそれぞれの利用条件に従ってご利用ください。</div>
    </div>
    
    <div class="box-body padt10 padbt10">
       <div>協会はリンクサイトに掲載されている商品、サービス、会社などを推奨するものではなく、また、リンクは協会とリンクサイトとの間に提携などの特別な関係があるということを意味するものではありません。</div>
    </div>
    
    <div class="box-body padt10 padbt10">
       <div>協会はリンクサイトの内容について、また、それらをご利用になったことによるいかなる損害についても責任を負いません。</div>
    </div>
</div>

<div class="box">
    <div class="box-header title-policy-content">免責事項</div>
    <div class="box-body padt10 padbt10">
       <div>このウェブサイトの利用は、お客様の責任において行われるものとします。</div>
       <div>このウェブサイトをご利用中に発生した直接・間接の損失・損害に対し、協会はいかなる責任も負いません。</div>
    </div>
</div>

<div class="box margin-footer">
    <div class="box-header title-policy-content">法準拠および管轄裁判所</div>
    <div class="box-body padt10 padbt10">
       <div>このウェブサイトのご利用並びに本ご利用条件の解釈および適用は、他に別段の定めのない限り、日本国法に準拠するものとします。</div>
       <div>また、このウェブサイトの利用に関わる全ての紛争については、他に別段の定めのない限り、東京地方裁判所を第一審専属管轄裁判所とします。</div>
    </div>
</div>

<div class="clearfix"></div>