<!-- Styles -->
<?php $this->headLink ()->appendStylesheet ( $this->basePath ( 'css/home-static.css' ) )?>
<!-- Scripts -->

<div class="box">
    <div class="box-header title-policy border-bottom-privacy-policy padt20 padbt20">個人情報保護方針</div>   
    <div class="box-body text-right">
        <div>（制定）平成16年12月14日</div>
        <div>（最終改定）平成27年7月31日</div>
        <div>公益財団法人 日本英語検定協会</div>
        <div>理事長 松川 孝一</div>
    </div> 
</div> 

<div class="box">
    <div class="box-header title-policy-content">基本方針</div>
    <div class="box-body padr10">
       <div>公益財団法人 日本英語検定協会（以下「協会」といいます）は、英語検定事業の運営に際し、受験者の皆さま、英語検定に関係される皆さま、当協会職員など、多くの方々の個人情報を取り扱う法人として、個人情報の保護が事業活動の基本であるとともに、その適切な管理を行うことが社会的責務と考えております。当協会では、役員を含むすべての職員がこのような共通認識のもと、下記に定める基本方針に基づき個人情報の保護に取り組んでまいります。</div>
       <div class="text-center">記</div>
       <ol class="padl20">
            <li>
                <div>ご本人から個人情報をご提供いただく場合には、あらかじめその目的を明示し、その目的の達成に必要な範囲を超えた個人情報の取り扱い（以下「目的外利用」といいます）はいたしません。協会は目的外利用を禁止し、そのために必要な措置を講じます。また、目的外利用を行う必要が生じた場合は、事前にご本人にその目的をご連絡し、同意を得た上で取り扱います。</div>
            </li>
            <li>
                <div class="padt10">ご本人からご提供いただいた個人情報は、次の場合を除き第三者に開示または提供いたしません。 </div>
                <div class="padt10">2-1. ご本人の同意がある場合</div>
                <div>2-2. 個人情報に関する機密保持契約を締結している業務委託会社に対して、ご本人に明示した目的の達成に必要な範囲で個人情報の取り扱いを委託する場合</div>
                <div>2-3. 統計的なデータとして、個人を識別できない状態に加工した場合</div>
                <div>2-4. 法的な命令等により、個人情報の開示等を求められた場合</div>
            </li>
            <li>
                <div class="padt10">ご本人がご自身の個人情報について確認されたい場合には、下記「お問い合わせ先」にご連絡ください。当協会では、第三者への漏えいを防止するため、ご本人がご自身であることを確認した場合に限りお知らせいたします。また、ご本人の個人情報の変更や削除等のご依頼、苦情および相談に対しても同様の手続きを行い、これに対応いたします。</div>
            </li>
            <li>
                <div class="padt10">
                    ご提供いただいたご本人の個人情報は当協会で厳重に保管・管理するとともに、個人情報への不正アクセス、個人情報の紛失、破壊、改ざんおよび漏えい等を防止するために適切なセキュリティ対策を講じます。
                </div>
            </li>
            <li>
                <div class="padt10">個人情報に関する法令、国が定める指針およびその他の規範を遵守いたします。</div>
            </li>
            <li>
                <div class="padt10">個人情報保護に関する職員への教育・研修を適宜実施し、周知徹底するとともに意識向上と啓蒙に努めます。</div>
            </li>
            <li>
                <div class="padt10">本基本方針は、当協会のインターネット・ホームページ等に掲載することにより、いつでも閲覧可能な状態にします。</div>
            </li>
            <li>
                <div class="padt10">個人情報保護に関する日本工業規格「個人情報保護マネジメントシステム－要求事項」（JIS Q 15001:2006）に準拠した協会内規定を策定し、その遵守状況を定期的に点検および監査するとともに、これらの確認結果に基づき、継続的に個人情報保護の取り組みを見直し、改善します。</div>
            </li>
       </ol>
    </div>
    <div class="box-body padt10">
        <img src="../../img/icon_pdf_01.gif">
        <a target="_blank" class="link-style" href="http://www.eiken.or.jp/privacypolicy/pdf/privacypolicynm.pdf"><span>特定個人情報（共通番号）に関して</span></a>
    </div>
</div>

<div class="box">
    <div class="box-header title-policy-content">個人情報の取り扱いについて</div>
    <div class="box-body">
        <div class="pull-right padl10 padbt10">
            <a href="http://privacymark.jp/" target="_blank">
                <img src="../../img/privacy-icon.gif">
            </a>
        </div>
        <div>公益財団法人 日本英語検定協会は、皆さまの個人情報を取り扱う法人として、その保護ならびに適切な管理を行うことが社会的責務と考え、個人情報保護法のもと、その遂行に以下の事項を定め鋭意取り組んでおります。</div>
        <ol class="padl20">
            <li>
                <div class="font-weight-bold">事業者の名称：</div>
                <div>公益財団法人 日本英語検定協会</div>
            </li>
            <li>
                <div class="font-weight-bold">個人情報保護管理者：</div>
                <div>当協会総務部長</div>
            </li>
            <li>
                <div class="font-weight-bold">利用目的：</div>
                <div>受験申し込みの際にご記入いただく個人情報は、英語検定業務の円滑な実施、合格者に対する「合格証明書」発行等のサービスの実施、および英語検定統計のために利用いたします。</div>
                <div>また、これ以外の目的に利用する場合は、新たに皆さまの同意を得た上で行います。</div>
            </li>
            <li>
                <div class="font-weight-bold">第三者への提供：</div>
                <div>お預かりした個人情報は、以下を除いて提供することはありません。</div>
                <div>・ ご本人の同意を得た場合</div>
                <div>・ 法令に基づく場合</div>
                <div>・ 人の生命、身体または財産の保護のために必要な場合であって本人の同意を得ることが困難な場合</div>
                <div>・ 公衆衛生の向上又は児童の健全な育成の推進のために特に必要がある場合で、本人の同意を得ることが困難な場合</div>
                <div>・ 国の機関若しくは地方公共団体又はその委託を受けた者が法令の定める事務を遂行することに対して協力する場合に、本人の同意を得ることによって当概事務の遂行に支障を及ぼすおそれがあるとき</div>
            </li>
            <li>
                <div class="font-weight-bold">委託について：</div>
                <div>業務運営に際し、委託先に預託することがあります。</div>
            </li>
            <li>
                <div class="font-weight-bold">開示、訂正、追加又は削除：</div>
                <div>ご本人からの開示、訂正、追加又は削除のお申し出については（お問い合わせ先）にお申し出ください。</div>
            </li>
            <li>
                <div class="font-weight-bold">個人情報を与えることの任意性及び与えなかった場合の結果：</div>
                <div>個人情報の当協会へのご提供は、ご本人の任意ですが、当協会の受験者登録に必要な情報が提供されない場合、申込を辞退されたものとみなす場合もありうることを予めご承知おきください。</div>
            </li>
        </ol>
    </div>
</div>

<div class="box">
    <div class="box-header title-policy-content">個人情報の取り扱いに関するお問い合わせ</div>
    <div class="box-body padbt10">
        <div>当協会の個人情報保護方針に関するお問い合わせ、ならびに当協会が保有する開示対象個人情報の利用目的の通知、開示、内容の訂正、追加または削除、利用の停止、消去および第三者への提供の停止をご希望の方は、下記のお問い合わせ先までお申し出ください。</div>
    </div>
    <div class="box-body padt10 padbt10">
        <div>〒162-8055　東京都新宿区横寺町55</div>
        <div>公益財団法人 日本英語検定協会・情報セキュリティ管理委員会</div>
    </div>
    <div class="box-body padt10">
        <img src="../../img/google-icon.png" />
        <a target="_blank" href="https://uketuke.eiken.or.jp/privacy21/" class="link-style"><span>個人情報保護に関するお問い合わせフォーム</span></a>
    </div>
</div>

<div class="box margin-footer">
    <div class="box-header title-policy-content">お問い合わせフォームご利用について</div>
    <div class="box-body">
        <ol class="padl20">
            <li>
                <div class="font-weight-bold">ブラウザはできるだけ最新のバージョンのものをお使いください。</div>
                <div>Windows：Internet Explorer 7.0以上, Firefox 2.0以上</div>
                <div>Mac OS X：Safari1.2以上</div>
                <div>（iPhoneなどスマートフォンでのご利用は保証しておりません）</div>
                <div>
                   <img src="../../img/navigator-top-icon.png" />
                   <a target="_blank" href="http://www.eiken.or.jp/association/info/2014/0226_01.html" class="link-style">
                       <span>Windows XP サポート終了に伴う対応についてのお知らせ</span>
                   </a>
                </div>
            </li>
            <li>
                <div class="font-weight-bold">「SSLを使用する」に設定してください。</div>
                <div>例：Internet Explorerをお使いの場合</div>
                <div>ツールメニュー→インターネット オプション→詳細設定タブ→「SSL2.0を有効にする、3.0を有効にする」</div>
                <div>にチェックが入っているかを確認してください。</div>
            </li>
            <li>
                <div class="font-weight-bold">ブラウザによってはスクリプト関係の設定でエラーとなる場合があります。</div>
                <div>例：Internet Explorerをお使いの場合</div>
                <div>「セキュリティ」を既定のレベル「中」、「プライバシー」のレベルを「中」以下</div>
                <div>に設定してください。</div>
            </li>
            <li>
                <div class="font-weight-bold">時期によって回答が遅れる場合がございます。</div>
                <div>通常、2営業日以内に回答いたしますが、連休明けや申込締切日前後はお時間をいただく場合がございます。あらかじめご了承ください。</div>
            </li>
            <li>
                <div class="font-weight-bold">携帯電話からはご利用いただくことができません。</div>
                <div>パソコンをご利用いただけない方は、お電話にてお問い合わせください。</div>
            </li>
            <li>
                <div class="font-weight-bold">システムメンテナンスにより利用できない時間帯があります。</div>
                <div>誠に申し訳ございませんが、システムメンテナンス後にお問い合わせください。</div>
            </li>
        </ol>
    </div>
</div>

<div class="clearfix"></div>