<!-- Styles -->
<?php $this->headLink ()->appendStylesheet ( $this->basePath ( 'css/home-static.css' ) )?>
<!-- Scripts -->

<div class="box eiken-policy">
	<div class="box-header">
		<strong>サイトマップ</strong>
	</div>
</div>

<div class="col-md-3 padr10 navigator-line-height">
	<div class="box navigator-height-first">
		<div class="box-header">
			<strong>各種検定申込</strong>
		</div>
		
		<div class="box-body navigator padl20">
            <ul class="padl20">
                <li><a href="javascript: void(0);"><span>英検IBA申込</span></a>
                    <ul class="padl20">
                        <li><a href="javascript: void(0);"><span>IBA申込登録</span></a></li>
                    </ul>
                </li>
                <li><a href="javascript: void(0);"><span>英検申込</span></a>
                    <ul class="padl20">
                        <li><a href="javascript: void(0);"><span>個別支払</span></a></li>
                        <li><a href="javascript: void(0);"><span>案内状作成</span></a>
                            <ul class="padl20">
                                <li><a href="javascript: void(0);"><span>受験案内状設定</span></a></li>
                                <li><a href="javascript: void(0);"><span>目標級設定</span></a></li>
                                <li><a href="javascript: void(0);"><span>受験案内状印刷</span></a></li>
                            </ul>
                        </li>
                        <li><a href="javascript: void(0);"><span>団体支払</span></a>
                            <ul class="padl20">
                                <li><a href="javascript: void(0);"><span>案内状作成</span></a></li>
                                <li><a href="javascript: void(0);"><span>申込登録</span></a></li>
                            </ul>
                        </li>
                    </ul>
                </li>
            </ul>
		</div>
	</div>
</div>
	
<div class="col-md-9">
	<div class="col-md-4 padr10 padl10 navigator-line-height">
		<div class="box navigator-height">
			<div class="box-header">
				<strong>成績分析</strong>
			</div>
			
			<div class="box-body navigator padr5">
			   <ul class="padl20">
				   <li><a href="javascript: void(0);"><span>英検級取得率：目標対実績</span><br /><span>（級別）</span></a></li>
				   <li><a href="javascript: void(0);"><span>英検級取得率：目標対実績</span><br /><span>（年度比較）</span></a></li>
				   <li><a href="javascript: void(0);"><span>CSEスコア推移表</span></a></li>
			   </ul>
			</div>
		</div>
	</div>
	
	<div class="col-md-4 padr10 padl10 navigator-line-height">
		<div class="box navigator-height">
			<div class="box-header">
				<strong>申込履歴・結果照会</strong>
			</div>
			
			<div class="box-body navigator">
                <ul class="padl20">
                    <li><a href="javascript: void(0);"><span>申込履歴照会</span></a></li>
                    <li><a href="javascript: void(0);"><span>試験結果照会</span></a>
                        <ul class="padl20">
                            <li><a href="javascript: void(0);"><span>英検履歴</span></a></li>
                            <li><a href="javascript: void(0);"><span>IBA履歴</span></a></li>
                        </ul> 
                    </li>
                </ul>
			</div>
		</div>
	</div>
	
	<div class="col-md-4 padl10 navigator-line-height">
		<div class="box navigator-height">
			<div class="box-header">
				<strong>学習進捗管理</strong>
			</div>
			
			<div class="box-body navigator">
			   <ul class="padl20">
				   <li><a href="javascript: void(0);"><span>スタギア学習進捗照会</span></a></li>
			   </ul>
			</div>
		</div>
	</div>
	
	<div class="clearfix"></div>
	
	<div class="col-md-4 padr10 padl10 navigator-line-height">
		<div class="box navigator-height">
			<div class="box-header">
				<strong>目標設定・学習計画</strong>
			</div>
			
			<div class="box-body navigator padr5">
                <ul class="padl20">
                    <li><a href="javascript: void(0);"><span>目標設定</span></a>
                        <ul class="padl20">
                            <li><a href="javascript: void(0);"><span>目標設定</span></a></li>
                            <li><a href="javascript: void(0);"><span>全国・都道府県別・</span><br /><span>自校英検取得率照会</span></a></li>
                            <li><a href="javascript: void(0);"><span>学年の目標級対英検級</span><br /><span>取得率</span></a></li>
                        </ul>
                    </li>
                    <li><a href="javascript: void(0);"><span>学習計画</span></a></li>
                </ul>
			</div>
		</div>
	</div>
	
	<div class="col-md-4 padr10 padl10 navigator-line-height">
		<div class="box navigator-height">
			<div class="box-header">
				<strong>団体情報管理</strong>
			</div>
			
			<div class="box-body navigator">
			   <ul class="padl20">
				   <li><a href="javascript: void(0);"><span>学年管理</span></a></li>
				   <li><a href="javascript: void(0);"><span>クラス管理</span></a></li>
				   <li><a href="javascript: void(0);"><span>生徒管理</span></a></li>
				   <li><a href="javascript: void(0);"><span>団体情報</span></a></li>
				   <li><a href="javascript: void(0);"><span>ユーザ管理</span></a></li>
				   <li><a href="javascript: void(0);"><span>基準級</span></a></li>
			   </ul>
			</div>
		</div>
	</div>
	
	<div class="col-md-4 padl10 navigator-line-height">
		<div class="box navigator-height">
			<div class="box-header">
				<strong>ヘルプ</strong>
			</div>
			
			<div class="box-body navigator">
			   <ul class="padl20">
				   <li><a href="javascript: void(0);"><span>ポリシー</span></a></li>
				   <li><a href="javascript: void(0);"><span>サイトポリシー</span></a></li>
				   <li><a href="javascript: void(0);"><span>サイトマップ</span></a></li>
				   <li><a href="javascript: void(0);"><span>お問い合わせ先</span></a></li>
			   </ul>
			</div>
		</div>
	</div>
</div>

<div class="clearfix"></div>