<!-- Styles -->
<?php $this->headLink()->appendStylesheet($this->basePath('css/home-static.css')) ?>
<!-- Scripts -->

<div class="box eiken-policy">
    <div class="box-header">
        <strong>使い方 </strong>
    </div>
</div>

<div class="box col-md-12">
    <div class="col-md-4">
        <div class="box-header border-none">
            <strong>英検申込</strong>
        </div>

        <div class="navigator padl20">            
            <ul class="padl20">
                <li><a href="javascript:%20void(0);"><span>団体申込の流れ</span></a>
                    <ul class="padl20">
                        <li><a href="/help/eiken_apply_pattern_v06.pdf"><span>団体申込のパターン</span></a></li>
                        <li><a href="/help/eiken_invitation_letter_v06.pdf"><span>英検受験案内状の種類</span></a></li>
                    </ul>
                </li>
                <li><a href="javascript:%20void(0);"><span>団体一括払いでの申込方法</span></a>
                    <ul class="padl20">
                        <li><a href="/help/eiken_group_payment_v07.pdf"><span>案内状不使用</span></a></li>
                        <li><a href="/help/eiken_group_payment_letter_1_v07.pdf"><span>案内状使用</span></a></li>
                    </ul>
                </li>
                <li><a href="javascript:%20void(0);"><span>受験者個別払いでの申込方法</span></a>
                    <ul class="padl20">
                        <li><a href="/help/eiken_individual_payment_letter_1_v07.pdf"><span>案内状使用（個別支払方法のみ）</span></a></li>
                        <li><a href="/help/eiken_individual_payment_letter_2_v06.pdf"><span>案内状使用（個別支払方法＋目標級）</span></a></li>
                    </ul>
                </li>
                <li><a href="/help/eiken_ichimen_search_v08.pdf"><span>一免者参照</span></a></li>
                <li><a href="/help/eiken_invitation_letter_edit_download_v06.pdf"><span>受験案内状編集・印刷</span></a></li>
            </ul>

        </div>
        <div class="box-header border-none">
            <strong>英検IBA申込</strong>
        </div>
        <div class="navigator padl20">
            <ul class="padl20">
                <li><a href="/help/eiken-iba_apply_v06.pdf"><span>団体申込登録</span></a></li>
            </ul>
        </div>  
         <div class="box-header border-none">
            <strong>申込履歴照会</strong>
        </div>

        <div class="navigator padr5 padl20">
            <ul class="padl20">
                <li><a href="/help/application_info_details_v06.pdf"><span>申込情報詳細</span></a></li>
                <li><a href="/help/regist_payment_info_v08.pdf"><span>登録支払状況</span></a></li>
                <li><a href="/help/eiken-kyu_recommend_info_v06.pdf"><span>目標級設定状況</span></a></li>
            </ul>
        </div>
    </div>

    <div class="col-md-4">
       

        <div class="box-header border-none">
            <strong>試験結果照会</strong>
        </div>

        <div class="navigator padl20">
            <ul class="padl20">
                <li><a href="/help/test_result_group_v06.pdf"><span>団体別</span></a></li>
                <li><a href="/help/test_result_individual_v06.pdf"><span>個人別</span></a>
                </li>
            </ul>
        </div>

        <div class="box-header border-none">
            <strong>学習進捗管理</strong>
        </div>

        <div class="navigator padl20">
            <ul class="padl20">
                <li><a href="/help/learning_progress_study-gear_individual_v06.pdf"><span>スタギア学習状況（個人別）</span></a></li>
                    <li><a href="/help/learning_progress_study-gear_group_v06.pdf"><span>スタギア学習状況（学年・クラス別）</span></a></li>
            </ul>
        </div>
          <div class="box-header border-none">
            <strong>成績分析</strong>
        </div>
        <div class="navigator padl20">
            <ul class="padl20">
                <li><a href="/help/eiken_result_taking_v06.pdf"><span>英検受験実績</span></a></li>
                <li><a href="/help/eiken_result_pass_v06.pdf"><span>英検合格実績</span></a></li>
<!--                <li><a href="/help/eiken_result_acquisition.pdf"><span>英検取得状況</span></a></li>-->
<!--                <li><a href="/help/target_achievement.pdf"><span>目標達成状況</span></a></li>-->
                <li><a href="/help/cse_transition_v06.pdf"><span>CSEスコア推移</span></a></li>
            </ul>
        </div>
<!--        <div class="box-header border-none">-->
<!--            <strong>目標設定</strong>-->
<!--        </div>-->
<!--        <div class="navigator padl20">-->
<!--            <ul class="padl20">-->
<!--                <li><a href="/help/target_set_at_graduation.pdf"><span>卒業時の目標設定</span></a></li>-->
<!--                <li><a href="/help/target_set_every_year.pdf"><span>年度ごとの目標設定</span></a></li>-->
<!--            </ul>-->
<!--        </div>-->
         <div class="box-header border-none">
            <strong>学習計画</strong>
        </div>

        <div class="navigator padl20">
            <ul class="padl20">
                <li><a href="/help/annual_schedule_v06.pdf"><span>年間スケジュール</span></a></li>
            </ul>
        </div>
    </div>

    <div class="col-md-4">
        <div class="box-header border-none">
            <strong>マスタ設定</strong>
        </div>

        <div class="navigator padl20">
            <ul class="padl20">
                <li><a href="/help/set_grade_info_v06.pdf"><span>学年登録</span></a></li>
                <li><a href="/help/set_eiken-kyu_standard_v06.pdf"><span>基準級登録</span></a></li>
                <li><a href="/help/set_class_info_v06.pdf"><span>クラス登録</span></a></li>
                <li><a href="/help/set_student_info_v06.pdf"><span>生徒情報登録</span></a></li>
                <li><a href="/help/group_info_v06.pdf"><span>団体情報参照</span></a></li>
                <li><a href="/help/user_info_v06.pdf"><span>ユーザ情報管理</span></a></li>
            </ul>
        </div>

        <div class="box-header border-none">
            <strong>その他</strong>
        </div>

        <div class="navigator padr5 padl20">
            <ul class="padl20">
                <li><a href="/help/login_logout_v07.pdf"><span>ログイン・ログアウト</span></a>
                     </li>
                        <li><a href="/help/top_page_v08.pdf"><span>トップページ</span></a></li>
                        <li><a href="/help/function_restriction_by_student_info_v06.pdf"><span>生徒情報の有無と利用できる機能</span></a></li>
                        <li><a href="/help/recommendation_environment.pdf"><span>利用推奨環境</span></a></li>
                   
            </ul>
        </div>

        <div class="box-header border-none">
            <strong>受験者サポート</strong>
        </div>

        <div class="navigator padr5 padl20">
            <ul class="padl20">
                <li><a href="/help/jukensha-support_login_logout_v06.pdf"><span>ログイン・ログアウト</span></a>
                </li>
                <li><a href="/help/jukensha-support_top_page_v06.pdf"><span>トップページ</span></a></li>
                <li><a href="/help/jukensha-support_eiken_application_v08.pdf"><span>英検のお申し込み</span></a></li>
                <li><a href="/help/jukensha-support_ei-navi_v06.pdf"><span>英ナビ！の利用</span></a></li>
            </ul>
        </div>
    </div>
</div>

<div class="clearfix"></div>