<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'AccessKey\Module'                        => __DIR__ . '/Module.php',
    'AccessKey\Controller\AccessKeyController' => __DIR__ . '/src/AccessKey/Controller/AccessKeyController.php',
);
