<?php
$this->headLink()->prependStylesheet($this->basePath('css/OrgInforManagement.css'));
$paging = $this->paginationHelper($paginator, $page, $this->url('org-mnt/default', array('controller' => 'org', 'action' => 'index')), $numPerPage);
$this->headScript()->appendFile($this->basePath('js/jquery-ui.js'));

$form->setAttribute('action', $this->url('org-mnt/default', array(
            'controller' => 'org',
            'action' => 'index'
)));
echo $this->form()->openTag($form);
$advancedSearchVisible = ($form->get('refundStatus')->getValue() != '') || ($form->get('publicFunding')->getValue() != '') || ($form->get('paymentBill')->getValue() != '');
?>
<div class="row">    
    <div class="box frm-detail">
        <div class="box-header collapsed" data-toggle="collapse" data-target="#search-box">
            <div class="search-header  sorting-field">
                <i class="search-chevron-down"></i>
                <?php echo $this->translate('検索条件'); ?>
            </div>
        </div>
        <div id="search-box" aria-expanded="true" class="collapse in">   
            <div class="box-body search-org">
                <div class="row r1">
                    <div class="col-sm-2 title-txtOrgNumber">
                        <label><b><?php echo $this->translate('団体番号'); ?></b></label>
                    </div>
                    <div class="col-sm-3 input-txtOrgNumber" id="divOrgNumber"><?php echo $this->formRow($form->get('txtOrgNumber')); ?></div>
                    <div class="col-sm-2 title-org-name">
                        <label><?php echo $this->translate('団体名（漢字）'); ?></label>
                    </div>
                    <div class="col-sm-3 input-org-name" id="divOrgName"><?php echo $this->formRow($form->get('txtOrgName1')); ?></div>
                    <div class="col-sm-2 title-teet">
                        <label><b><?php echo $this->translate('団体名（カナ）'); ?></b></label>
                    </div>
                    <div class="col-sm-3 styled-select input-teet" id="divEikenType"><?php echo $this->formRow($form->get('txtOrgName2')); ?></div>
                </div>
                <div class="row r2">
                    <label class="col-sm-2 title_ex"><b><?php echo $this->translate('検定名'); ?></b>
                    </label>
                    <div class='col-sm-2 select_ex styled-select'>
                        <?php echo $this->formRow($form->get('txteet')); ?>
                    </div>
                    <label class="col-sm-2 title-date-1"><b><?php echo $this->translate('検定試験申込日'); ?></b></label>
                    <div class='col-sm-2'>
                        <div class="form-group">
                            <div class='input-group date' id="divStartDate">
                                <?php echo $this->formRow($form->get('datetime1')); ?>
                                <span class="input-group-addon"> <span class="icon-calendar"
                                                                       onclick="showCalendar(1)"></span>
                                </span>
                            </div>
                        </div>
                    </div>
                    <label class="col-sm-1 label1"><?php echo $this->translate('（から）'); ?></label>
                    <div class='col-sm-2 datemargin'>
                        <div class="form-group">
                            <div class='input-group date input-date-2' id="divEndDate">
                                <?php echo $this->formRow($form->get('datetime2')); ?>
                                <span class="input-group-addon"> <span class="icon-calendar"
                                                                       onclick="showCalendar(2)"></span>
                                </span>
                            </div>
                        </div>
                    </div>
                    <label class="col-sm-1 lable-title lable1"><?php echo $this->translate('（まで）'); ?></label>

                </div>
                <div class="collapsed ">
                    <p class="sorting-field advanced-search">
                        <span class="<?php echo ($form->get('refundStatus')->getValue() == '') ? 'search-plus-square-o-blue' : 'search-minus-square-o-blue'; ?>"></span>
                        <?php echo $this->translate('高度な検索'); ?>
                    </p>
                </div>
                <div>
                    <div id="advanced-search" class="row <?php if (!$advancedSearchVisible) echo 'hide'; ?>"> 
                        <div class="row refund-search">
                            <label class="col-sm-1 lblRefundStatus"><?php echo $this->translate('lblRefundStatus'); ?></label>
                            <div class="col-sm-3 select-refund styled-select">
                                <?php echo $this->formRow($form->get('refundStatus')); ?>                                            
                            </div>
                        </div>
                        <div class="row">
                            <label class="col-sm-1 lbl-public-funding"><?php echo $this->translate('lblPublicFunding'); ?></label>
                            <div class="col-sm-2 select-public-funding styled-select">
                                <?php echo $this->formRow($form->get('publicFunding')); ?>                                            
                            </div>
                            <label class="col-sm-2 lbl-payment-bill"><?php echo $this->translate('lblPaymentBill'); ?></label>
                            <div class="col-sm-2 select-public-funding styled-select">
                                <?php echo $this->formRow($form->get('paymentBill')); ?>                                            
                            </div>
                        </div>
                    </div>
                </div>
                <div class="box-footer btn-org">
                    <div class="text-right">
                        <a class="btn btn-small-100 margin-right-10" id="btnClear"
                           href="javascript:void(0);"><?php echo $this->translate('クリア'); ?></a>
                        <a class="btn btn-small-180" type="button" onClick="submit_form()"
                           href="javascript:void(0);"><i class="fa-search"></i><?php echo $this->translate('検索'); ?>
                        </a>
                    </div>
                </div>
            </div>                        
        </div>
    </div>            
</div>
<?php echo $this->form()->closeTag(); ?>
<div class="box search-form15">
    <div class="box-header">
        <span><b><?php echo $this->translate('団体検索'); ?></b></span>
    </div>
    <div class="box-body bd-search-org">
        <div class="row">
            <div class="pull-right">
                <a class="btn btn-red btn-small-180 <?php if(!\Dantai\PublicSession::isSysAdminRole()) echo 'disabled'; ?>"  href="<?php echo $this->url('org-mnt/default', array('controller' => 'importmasterdata', 'action' => 'index')); ?>">
                    <i class="fa-upload-small-w" ></i> <?php echo $this->translate('TextButtonUpload'); ?>
                </a>
            </div>
        </div>
        <!-- id="hidethis" style="display: none;"  -->
        <div class="row">
            <div class="top-mark">
                <?php if ($advancedSearchVisible) { ?>
                    <label class="font-mark"><?php echo $this->translate('DescriptionSearchOrgTable'); ?></label><br>
                    <label class="font-mark search-attribute">
                        <?php
                        echo $form->get('refundStatus')->getValue() != '' ?
                                $this->translate('lblRefundStatus') . ': ' . $form->get('refundStatus')->getValueOptions()[$form->get('refundStatus')->getValue()] . '<br>' : '';
                        ?>                    

                        <?php
                        echo $form->get('publicFunding')->getValue() != '' ?
                                $this->translate('lblPublicFunding') . ': ' . $form->get('publicFunding')->getValueOptions()[$form->get('publicFunding')->getValue()] . '<br>' : '';
                        ?>                   

                        <?php
                        echo $form->get('paymentBill')->getValue() != '' ?
                                $this->translate('lblPaymentBill') . ': ' . $form->get('paymentBill')->getValueOptions()[$form->get('paymentBill')->getValue()] . '<br>' : '';
                        ?>
                    </label>
                <?php } ?>
            </div>
            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th class="width170"><?php echo $this->translate('団体番号'); ?></th>
                        <th class="width270"><?php echo $this->translate('OrganizationName(Kanji)'); ?></th>
                        <th class="width255"><?php echo $this->translate('OrganizationName(Kana)'); ?></th>
                        <th ><?php echo $this->translate('住所 '); ?></th>
                        <th class="width95">準的本会場</th>
                        <th class="col-sm-3 width215"><?php echo $this->translate('操作'); ?></th>
                    </tr>
                </thead>
                <tbody>
                    <?php if ($items) { ?>
                        <?php foreach ($items as $key => $value) {
                            ?>
                            <tr class="text-center">
                                <td class="data-orgno"><?php echo $this->escapeHtml($value['organizationNo']); ?></td>
                                <td><?php echo $this->escapeHtml($value['orgNameKanji']); ?></td>
                                <td><?php echo $this->escapeHtml($value['orgNameKana']); ?></td>
                                <td>
                                    <?php
                                    if (!empty($value['cityId'])) {
                                        echo $this->escapeHtml($value['cityName'] . $value['address1']);
                                    } else {
                                        echo $this->escapeHtml($value['address1']);
                                    }
                                    ?>
                                </td>
                                <td class = "text-center">
                                    <?php
                                    //change for ticket GNCCNCJDM-274
                                    if (!\Dantai\PublicSession::isSysAdminOrServiceManagerOrOrgSupervisor())
                                        $form->get('semiMainVenue[]')->setAttribute('disabled', 'disabled');
                                    echo $this->formrow($form->get('semiMainVenue[]')->setCheckedValue($value['id'])->setChecked(($value['semiMainVenue'] == 1) ? true : false));
                                    ?>
                                </td>
                                <td class = "center">
                                    <a data-id = "<?php echo $value['id']; ?>"
                                       data-orgno = "<?php echo $value['organizationNo']; ?>"
                                       class = "btn btn-small-76 showdetail"
                                       href = "javascript:void(0);"><?php echo $this->translate('詳細表示'); ?>
                                    </a>
                                    <button
                                        class = "btn btn-small-98" <?php echo!\Dantai\PublicSession::isRole1236() ? 'disabled' : '' ?>
                                        onclick = "switchOrg('<?php
                                        echo $this->url('org-mnt/default', array(
                                            'controller' => 'org',
                                            'action' => 'transform',
                                            'id' => $value['id'],
                                        ));
                                        ?>')">
                                            <?php echo $this->translate('団体トップページ'); ?>
                                    </button>
                                </td>
                            </tr>
                        <?php } ?>
                    <?php } ?>
                </tbody>
            </table>
            <?php
            if (count($paginator) == 0) {
                echo '<p class="msgnull">' . $this->translate("MSGnoresult") . '</p>';
            }
            ?>
            <?php if (count($paginator) > $numPerPage) { ?>
                <div class="col-sm-12 text-center list-org-user-table list-org-user-pagination">
                    <nav>
                        <ul class="pagination">
                            <?php echo $paging; ?>
                        </ul>
                    </nav>
                </div>
            <?php } ?>
        </div>
    </div>
</div>
<script type="text/javascript">
    var jsMessages_cl = <?php echo $jsMessages->jsonSerialize(); ?>;
    var jsMessages = jsMessages_cl.data;

//validate
    jQuery.validator.addMethod("comparedate",
            function (value, element) {
                var date2 = $("#datetimepicker2").val();
                date2 = Date.parse(date2);
                var date1 = $("#datetimepicker1").val();
                date1 = Date.parse(date1);
                if (value == "")
                    return true;
                if (date2 < date1) {
                    return false;
                } else {
                    return true;
                }
            }, 'date from > date to');
//  date fomat
    jQuery.validator.addMethod("dateISO2", function (value, element) {
        if (value.length != 0) {
            if (/^\d{4}[\/]\d{2}[\/]\d{2}$/.test(value) == false) {
                return false;
            }
        }
        var array = value.split("/");
        var dtDay = parseInt(array[2]);
        var dtMonth = parseInt(array[1]);
        var dtYear = parseInt(array[0]);

        if (dtMonth < 1 || dtMonth > 12) {
            return false;
        }
        else if (dtDay < 1 || dtDay > 31) {
            return false;
        }
        else if ((dtMonth == 4 || dtMonth == 6 || dtMonth == 9 || dtMonth == 11) && dtDay == 31) {
            return false;
        }
        else if (dtMonth == 2) {
            var isleap = (dtYear % 4 == 0 && (dtYear % 100 != 0 || dtYear % 400 == 0));
            if (dtDay > 29 || (dtDay == 29 && !isleap)) {
                return false;
            }
        }
        return true;
    }, "sai dinh dang ngay thang");

    var validator = $("#OrgSearch").validate({
        onfocusout: false,
        onkeyup: false,
        onclick: false,
        focusInvalid: false,
        rules: {
            datetime1: {
                //dateISO :true,
                dateISO2: true
            },
            datetime2: {
                //dateISO :true,
                dateISO2: true,
                comparedate: true
            }
        },
        messages: {
            datetime1: {
                dateISO2: jsMessages.MSGdatefomat
            },
            datetime2: {
                dateISO2: jsMessages.MSGdatefomat,
                comparedate: jsMessages.MSGdatecompare
            }
        },
        errorPlacement: function (error, element) {
        },
        showErrors: function (errorMap, errorList) {
            this.defaultShowErrors();
            ERROR_MESSAGE.show(errorList, function () {
            }, 'inline');
        }
    });
    function submit_form()
    {
        $('#OrgSearch').submit();
    }
// check API
    $(".showdetail").click(function () {
        var id = $(this).data("id");
        var orgno = $(this).data("orgno");
        $.ajax({
            type: 'POST',
            url: "<?php echo $this->url('org-mnt/default', array('controller' => 'org', 'action' => 'getAPI')); ?>",
            data: {id: id, orgno: orgno},
            success: function (data) {
                if (data.length != 0) {
                    ERROR_MESSAGE.show(data,
                            function ()
                            {
                                //alert("Callback");
                            });
                } else {
                    window.location = "<?php echo $this->url('org-mnt/default', array('controller' => 'org', 'action' => 'show',)); ?>/" + id;
                }
            },
            error: function () {
            }
        });
    });
// end check API
    $('form:first *:input[type!=hidden]:first').focus();

    $("#btnClear").click(function () {
        $(this).closest('#OrgSearch').find("input[type=text], select").val("");
        $("#OrgSearch").submit();
    });
    $(document).ready(function () {
        $('#btnClear').click(function () {
            $("#divOrgNumber input").val("");
            $("#divOrgName input").val("");
            $("#divEikenType select").val("");
            $("#divStartDate input").val("");
            $("#divEndDate input").val("");
        });
        $('.advanced-search').click(function () {
            if ($('.advanced-search').find('span').hasClass('search-plus-square-o-blue')) {
                $('#advanced-search').removeClass("hide");
                $('.advanced-search').find('span').removeClass('search-plus-square-o-blue');
                $('.advanced-search').find('span').addClass('search-minus-square-o-blue');
            }
            else {
                $('#advanced-search').addClass("hide");
                $('.advanced-search').find('span').removeClass('search-minus-square-o-blue');
                $('.advanced-search').find('span').addClass('search-plus-square-o-blue');
            }
        });
    });

    $(function () {
        $('#datetimepicker1').datepicker();
        $('#datetimepicker2').datepicker();
//         $('#datetimepicker2').change(function () {
//         	var datetime1 =  parseInt(converttime($('#datetimepicker1').val()));
//         	var datetime2 =  parseInt(converttime($('#datetimepicker2').val()));
//             if(datetime2 < datetime1){
//                 $('#datetimepicker2').val('');
//             }
//         });

    });
    function converttime(datetime) {
        var time_date = new Date(datetime).getTime();
        return time_date;
    }
    function toggle() {
        if (document.getElementById("hidethis").style.display === 'none') {
            document.getElementById("hidethis").style.display = 'table'; // set to table-row instead of an empty string
        } else {
            document.getElementById("hidethis").style.display = '';
        }
    }

    function showCalendar(args) {
        var id = "datetimepicker" + args;
        $('#' + id).datepicker('show');
    }

    function switchOrg(hyperLink) {
        // remove sessionStorage for checkbox.
        sessionStorage.removeItem('cookieExport');
        // redirect to transform action.
        window.location.href = hyperLink;
    }
    $(function () {
        $.datepicker.regional['ja'] = {
            clearText: 'クリア', clearStatus: '日付をクリアします',
            closeText: '閉じる', closeStatus: '変更せずに閉じます',
            prevText: '&#x3c;前', prevStatus: '前月を表示します',
            prevBigText: '&#x3c;&#x3c;', prevBigStatus: '前年を表示します',
            nextText: '次&#x3e;', nextStatus: '翌月を表示します',
            nextBigText: '&#x3e;&#x3e;', nextBigStatus: '翌年を表示します',
            currentText: '今日', currentStatus: '今月を表示します',
            monthNames: ['1月', '2月', '3月', '4月', '5月', '6月',
                '7月', '8月', '9月', '10月', '11月', '12月'],
            monthNamesShort: ['1月', '2月', '3月', '4月', '5月', '6月',
                '7月', '8月', '9月', '10月', '11月', '12月'],
            monthStatus: '表示する月を変更します', yearStatus: '表示する年を変更します',
            weekHeader: '週', weekStatus: '暦週で第何週目かを表します',
            dayNames: ['日曜日', '月曜日', '火曜日', '水曜日', '木曜日', '金曜日', '土曜日'],
            dayNamesShort: ['日', '月', '火', '水', '木', '金', '土'],
            dayNamesMin: ['日', '月', '火', '水', '木', '金', '土'],
            dayStatus: '週の始まりをDDにします', dateStatus: 'Md日(D)',
            dateFormat: 'yy/mm/dd', firstDay: 0,
            initStatus: '日付を選択します', isRTL: false,
            showMonthAfterYear: true};
        $.datepicker.setDefaults($.datepicker.regional['ja']);
    });
    $('input[name="semiMainVenue[]"]').change(function () {
        var orgId = $(this).val();
        var check = $(this).is(':checked');
        $.ajax({
            type: 'POST',
            url: COMMON.baseUrl + 'org/org/ajaxSetSemiMainVenue',
            dataType: 'json',
            data: {orgId: orgId, check: check},
            success: function (result) {
                if (!result.success) {
                    ERROR_MESSAGE.show(result.messages[0]);
                } else if (result.data.isShowMessage === 'true') {
                    ALERT_MESSAGE.show(result.messages[0])
                }
            },
            error: function () {
                return false;
            }
        });
    });
</script>



