<?php $this->headScript()->appendFile($this->basePath('js/eiken/eiken-org.js?v='. strtotime(date("y-m-d h:s:i")))) ?>
<script type="text/javascript">
    var jsMessages = <?php echo $jsMessages; ?>;
<?php if (!empty($eikenOrgDetail)) : ?>
        var eikenOrgDetail = <?php echo $eikenOrgDetailJS; ?>;
<?php else: ?>
        var eikenOrgDetail = {};
<?php endif; ?>
<?php if (!empty($applyEikenLevel['applyEikenStatus'])): ?>
        var eikenStatus = "<?php echo $applyEikenLevel['applyEikenStatus']; ?>";
<?php else: ?>
        var eikenStatus = "";
<?php endif; ?>

<?php if (!empty($applyEikenLevel['isSentStandardHall']) || $isDisableStandard): ?>
        var isSentStandardHall = 1;
<?php else: ?>
        var isSentStandardHall = 0;
<?php endif; ?>
    var invitation = <?php echo $isInvitationSetting; ?>;
    var MSGCreateGrade = '<?php echo isset($MSGCreateGrade) ? $MSGCreateGrade : ""; ?>';
    var flgHadGradeDiscount = '<?php echo isset($flgHadGradeDiscount) ? $flgHadGradeDiscount : 0; ?>';
</script>
<?php $this->headLink()->prependStylesheet($this->basePath('css/appeiken.css')) ?>
<?php
$form->setAttribute('action', 'save-registrant');
$form->prepare();
?>
<?php echo $this->form()->openTag($form); ?>
<input type="hidden" id="ExamDayInviSetting"
       value="<?php echo $inviSetting != Null ? ( ($inviSetting->getExamDay() != Null ? $inviSetting->getExamDay() : 0 ) ) : 0 ?>"/>
<input type="hidden" id="FirtNameKanji"
       value="<?php echo $this->escapeHtml($registrationInfor['firstName']); ?>">
<input type="hidden" id="LastNameKanji"
       value="<?php echo $this->escapeHtml($registrationInfor['lastName']); ?>">
<input type="hidden" id="MailAddress"
       value="<?php echo $this->escapeHtml($registrationInfor['emailAddress']); ?>">
<input type="hidden" id="PhoneNumber"
       value="<?php echo $this->escapeHtml($registrationInfor['phoneNumber']); ?>">
<input type="hidden" id="confirmMailAddress" value="<?php echo $this->escapeHtml($registrationInfor['confirmMailAddress']); ?>">
<input type="hidden" id="cityId" value="<?php echo $this->escapeHtml($registrationInfor['cityId']); ?>">
<input type="hidden" id="districtId" value="<?php echo $this->escapeHtml($registrationInfor['districtId']); ?>">

<input type="hidden" id="hasRegisterd7"
       value="<?php echo!empty($applyEikenLevel['publicSite'][7]) ? $applyEikenLevel['publicSite'][7] : 0; ?>">
<input type="hidden" id="hasRegisterd6"
       value="<?php echo!empty($applyEikenLevel['publicSite'][6]) ? $applyEikenLevel['publicSite'][6] : 0; ?>">
<input type="hidden" id="hasRegisterd5"
       value="<?php echo!empty($applyEikenLevel['publicSite'][5]) ? $applyEikenLevel['publicSite'][5] : 0; ?>">
<input type="hidden" id="hasRegisterd4"
       value="<?php echo!empty($applyEikenLevel['publicSite'][4]) ? $applyEikenLevel['publicSite'][4] : 0; ?>">
<input type="hidden" id="hasRegisterd3"
       value="<?php echo!empty($applyEikenLevel['publicSite'][3]) ? $applyEikenLevel['publicSite'][3] : 0; ?>">
<input type="hidden" id="hasRegisterd2"
       value="<?php echo!empty($applyEikenLevel['publicSite'][2]) ? $applyEikenLevel['publicSite'][2] : 0; ?>">
<input type="hidden" id="hasRegisterd1"
       value="<?php echo!empty($applyEikenLevel['publicSite'][1]) ? $applyEikenLevel['publicSite'][1] : 0; ?>">
<input type="hidden" id="orgBR72"
       value="<?php echo!empty($eikenOrgDetail['orgBR72']) ? $eikenOrgDetail['orgBR72'] : 0; ?>">
<input type="hidden" id="totalRegistereds"
       value="<?php echo $totalRegistereds; ?>">
<div class="box createekien">
    <div class="box-header">
        <strong> <?php
            if (empty($applyEikenLevel['applyEikenOrg']))
                echo $this->translate('申込情報登録：' . $year . '年度第' . $kaiNumber . '回');
            else
                echo $this->translate('団体申込情報編集：' . $year . '年度第' . $kaiNumber . '回');
            ?>
        </strong>
    </div>
    <div class="box-body">
        <div class="top-mark">
            <label class="font-mark">
                <ul class="guide-list">
                    <li>
                        申込済人数：スマホまたはPCから申請された人数です。<br/>
                        （この機能を利用されていない場合は数値が表示されません）
                    </li>
                    <li>
                        支払済人数：個人支払が済んでいる人数です。<br/>
                        （個人支払の場合のみ表示されます）
                    </li>
                    <li>申込人数：最終的に申し込む人数になります。</li>
                </ul>
                <br/>
                <p class="guide-text">【本会場の場合】</p>
<!--                <p class="guide-text">「登録」ボタンを押し、受験者の個人データを登録してください。</p>-->
                <ul class="guide-list">
                    <li>申込人数：受験者の個人データが登録されている人数です。<br/>
                        ※個人支払の場合、支払済人数と一致しているかご確認ください。
                    </li>
                </ul>
                <br/>
                <p class="guide-text">【準会場の場合】</p>
                <p class="guide-text">「申込人数」欄に各級の人数を入力してください。</p>
                <p class="guide-text-last">※個人支払の場合、支払済みの人数があらかじめ表示されています。</p>
                </label>

        </div>

        <div class="title-action">


            <a class="fl cl1"><?php echo $this->translate('ステータス'); ?>
                <?php if ((!empty($applyEikenLevel['applyEikenOrg']['status']) && $applyEikenLevel['applyEikenOrg']['status'] == 'DRAFT') || empty($applyEikenLevel['applyEikenOrg']['status'])): ?>
                    <i><?php echo $this->translate('ドラフト'); ?></i>
                <?php else: ?>
                    <i><?php echo $this->translate('提出済み'); ?></i>
                <?php endif; ?>
            </a>
        </div>
        <?php if($isOrgDiscount){ ?>
        <div>
            <p class="guide-text clred">各受験者への公費適用は、年度内につき１回のみです。すでに公費の補助を受けた受験者は団体サポートシステムからお申込できませんので、別のお申込方法をご利用いただきますようお願い申し上げます。</p>
        </div>
        <?php } ?>
        <div class="row content-ekien">
            <div class="row">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th colspan="2"><?php echo $this->translate('受験級'); ?></th>
                            <th width="9%"><?php echo $this->translate('1級 '); ?></th>
                            <th width="9%"><?php echo $this->translate('準1級 '); ?></th>
                            <th width="9%"><?php echo $this->translate('2級'); ?></th>
                            <th width="9%"><?php echo $this->translate('準2級'); ?></th>
                            <th width="9%"><?php echo $this->translate('3級'); ?></th>
                            <th width="9%"><?php echo $this->translate('4級'); ?></th>
                            <th width="9%"><?php echo $this->translate('5級'); ?></th>
                            <th width="9%"><?php echo $this->translate('合計 '); ?></th>
                        </tr>
                    </thead>
                    <tbody>
                        <!--  サテライトサイ トでの申込人数  Hoi Truong Chinh Row 1 -->
                        <tr>
                            <td width="70" rowspan="2" class="classcenter classwhite"><p>本会場</p></td>
                            <td class="classcenter" width="135"><p>申込済人数</p></td>
                            <?php
                            $grandTotal = 0;
                            for ($i = 1; $i < 8; $i++):
                                ?>
                                <td class="classright">
                                    <?php
                                    if (!empty($applyEikenLevel['publicSite'][$i])) {
                                        $grandTotal += $applyEikenLevel['publicSite'][$i];
                                        echo '<p><a id="txtMainHallExpectApplyNo' . (8 - $i) . '" href="/eiken/payment/paymentstatus/' . $eikenScheduleId . '?eikenLevelId=' . $i . '&testSite=1&regist=1' . '&backUrl=1">' . $applyEikenLevel['publicSite'][$i] . '</a></p>';
                                    }
                                    ?>
                                </td>
                            <?php endfor; ?>
                            <td class="classright total-td <?php echo $grandTotal != 0 ? 'goukei' : ''; ?>" id="grand-total-main-combini">
                                <?php echo $grandTotal != 0 ? '<p><a href="/eiken/payment/paymentstatus/' . $eikenScheduleId . '?testSite=1&regist=1' . '&backUrl=1">' . $grandTotal . '</a></p>' : '0'; ?>
                            </td>
                        </tr>
                        <!--  サテライトサイ トでの申込人数  Hoi Truong Chinh Row 2 -->
                        <tr>
                            <td class="classcenter"><p>支払済人数</p></td>
                            <?php
                            $grandTotal = 0;
                            for ($i = 1; $i < 8; $i++):
                                ?>
                                <td  class="classright" >
                                    <?php
                                    if (!empty($totalKyuPayment['mainHall'][$i]['totalKyu'])) {
                                        $grandTotal += $totalKyuPayment['mainHall'][$i]['totalKyu'];
                                        echo '<p><a href="/eiken/payment/paymentstatus/' . $totalKyuPayment['mainHall'][$i]['eikenScheduleId'] . '?eikenLevelId=' . $totalKyuPayment['mainHall'][$i]['eikenLevelId'] . '&testSite=1&regist=1&pay=1' . '&backUrl=1">' . $totalKyuPayment['mainHall'][$i]['totalKyu'] . '</a></p>';
                                    }
                                    ?>
                                </td>
                            <?php endfor; ?>
                            <td class="classright total-td <?php echo $grandTotal != 0 ? 'goukei' : ''; ?>" id="grand-total-main-combini">
                                <?php
                                echo $grandTotal != 0 ? '<p><a href="/eiken/payment/paymentstatus/' . $eikenScheduleId . '?testSite=1&pay=1&regist=1' . '&backUrl=1">' . $grandTotal . '</a></p>' : '0';
                                ;
                                ?>
                            </td>
                        </tr>
                        <!--  サテライトサイ トでの申込人数  Hoi Truong Chinh Row 3 -->
                        <!-- サテライトサイ トでの申込人数  - Standard Hall -->
                        <tr>
                            <td width="70" rowspan="3" class="classcenter classwhite"><p>準会場</p></td>
                            <td class="classcenter" width="125"><p>申込済人数</p></td>
                            <?php
                            $grandTotal = 0;
                            for ($i = 1; $i < 8; $i++):
                                ?>
                                <td class="classright">
                                    <?php
                                    if (!empty($applyEikenLevel['groupSite'][$i])) {
                                        $grandTotal += $applyEikenLevel['groupSite'][$i];
                                        echo '<p><a href="/eiken/payment/paymentstatus/' . $eikenScheduleId . '?eikenLevelId=' . $i . '&testSite=0&regist=1' . '&backUrl=1">' . $applyEikenLevel['groupSite'][$i] . '</a></p>';
                                    }
                                    ?>
                                </td>
                            <?php endfor; ?>
                            <td class="classright total-td <?php echo $grandTotal != 0 ? 'goukei' : ''; ?>" id="grand-total-standard-satteline">
                                <?php echo $grandTotal != 0 ? '<p><a href="/eiken/payment/paymentstatus/' . $eikenScheduleId . '?testSite=0&regist=1&backUrl=1">' . $grandTotal . '</a></p>' : '0'; ?>
                            </td>
                        </tr>

                        <tr>
                            <td class="classcenter"><p>支払済人数</p></td>
                             <?php
                            $grandTotal = 0;
                            for ($i = 1; $i < 8; $i++):
                                if ($i > 2) {
                                    ?>
                                    <td class="classright">
                                        <?php
                                        if (!empty($totalKyuPayment['standardHall'][$i]['totalKyu'])) {
                                            $grandTotal += $totalKyuPayment['standardHall'][$i]['totalKyu'];
                                            echo '<p><a href="/eiken/payment/paymentstatus/' . $totalKyuPayment['standardHall'][$i]['eikenScheduleId'] . '?eikenLevelId=' . $totalKyuPayment['standardHall'][$i]['eikenLevelId'] . '&testSite=0&pay=1' . '&backUrl=1">' . $totalKyuPayment['standardHall'][$i]['totalKyu'] . '</a></p>';
                                        }
                                        ?>
                                    </td>
                                    <?php
                                } else {
                                    echo '<td class="classright"></td>';
                                } endfor;
                            ?>
                            <td class="classright total-td <?php echo $grandTotal != 0 ? 'goukei' : ''; ?>" id="grand-total-standard-combini">
                                <?php echo $grandTotal != 0 ? '<p><a href="/eiken/payment/paymentstatus/' . $eikenScheduleId . '?testSite=0&pay=1' . '&backUrl=1">' . $grandTotal . '</a></p>' : '0'; ?>
                            </td>
                        </tr>
                        <!--  希望申込人数  -->
                        <tr>
                            <td class="classcenter"><p>申込人数</p></td>
                            <?php
                            if (!empty($applyEikenLevel['noOfExpectationStandard'])) {
                                $expectationData = $applyEikenLevel['noOfExpectationStandard'];
                            //} else if (!empty($applyEikenLevel['notMainHallSateLine'])) {
                            //    $expectationData = $applyEikenLevel['notMainHallSateLine'];
                            //} else if (!empty($applyEikenLevel['notMainHallPayment'])) {
                            //    $expectationData = $applyEikenLevel['notMainHallPayment'];
                            //} else if (!empty($applyEikenLevel['theMainHallSateLine'])) {
                            //    $expectationData = $applyEikenLevel['theMainHallSateLine'];
                            //} else if (!empty($applyEikenLevel['theMainHallPayment'])) {
                            //    $expectationData = $applyEikenLevel['theMainHallPayment'];
                            } else {
                                $expectationData = array(1 => array('id' => 1, 'total' => 0), 2 => array('id' => 2, 'total' => 0), 3 => array('id' => 3, 'total' => 0), 4 => array('id' => 4, 'total' => 0), 5 => array('id' => 5, 'total' => 0), 6 => array('id' => 6, 'total' => 0), 7 => array('id' => 7, 'total' => 0));
                            }
                            ?>
                            <?php if (!empty($expectationData)): ?>
                                <td class="classright"></td>
                                <td class="classright"></td>
                                <?php
                                $i = 5;
                                $j = 3;
                                foreach ($expectationData as $key => $detailLevel):
                                    ?>
                                    <?php
                                    $stand = isset($standPupilOfKyuTotal[$j]) ? $standPupilOfKyuTotal[$j] : 0;
                                    if (in_array($key, array(1, 2)) || $key == 'origin')
                                        continue;
                                    $disabledClass = '';
                                    if (in_array($j, $arrayHeader) || $isDisableStandard) {
                                        $disabledClass = " disabled='disabled' ";
                                    }
                                    ?>
                                    <td class="classright">
                                        <input <?php echo ($isOrgDiscount == 1 || $isDisableStandard) ? $disabledClass : ''; ?> name="txtExpectApplyNo<?php echo $i; ?>" id="txtExpectApplyNo<?php echo $i; ?>" value="<?php echo ($isOrgDiscount == 1 && in_array($j, $arrayHeader)) ? $stand : $detailLevel['total']; ?>" class="form-control standardHall-expect-number txtExpectApplyNo" onkeypress="return EIKEN_ORG.isNumber(event)" style="-ms-ime-mode: inactive;" type="tel" />
                                    </td>
                                    <?php
                                    $j++;
                                    $i--;
                                endforeach;
                                ?>
                            <?php else: ?>
                                <td class="classright"></td>
                                <td class="classright"></td>
                                <?php
                                for ($i = 5; $i >= 1; $i--):
                                    ?>

                                    <td class="classright">
                                        <input name="txtExpectApplyNo<?php echo $i; ?>" id="txtExpectApplyNo<?php echo $i; ?>" value="" class="form-control standardHall-expect-number txtExpectApplyNo" onkeypress="return EIKEN_ORG.isNumber(event)" style="-ms-ime-mode: inactive;" type="tel" />
                                    </td>
                                <?php endfor; ?>
                            <?php endif; ?>
                            <td class="classright total-td" id="grand-total-standard-expectation"></td>
                        </tr>
                        <!--  公費済用人  -->
                        <?php if ($isOrgDiscount == 1) { ?>
                            <tr>
                                <td colspan="2">
                                    公費適用人数
                                    <span tabindex="0" class="glyphicon glyphicon-info-sign"
                                          data-toggle="popover" data-trigger="hover"
                                          data-content="<?php echo $this->translate('toggleNote'); ?>"></span>
                                </td>
                                <?php
                                $totalPupilDiscount = 0;
                                for ($i = 1; $i < 8; $i++):
                                    $stand = isset($standPupilOfKyu[$i]) ? $standPupilOfKyu[$i] : 0;
                                    $main = isset($totalPupilMainHall[$i]) ? $totalPupilMainHall[$i] : 0;
                                    $totalPupilDiscount = $totalPupilDiscount + $stand + $main;
                                    ?>
                                    <td class="classright">
                                        <input name="totalDiscountKyu<?php echo $i; ?>" disabled id="totalDiscountKyu<?php echo $i; ?>" 
                                               value="<?php echo $stand + $main; ?>" 
                                               class="form-control standardHall-expect-number txtExpectApplyNo" onkeypress="return EIKEN_ORG.isNumber(event)" style="-ms-ime-mode: inactive;" type="tel" />
                                    </td>
                                <?php endfor; ?>
                                <td class="classright total-td" id="total-apply-expectation"><?php echo $totalPupilDiscount; ?></td>
                            </tr>
                        <?php } ?>
                        <!--total-->
                        <tr>
                            <td class="classcenter" colspan="2">
                                <p>申込人数合計</p>
                                <p class="font-size-12">（本会場の申込済人数と準会場の申込人数の合計）</p>
                            </td>
                            <td class="classright" id="total7" style="color: black;"></td>
                            <td class="classright" id="total6" style="color: black;"></td>
                            <td class="classright" id="total5" style="color: black;"></td>
                            <td class="classright" id="total4" style="color: black;"></td>
                            <td class="classright" id="total3" style="color: black;"></td>
                            <td class="classright" id="total2" style="color: black;"></td>
                            <td class="classright" id="total1" style="color: black;"></td>
                            <td class="classright total-td" id="grand-total"></td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="row">
            <?php
            if ($isOrgDiscount == 1) {
                echo $this->partial('partial/edit-number-total.phtml', array('isSemiMainVenue' => $isSemiMainVenue));
            }
            ?>
                <div class="heighthr"></div>
            </div>
            
            <!--=============================================================-->
            <div id="notTheMainHall">
                <p class="fl titledate">*準会場の場合、以下のフォームに情報をご記入ください。</p>
                <div class="fl date-start col-sm-12">
                    <div class="fl col2 ">
                        <div class="col-sm-1">
                            <label><strong>実施曜日 </strong></label><span class="reg-required">*</span>
                        </div>
                        <div class="col-sm-8">
                            <?php echo $this->formRow($form->get('date0')); ?>
                            <!--                            <label class="fix-w allowAll">金・土の両日にわたり実施</label>-->
                        </div>
                    </div>
                </div>
                <div class="fl end-start" id="date1">

                    <div class="fl col1 kyubetsu-createEiken">
                        <label>級別実施曜日</label><span class="reg-required">*</span> <label
                            class="font-mark padding-mark-1"> 一次試験の実施曜日を各級ごとに選択します </label>

                    </div>
                    <div class="fl col2">
                        <div class="row">
                            <div class="col-sm-2">
                            </div>
                            <div class="col-sm-3">
                                <table class="table table-bordered table-striped" width="100%">
                                    <thead>
                                        <tr>
                                            <th width="30%"><?php echo $this->translate('級'); ?></th>
                                            <th width="70%"><?php echo $this->translate('実施曜日'); ?></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td><?php echo $this->translate('2級'); ?></td>
                                            <td><?php echo $this->formRow($form->get('date1')); ?></td>
                                        </tr>
                                        <tr>
                                            <td><?php echo $this->translate('準2級'); ?></td>
                                            <td><?php echo $this->formRow($form->get('date2')); ?></td>
                                        </tr>
                                        <tr>
                                            <td><?php echo $this->translate('3級'); ?></td>
                                            <td><?php echo $this->formRow($form->get('date3')); ?></td>
                                        </tr>
                                        <tr>
                                            <td><?php echo $this->translate('4級'); ?></td>
                                            <td><?php echo $this->formRow($form->get('date4')); ?></td>
                                        </tr>
                                        <tr>
                                            <td><?php echo $this->translate('5級'); ?></td>
                                            <td><?php echo $this->formRow($form->get('date5')); ?></td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row totalcd r cdsuu-dantaimei">
                    <div class="col-sm-2">
                        <label>CDセット数</label><span class="reg-required">*</span>
                    </div>
                    <div class="col-sm-1">
                        <?php echo $this->formRow($form->get('totalcd')); ?>
                    </div>
                    <div class="col-sm-9">
                        <label class="font-mark padding-mark-1">
                            ※2セット以上を記入してください。　<a class="clred" href="javascript:void(0)" onclick="EIKEN_ORG.showPopupGuide('popup_guide_cd')">◎CDセット内容</a><br/>
                            ※合同実施の場合、CD数は合流先団体が入力したセット数をお送りします
                        </label>

                    </div>
                </div>
                <div class="row r cl-jishikbn">
                    <div class="col-sm-2">
                        <label>実施区分</label><span class="reg-required">*</span>
                    </div>
                    <div class="col-sm-6">
                        <label>
                            <input type="radio" name="locationType" class="padding_radio" id="location-type-single" value="0"
                                   <?php if (isset($eikenOrgDetail['locationType']) && $eikenOrgDetail['locationType'] == 0) echo 'checked="checked"'; ?>>単独

                        </label>
                        &nbsp;&nbsp;&nbsp; 
                        <label>
                            <input type="radio" name="locationType" class="classrd padding_radio" id="location-type-combination" value="1">合同
                        </label>
                    </div>

                    <div class="col-sm-4"></div>
                </div>
                <div class="top-mark-1">
                    <label class="font-mark">
                        ※他団体を吸収する場合は、吸収する団体名を入力してください。<br/>
                        ※他団体に合流する場合は、合流先団体番号を入力し団体名をご確認ください。
                    </label>

                </div>

                <div
                    class="row r cl-henkoflg goudou-dantaimei locationType1 location-type-combination">
                    <div class="col-sm-2">
                        <label>合同実施区分</label><span class="reg-required">*</span>
                    </div>
                    <div class="col-sm-10 styled-select">
                        <?php //echo $this->formRow($form->get('locationType1'));         ?>
                        <select name="locationType1" class="form-control"
                                id="locationType1">
                            <option value=""></option>
                            <option value="1">他団体を吸収する</option>
                            <option value="2">他団体に合流する</option>
                        </select>
                    </div>
                </div>
                <div class="row EikenOrgNo1 location-type-combination">
                    <div class="col-sm-2">
                        <label>合流する団体番号</label><span class="reg-required">*</span>
                    </div>
                    <div class="col-sm-2">
                        <?php echo $this->formRow($form->get('EikenOrgNo1')); ?>
                    </div>
                    <div class="col-sm-8">
                        <button type="button" id="btnGetOrgName" class="btn btnGetOrgName"
                                onclick="EIKEN_ORG.getOrgName();" style="font-size: 12px;">
                                    <?php echo $this->translate('団体名確認'); ?>
                        </button>
                    </div>
                </div>
                <div class="row EikenOrgNo1 location-type-combination">
                    <div class="col-sm-2">
                        <label>合流する団体名</label>
                    </div>
                    <div class="col-sm-5" id="EikenOrgNo123"></div>
                </div>
                <div class="row EikenOrgNo2 location-type-combination">
                    <div class="col-sm-2">
                        <label>吸収する団体名 </label><span class="reg-required">*</span>
                    </div>
                    <div class="col-sm-4">
                        <?php echo $this->formRow($form->get('EikenOrgNo2')); ?>
                    </div>
                    <div class="col-sm-6"></div>
                </div>
                <div class="heighthr"></div>
                <div class="row">
                    <div class="col-sm-4 refund-label">
                        <label><?php echo $this->translate('refundLabel'); ?></label>
                        <span class="reg-required">*</span>
                    </div>
                    <div class="col-sm-8 refund-status styled-select">
                        <?php echo $this->formRow($form->get('refundStatus')); ?>
                    </div>
                </div>
                <div>
                    <p><?php echo $this->translate('refundDescription'); ?></p>
                </div>
            </div>
        </div>
    </div>

    <div class="box-footer">
        <?php $isSubmited = (!empty($applyEikenLevel['applyEikenOrg']['status']) && $applyEikenLevel['applyEikenOrg']['status'] == 'SUBMITTED') ? true : false; ?>
        <div class="<?php echo $isSubmited ? 'col-sm-6' : 'col-sm-4'; ?>" style="text-align: left;">
            <button type="button" id="backToPolicy" class="btn btn-large-180 back-to-policy" onclick="EIKEN_ORG.backtoPolicy();">
                <i class="pencil-square"></i>責任者情報を編集する
            </button>
            <?php if ($isSubmited) { ?>
                <a class="btn btn-large-180" target="_blank" href="<?php
                echo $this->url('logs/default', array(
                    'controller' => 'apply-eiken',
                    'action' => 'index',
                        ), array(
                    'query' => array(
                        'ref' => 'apply',
                    ))
                );
                ?>">更新履歴</a>
               <?php } ?>
        </div>
        <div class="<?php echo $isSubmited ? 'col-sm-6' : 'col-sm-8'; ?>" style="text-align: right;">
            <?php
            if ((!empty($applyEikenLevel['applyEikenOrg']['status']) && $applyEikenLevel['applyEikenOrg']['status'] == 'DRAFT') || empty($applyEikenLevel['applyEikenOrg']['status'])):
                ?>
                <?php if (empty($applyEikenLevel['applyEikenOrg']['status'])): ?>
                    <button type="button" id="btnCancel"
                            class="btn btn-large-180" onclick="EIKEN_ORG.gotoHomePage();">
                                <?php echo $this->translate('キャンセル'); ?>
                    </button>
                <?php else: ?>
                    <button type="button" id="btnCancel"
                            class="btn btn-large-180" onclick="EIKEN_ORG.cancel(<?php echo $eikenScheduleId; ?>);">
                                <?php echo $this->translate('キャンセル'); ?>
                    </button>
                <?php endif; ?>
                <button type="button" id="btnCancelRegInfoModal"
                        class="btn btn-large-180" onclick="EIKEN_ORG.saveAsDraft();">
                    <i class="file-archive-o"></i><?php echo $this->translate('ドラフト保存'); ?>
                </button>
            <?php else: ?>
                <button type="button" id="btnCancel"
                        class="btn btn-large-180" onclick="EIKEN_ORG.cancel(<?php echo $eikenScheduleId; ?>);">
                            <?php echo $this->translate('キャンセル'); ?>
                </button>
            <?php endif; ?>
            <button type="button" id="btnSubmitToEiken"
                    class="btn btn-large-180 btn-red"
                    onclick="EIKEN_ORG.submitToEiken();">
                <i class="fa-download-w"></i><?php echo $this->translate('入力内容確認'); ?></button>
        </div>
    </div>
</div>
<input name="totalDiscountMain" id="totalDiscountMain" value="<?php echo $totalPupilMainHall ? htmlentities(json_encode($totalPupilMainHall)) : ''; ?>" type="hidden" />
<input name="renderStand" id="renderStand" value="<?php echo htmlentities($arrayRender); ?>" type="hidden" />
<input name="isOrgDiscount" id="isOrgDiscount" value="<?php echo $isOrgDiscount; ?>" type="hidden" />
<?php
if ($totalPupilMainHall) {
    foreach ($totalPupilMainHall as $key => $value) {
        ?>
        <input name="mainPupilDiscountKuy<?php echo $key; ?>" id="mainPupilDiscountKuy<?php echo $key; ?>" value="<?php echo $value ? $value : 0; ?>" type="hidden" />
        <?php
    }
}
for($i = 1 ; $i < 8 ;$i++){
    ?>
    <input name="standPupilDiscountKuy<?php echo $i; ?>" id="standPupilDiscountKuy<?php echo $i; ?>" value="<?php echo isset($standPupilOfKyu[$i]) ? $standPupilOfKyu[$i] : 0; ?>" type="hidden" />
    <?php 
}
?>
<?php echo $this->form()->closeTag(); ?>

<!-- MODAL -->
<div id="popup_guide_cd" data-backdrop="static" class="modal fade" role="dialog">
    <form method="post">
        <div class="modal-dialog rcm-modal">
            <div class="modal-content rcm-boder-radius-0">
                <div class="box-header"> <?php echo $this->translate('CDセット数'); ?> </div>
                <div class="modal-body rcm-modal-body">
                    <div class="row padding-left-rcm-5">
                        <div>
                            <label class="clred"><strong><?php echo $this->translate('リスニングCDは3枚で1セットです'); ?></strong></label>
                        </div>
                        <table class="table table-bordered rcm-table ver-center">
                            <tr><td class="text-center">CD①</td><td>受験者心得／2級</td></tr>
                            <tr><td class="text-center">CD②</td><td>受験者心得／準2級／3級</td></tr>
                            <tr><td class="text-center">CD③</td><td>受験者心得／4級／5級</td></tr>
                        </table>
                    </div>
                    <p>【準2級／3級】【4級／5級】は1枚のCDに収録されていますのでご注意ください</p>
                </div>

                <div class="modal-footer ptb20">
                    <a id="btnUpdateLevel" data-dismiss="modal" class="btn btn-large-180 btn-red rcm-margin-right-30">
                        OK
                    </a>
                </div>
            </div>
        </div>
    </form>
</div>
<script>
    $(function () {
        $('[data-toggle="popover"]').popover();
    })
</script>