<?php
$this->headLink()->prependStylesheet($this->basePath('css/goalsetting/graduationgoalsetting.css'));
$isViewer = \Dantai\PublicSession::isViewerRole();
?>
<!--[if lte IE 8]>
        <link rel="stylesheet" type="text/css" href="/css/goalsetting/ie8-graduationgoalsetting.css" />
<![endif]-->
<div>
	<div class="graduationgoalsetting">
        <?php

        $action = $this->url('goal-setting/default', array(
            'controller' => 'graduationgoalsetting',
            'action' => 'graduationgoalsearch'
        ));
        $form->setAttribute('action', $action);
        ?>
        <?php echo $this->form()->openTag($form); ?>
        <input type="hidden" name="edit" id="editAction"
			value="<?php  echo isset($searchbox['edit'])? $searchbox['edit']:0;?>" />
		<div class="box">
			<div class="box-header" data-toggle="collapse" data-target="#search-box">
				<div class="search-header  sorting-field">
					<i class="search-chevron-down"></i><b> <?php echo $this->translate('検索条件'); ?></b>
				</div>

			</div>
			<div id="search-box" class="box-search collapse in" aria-expanded="true">
				<div style="display: none" class="pull-left ie-width-1">
					<label class="control-label"><?php echo $this->translate('目標設定'); ?><span
						class="star">*</span></label> <label class="text-normal"><input
						type="radio" name="rdGoalSetting" id="rdGoalSetting" tabindex="1"
						class="radio-box" style="margin-left: -4px;" value="0"
						<?php if(empty($searchbox['rdGoalSetting'])){?> checked <?php }?> /><span
						class="text-lbl">卒業時目標</span></label> <label class="text-normal"><input
						type="radio" name="rdGoalSetting" id="rdGoalSetting2" tabindex="2"
						class="radio-box" style="margin-left: 22px;" value="1"
						<?php if($searchbox['rdGoalSetting']==1){?> checked <?php }?> /><span
						class="text-lbl">年度目標</span></label>
				</div>
				<div class="pull-left lblSchoolYear">
					<label class="control-label"><?php echo $this->translate('年度'); ?></label>
				</div>
				<div class="pull-left styled-select form-control-margin-top">
                     <?php echo $this->formrow($form->get('ddbYear')); ?>
                </div>
				<div
					class="pull-right form-control-margin-top box-search-button-group">
					<a tabindex="4" href="javascript:void(0)"
						onclick="GRADUATIONGOALSETTING.clearAction();"
						class="btn btn-small-100 margin-right-20">クリア</a> <a tabindex="5"
						class="btn btn-small-180" href="javascript:void(0);"
						id="btnSearch"
						onclick="GRADUATIONGOALSETTING.searchAllAction()"><i
						class="fa-search"></i> 検索</a>
				</div>
			</div>
		</div>
        <?php echo $this->form()->closeTag(); ?>
        
        <div class="box">
			<div class="box-header">
				<div class="search-header">
				    <b id="show-title-name">年度目標詳細</b>
				</div>
			</div>
			<div class="box-search description-page">
			 <div class="col-sm-12" id="description-page-show">
            <label class="font-mark"> 
                                    目標を設定します。<br/>
                                    目標の設定方法には２種類あり、「卒業時」と「年度目標」を選択できます。<br/>
               <i class="text-parenthesis-jp">「卒業時」は、中学３年時、高校３年時の取得目標を各学年ごとに設定します。</i><br />
               <i class="text-parenthesis-jp"> 「年度目標」は、各学年ごとに年次の取得目標を設定します。</i><br />
                                    まず、設定したい種類について検索条件から選択して「検索」ボタンを押してください。<br />
                                    次に「編集」ボタンを押して、取得目標を入力してください。    
            </label>
            </div>
            <div class="description">
                <p>
                    試験結果情報には受験生による入力ミスなども含まれるため、以下の統計情報には不正確なデータも含まれることがあります。<br>
                    より正確な統計情報を算出するためには各試験結果データと名簿データの間の突合を行ってください。
                </p>
            </div>
            <div class="col-sm-12" id="description-page-edit-r1">
            <label class="font-mark"> 
                                   卒業時の目標を設定します。<br />
                                    各学年ごとに卒業時に何級を何パーセント取得したいのかを設定します。<br />
                                    設定を終えたら、「保存」ボタンを押してください。<br />
            </label>
            </div>
            <div class="col-sm-12" id="description-page-edit-r2">
            <label class="font-mark"> 
                                 各学年ごとに今年度に何級を何パーセント取得したいのかを設定します。<br />
                                設定を終えたら、「保存」ボタンを押してください。
            </label>
            </div>
			</div>
		</div>
        <!-- default visible-->
        <?php
        $formAcquisitionRateEdit->setAttribute('action', $action);
        echo $this->form()->openTag($formAcquisitionRateEdit);
        ?>
             <input type="hidden" name="edit" id="editfrom" value="1" />
		<input type="hidden" name="ddbYear" id="ddbYearfrom"
			value="<?php echo $searchbox['ddbYear']?>" /> <input type="hidden"
			name="rdGoalSetting" id="rdGoalSettingfrom"
			value="<?php echo $searchbox['rdGoalSetting']?>" />
         <?php echo $this->form()->closeTag(); ?>
        <?php $actionUpdateGraduationGoal = $this->url('goal-setting/default', array('controller' => 'graduationgoalsetting', 'action' => 'updategraduationgoal'));?>
        <form name="updateGraduationGoal" id="updateGraduationGoal"
			action="<?php echo $actionUpdateGraduationGoal ;?>" method="post">
            <input type="hidden" name="tokenGra" id="tokenGra" value="<?php echo $token;?>" />
			<div id="graduation-time-target" class="row remove-margin-bottom" style="display: none">
				<div class="col-sm-6 pull-left">
					<div class="box">
						<div class="box-header">
                        <?php  echo $this->translate('取得率（目標）：卒業時'); ?>
                    </div>
						<div class="box-body">
							<table class="table table-bordered ">
								<thead style="display: table-header-group;">
									<tr>
										<th width="80" class="text-center">卒業年度</th>
										<th>学年</th>
                                                                                <th class="col-goal-level" width="80">目標級</th>
										<th class="col-goal-rate" width="80">取得率</th>
									</tr>
								</thead>
								<tbody id="graduationtargets"
									class="graduationtargets-Yearlytargets">
                             <!-- show data by ajax-->
                            </tbody>
							</table>
						</div>
					</div>
				</div>
				<div class="col-sm-6 pull-right">
					<div class="box">
						<div class="box-header">
                        <?php echo $this->translate('取得率（実績）：卒業時'); ?>
                    </div>
						<div class="box-body">
							<table class="table table-bordered ">
								<thead style="display: table-header-group;">
									<tr>
										<th width="80">卒業年度</th>
										<th width="80">目標級</th>
										<th>取得率（目標)</th>
										<th>取得率（実績）</th>
									</tr>
								</thead>
								<tbody id="Historicgoal">
                                <!-- show data by ajax-->
                            </tbody>
							</table>
						</div>
					</div>
				</div>
			</div>
			<!-- visible when 年度目標 selected -->
		</form>
		<form name="updateYearGoal" id="updateYearGoal"
			action="<?php echo $actionUpdateGraduationGoal ;?>" method="post">
			<input type="hidden" name="tokenYear" id="tokenYear" value="<?php echo $token;?>" />
			<div id="annual-target" class="annual-target row remove-margin-bottom"  style="display:none">
				<div class="col-sm-6 pull-left">
					<div class="box">
						<div class="box-header">
                        <?php echo $this->translate('取得率（目標）：'.!empty($searchbox['ddbYear'])?((int)$searchbox['ddbYear']):''.'年度'); ?>
                    </div>
						<div class="box-body">
							<table class="table table-bordered ">
								<thead style="display: table-header-group;">
									<tr>
										<th>学年</th>
										<th width="108">目標級</th>
										<th width="108">取得率</th>
									</tr>
								</thead>
								<tbody id="Yearlytargets"
									class="graduationtargets-Yearlytargets">
                               <!-- show data by ajax-->
                            </tbody>
							</table>
						</div>
					</div>
				</div>
				<div class="col-sm-6 pull-right">
					<div class="box">
						<div class="box-header">
                        <?php echo $this->translate('取得率（実績）：'. !empty($searchbox['ddbYear'])?((int)$searchbox['ddbYear'] -1):''.'年度'); ?>
                    </div>
						<div class="box-body">
							<table class="table table-bordered ">
								<thead style="display: table-header-group;">
									<tr>
										<th>学年</th>
										<th width="80">目標級</th>
										<th width="80">取得率（目標)</th>
										<?php if(\Dantai\PublicSession::isHighSchool()) { ?>
										<th width="85">取得率（実績）</th>
										<?php } ?>
									</tr>
								</thead>

								<tbody id="HistoricgoalByYear">
                                 <!-- show data by ajax-->
                            </tbody>
							</table>
						</div>
					</div>
				</div>
			</div>
		</form>
		<!-- box 2-->
		<div class="box">
			<div class="box-header">
                <?php echo $this->translate('全国・都道府県の取得率(級別)'); ?>
            </div>
			<div class="box-body">
                <?php  $formNational->setAttribute('action', $action);?>
                <?php echo $this->form()->openTag($formNational); ?>
                <input id="yearsearch" name="yearsearch"
					value="<?php echo $searchbox['ddbYear']?>" type="hidden" />
				<div class="table-header-filter">
					<div class="pull-left">
						<label class="control-label  ie-width-2"><?php echo $this->translate('団体区分'); ?></label>
					</div>
					<div class="pull-left styled-select form-control-margin-top">
						<?php if (\Dantai\PublicSession::isHighSchool()) {
							echo $this->formRow($formNational->get('ddbOrganization')->setAttribute('onChange', 'GRADUATIONGOALSETTING.loadListSchoolYear();'));
						}
						else {
							echo $this->formRow(
								$formNational->get('ddbOrganization')
									->setAttributes(array(
										'disabled' => 'disabled'
									)));
						} ?>
					</div>
					<div class="pull-left" style="margin-left: 55px">
						<label class="control-label  ie-width-2"><?php echo $this->translate('都道府県'); ?></label>
					</div>
					<div class="pull-left styled-select form-control-margin-top">
<!--						--><?php //echo $cityName; ?>
                        <?php echo $this->formRow($formNational->get('ddbPrefectures')); ?>
                    </div>
					<div class="pull-left" style="margin-left: 50px">
						<label class="control-label"><?php echo $this->translate('学年'); ?></label>
					</div>
					<div class="pull-left styled-select form-control-margin-top">
                        <?php echo $this->formRow($formNational->get('ddbSchoolYear')); ?>
                    </div>
					<div
						class="pull-left form-control-margin-top box-search-button-group-2">
						<a tabindex="9"
							onclick="GRADUATIONGOALSETTING.searchCityGoalAction();"
							href="javascript:void(0)"
							class="btn btn-small-100 margin-right-20"><i class="fa-search"></i>検索</a>
					</div>
				</div>
                <?php echo $this->form()->closeTag(); ?>
                <table class="table table-bordered  tbl-national">
                <?php $class ='hiddenClass showHide'; if(!empty($data['graduationStatistics'])){$class = 'activeClass showHide';}?>
                    <thead>
				<!--  <thead class="<?php //echo $class;?>"> -->
				<tr>
							<th>年度</th>
							<th width="100" class="text-left">都道府県</th>
							<th width="100">1級</th>
							<th width="100">準1級</th>
							<th width="100">2級</th>
							<th width="100">準2級</th>
							<th width="100">3級</th>
							<th width="100">4級</th>
							<th width="100">5級</th>
						</tr>
					</thead>

					<tbody id="loadDataIncity">
                    <?php
                    if (! empty($data['graduationStatistics'])) {
                        foreach ($data['graduationStatistics'] as $key => $item) {
                            if (! empty($item['city'])) {
                                $cityPassRate = $item['city'];
                            }
                            if (! empty($item['nation'])) {
                                $nationwidePassRate = $item['nation'];
                            }
                            ?>
                        <tr>
							<td rowspan="2" class=""><?php echo $key;?></td>
							<td class="text-center"><?php if(!empty($cityPassRate['cityName']))  echo $this->escapehtml($cityPassRate['cityName']);?></td>
							<td class="text-center"><?php if(isset($cityPassRate[1]))echo round($cityPassRate[1]).'%'?></td>
							<td class="text-center"><?php if(isset($cityPassRate[2])) echo round($cityPassRate[2]).'%'?></td>
							<td class="text-center"><?php if(isset($cityPassRate[3])) echo round($cityPassRate[3]).'%'?></td>
							<td class="text-center"><?php if(isset($cityPassRate[4])) echo round($cityPassRate[4]).'%'?></td>
							<td class="text-center"><?php if(isset($cityPassRate[5])) echo round($cityPassRate[5]).'%'?></td>
							<td class="text-center"><?php if(isset($cityPassRate[6])) echo round($cityPassRate[6]).'%'?></td>
							<td class="text-center"><?php if(isset($cityPassRate[7])) echo round($cityPassRate[7]).'%'?></td>
						</tr>
						<tr>
							<td class="text-center">全国</td>
							<td class="text-center"><?php if(isset($nationwidePassRate[1])) echo round($nationwidePassRate[1]).'%'?></td>
							<td class="text-center"><?php if(isset($nationwidePassRate[2]))  echo round($nationwidePassRate[2]).'%'?></td>
							<td class="text-center"><?php if(isset($nationwidePassRate[3])) echo round($nationwidePassRate[3]).'%'?></td>
							<td class="text-center"><?php if(isset($nationwidePassRate[4])) echo round($nationwidePassRate[4]).'%'?></td>
							<td class="text-center"><?php if(isset($nationwidePassRate[5])) echo round($nationwidePassRate[5]).'%'?></td>
							<td class="text-center"><?php if(isset($nationwidePassRate[6])) echo round($nationwidePassRate[6]).'%'?></td>
							<td class="text-center"><?php if(isset($nationwidePassRate[7])) echo round($nationwidePassRate[7]).'%'?></td>
						</tr>
                     <?php
                        }
                    } else {
                        ?>
                      <tr class="messError">
							<td colspan="9">検索条件に一致するデータがありません。</td>
						</tr>
                    <?php }?>
                    </tbody>
				</table>
			</div>
		</div>
		<div class="box">
			<div class="box-body">
				<div class="pull-right">
					<button id="btn-edit-setting" <?php echo $isViewer ? 'disabled' : '' ?>
					   onclick="GRADUATIONGOALSETTING.editModeAction()"
					   tabindex="14" class="btn btn-large-180 margin-right-btn btn-edit-setting">
						<i class="pencil-square"></i> 編集
					</button>
					<button style="display: none" id="btn-cancel-edit" onclick="GRADUATIONGOALSETTING.cancelEditAction()"
					   class="btn btn-large-180 margin-right-5 btn-cancel-edit" tabindex="27">
						キャンセル
					</button>
					<button style="display: none"
					   id="btn-save-edit" onclick="GRADUATIONGOALSETTING.saveEdit();"
					   class="btn btn-red btn-large-180" id="submitform" tabindex="28">
						<i class="fa-download-w"></i>保存
					</button>
				</div>
			</div>
		</div>
	</div>
</div>
<?php
$this->headScript()->prependFile($this->basePath('js/goal-setting/graduationgoalsetting.js'));
?>
<script type="text/javascript">
	var isHighSchool = "<?php echo \Dantai\PublicSession::isHighSchool(); ?>";
    var jsMessages = <?php echo $jsMessages;?>;
    $(document).ready(function () {
                GRADUATIONGOALSETTING.searchCityGoalAction();
		GRADUATIONGOALSETTING.init();
	});
</script>