<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Logs\Module'                        => __DIR__ . '/Module.php',
    'Logs\Controller\ActivityController' => __DIR__ . '/src/Logs/Controller/ActivityController.php',
);
