<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'History\Module'                        => __DIR__ . '/Module.php',
    'History\Controller\EikenHistoryController' => __DIR__ . '/src/History/Controller/EikenHistoryController.php',
);
