<?php if ($type == 'answer' && $items->totalMondai) { ?>
    <div class="answerSituation">
        <table id="table12" class="some tb-striped-c-e6">
            <thead>
            <tr>
                <td colspan="<?php echo max($items->totalMondai[0] + $items->totalMondai[1], $items->totalMondai[2] + $items->totalMondai[6]) + 1 ?>">
                    筆記
                </td>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>大問番号</td>
                <td colspan="<?php echo $items->totalMondai[0]; ?>">【 1 】</td>
                <td colspan="<?php echo $items->totalMondai[1]; ?>">【 2 】</td>
            </tr>
            <tr>
                <td>問題番号</td>
                <?php for ($i = 1; $i <= $items->totalMondai[0] + $items->totalMondai[1]; $i++) { ?>
                    <td><?php echo '(' . $i . ')'; ?></td>
                <?php } ?>
            </tr>
            <tr>
                <td>正解番号</td>
                <?php for ($i = 0; $i < $items->totalMondai[0] + $items->totalMondai[1]; $i++) { ?>
                    <td><?php echo $items->getAnswerNo[$i]; ?></td>
                <?php } ?>
            </tr>
            <tr>
                <td>正誤</td>
                <?php for ($i = 0; $i < $items->totalMondai[0] + $items->totalMondai[1]; $i++) { ?>
                    <td><strong><?php echo $items->getTrueFalse[$i]; ?></strong></td>
                <?php } ?>
            </tr>
            <tr>
                <td>大問番号</td>
                <td colspan="<?php echo $items->totalMondai[2] ?>">【 3 】</td>
                <td colspan="<?php echo $items->totalMondai[3] ?>">【 4 】</td>
            </tr>
            <tr>
                <td>問題番号</td>
                <?php for ($i = $items->totalMondai[0] + $items->totalMondai[1] + 1; $i <= $items->part1; $i++) { ?>
                    <td><?php echo '(' . $i . ')'; ?></td>
                <?php } ?>
            </tr>
            <tr>
                <td>正解番号</td>
                <?php for ($i = $items->totalMondai[0] + $items->totalMondai[1]; $i < $items->part1; $i++) { ?>
                    <td><?php echo $items->getAnswerNo[$i]; ?></td>
                <?php } ?>
            </tr>
            <tr>
                <td>正誤</td>
                <?php for ($i = $items->totalMondai[0] + $items->totalMondai[1]; $i < $items->part1; $i++) { ?>
                    <td><strong><?php echo $items->getTrueFalse[$i]; ?></strong></td>
                <?php } ?>
            </tr>
            </tbody>
        </table>
        <div class="clear"></div>
    </div>

    <hr/>
    <table id="table13" class="some tb-striped-c-e6 w-33">
        <thead>
        <tr>
            <td colspan="<?php echo $items->part2 + 2; ?>">リスニング</td>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>大問番号</td>
            <td colspan="<?php echo $items->totalMondai[4] ?>"> 第1部</td>
            <td colspan="<?php echo $items->totalMondai[5] ?>"> 第2部</td>
            <td colspan="<?php echo $items->totalMondai[6]; ?>"> 第3部</td>
        </tr>
        <tr>
            <td>問題番号</td>
            <?php for ($i = 1; $i <= $items->part2; $i++) { ?>
                <td><?php echo '(' . $i . ')'; ?></td>
            <?php } ?>
        </tr>
        <tr>
            <td>正解番号</td>
            <?php for ($i = $items->part1; $i < $items->part2 + $items->part1; $i++) { ?>
                <td><?php echo $items->getAnswerNo[$i]; ?></td>
            <?php } ?>
        </tr>
        <tr>
            <td>正誤</td>
            <?php for ($i = $items->part1; $i < $items->part2 + $items->part1; $i++) { ?>
                <td><strong><?php echo $items->getTrueFalse[$i]; ?></strong></td>
            <?php } ?>
        </tbody>
    </table>
    <div class="clear"></div>
    <div class="bottom-description">大問4(ライティング	問題)の模範解答は、英検ウェブサイトの解答速報をご覧下さい。</div>
<?php } ?>
<?php if ($type == 'part' && $items->totalMondai) { ?>
    <table id="table14" class="table some tb-striped-r-f2 table-writing">
        <thead>
        <tr>
            <?php foreach ($items->getTitleTableEiken['Title8'] as $key => $val) { ?>
                <td <?php echo ($key == 2 ? 'colspan="2"' : '');?> ><?php echo $val; ?></td>
            <?php } ?>
        </tr>
        </thead>
        <tbody>
        <tr class="first">
            <td rowspan="4"><?php echo $items->getSkill[1][1]; ?></td>
            <td colspan="2"><span>大問1</span><br>短文の語句空所補充</td>
            <td><?php echo $items->valueMondai[0]; ?></td>
            <td><?php echo $items->getPurpose[1][1][$items->getEikenLevelId()]; ?></td>
            <td><?php echo ltrim(str_replace('◆', '<br>◆', $items->getStydyAdvice1()),'<br>'); ?></td>
        </tr>
        <tr class="event">
            <td colspan="2"><span>大問2</span><br>会話文の文空所補充</td>
            <td><?php echo $items->valueMondai[1]; ?></td>
            <td class="text-justify"><?php echo $items->getPurpose[2][1][$items->getEikenLevelId()]; ?></td>
            <td rowspan="3"><?php echo ltrim(str_replace('◆', '<br>◆', $items->getStydyAdvice2()),'<br>'); ?></td>
        </tr>
        <tr class="event">
            <td colspan="2"><span>大問3</span><br>長文の語句空所補充</td>
            <td><?php echo $items->valueMondai[2]; ?></td>
            <td><?php echo $items->getPurpose[2][2][$items->getEikenLevelId()]; ?></td>
        </tr>
        <tr class="event">
            <td colspan="2"><span>大問4</span><br>長文の内容一致</td>
            <td><?php echo $items->valueMondai[3]; ?></td>
            <td><?php echo $items->getPurpose[2][3][$items->getEikenLevelId()]; ?></td>
        </tr>
        <tr class="first">
            <td rowspan="3"><?php echo $items->getSkill[1][2]; ?>
            <td colspan="2"><span>第1部</span><br>会話の応答文選択</td>
            <td><?php echo $items->valueMondai[4]; ?></td>
            <td><?php echo $items->getPurpose[3][1][$items->getEikenLevelId()]; ?></td>
            <td rowspan="3"><?php echo ltrim(str_replace('◆', '<br>◆', $items->getStydyAdvice3()),'<br>'); ?></td>
        </tr>
        <tr class="event">
            <td colspan="2"><span>第2部</span><br>会話の内容一致選択</td>
            <td><?php echo $items->valueMondai[5]; ?></td>
            <td><?php echo $items->getPurpose[3][2][$items->getEikenLevelId()]; ?></td>
        </tr>
        <tr class="event">
            <td colspan="2"><span>第3部</span><br>文の内容一致選択</td>
            <td><?php echo $items->valueMondai[6]; ?></td>
            <td><?php echo $items->getPurpose[3][3][$items->getEikenLevelId()]; ?></td>
        </tr>
        
        
        <tr class="first last-row">
            <td rowspan="4"><?php echo $items->getSkill[1][3] ?>※</td>
            <td rowspan="4"><span>大問5</span><br>英作文</td>
            <td><span><?php echo $this->translate('SkillMondai4')[1]; ?></span></td>
            <td class="text-center"><?php echo $items->valueMondai[7]; ?></td>
            <td><?php echo $items->getPurpose[4][1][$items->getEikenLevelId()][1]; ?></td>
            <td rowspan="4"><?php echo ltrim(str_replace('◆', '<br>◆', $items->getStydyAdvice4()),'<br>'); ?></td>
        </tr>
        <tr class="event">
            <td><span><?php echo $this->translate('SkillMondai4')[2]; ?></span></td>
            <td><?php echo $items->valueMondai[8]; ?></td>
            <td><?php echo $items->getPurpose[4][1][$items->getEikenLevelId()][2]; ?></td>
        </tr>
        <tr class="event">
            <td><span><?php echo $this->translate('SkillMondai4')[3]; ?></span></td>
            <td><?php echo $items->valueMondai[9]; ?></td>
            <td><?php echo $items->getPurpose[4][1][$items->getEikenLevelId()][3]; ?></td>
        </tr>
        <tr class="event">
            <td><span><?php echo $this->translate('SkillMondai4')[4]; ?></span></td>
            <td><?php echo $items->valueMondai[10]; ?></td>
            <td><?php echo $items->getPurpose[4][1][$items->getEikenLevelId()][4]; ?></td>
        </tr>
        </tbody>
    </table>
    <div style="clear: both"></div>
    <div class="bottom-description">※Writingでは、観点別の得点を表示しています。</div>
    </table>
<?php } ?>
    <style>
        .per-achi .b4.kyu1 .grid-box-chart, .per-achi .b4.kyu2 .grid-box-chart, .per-achi .b4.kyu3 .grid-box-chart, .per-achi .b4.kyu4 .grid-box-chart, .per-achi .b4.kyu5 .grid-box-chart{ height: 138px;}
        .per-achi .b4.kyu1 .grid-box-chart .col-1, .per-achi .b4.kyu2 .grid-box-chart .col-1, .per-achi .b4.kyu3 .grid-box-chart .col-1, .per-achi .b4.kyu4 .grid-box-chart .col-1 , .per-achi .b4.kyu5 .grid-box-chart .col-1 { height: 138px;}
    </style>
