<?php
if (!$isMobile) {
    $this->headLink()->prependStylesheet($this->basePath('css/forgot-password.css'));
}
else {
    $this->headLink()->prependStylesheet($this->basePath('css/forgot-password.mobile.css'));
}
?>
<div class="box" id="forgotpass">
    <div class="box-header">
        <div class="text-header">パスワードをお忘れの方</div>
    </div>
    <div class="box-body">
        <div class="row col-md-12">
            <span class="col-md-12">メールアドレスと生年月日を入力してください。<br>英ナビシステムがIDとパスワードをあなたのメールアドレスに送信します。</span>
        </div>
        <div class="col-md-12 row mt-reset mt15">
            <div class="col-md-4"><strong><span>メールアドレス</span><span class="red">*</span></strong></div>
            <div class="col-md-8">
                <input autocomplete="off" class="form-control" type="text" name="email" id="email" value="">
            </div>
        </div>
        <div class="col-md-12 row mt-reset mt15">
            <div class="col-md-4"><strong><span>生年月日</span><span class="red">*</span></strong></div>
            <div class="col-md-8">
                <div class="pull-left boxYear styled-select">
                    <select autocomplete="off" name="year" id="year" class="pull-left mw140">
                        <?php $dateYear = date('Y');
                        $heisei = $dateYear - 1988;
                        $showa = 63;
                        $taisho = 14;
                        for ($i = $dateYear; $i >= $dateYear - 100; $i--) {
                            $japaneseEraCalendar = '(平成' . ($heisei--) . ')';
                            if ($i < 1989) {
                                $japaneseEraCalendar = '(昭和' . ($showa--) . ')';
                            }
                            if ($i < 1926) {
                                $japaneseEraCalendar = '(大正' . ($taisho--) . ')';
                            }
                            ?>
                            <option value="<?php echo $i; ?>"><?php echo $i . $japaneseEraCalendar; ?></option>
                        <?php } ?>
                    </select>
                    <span class="pull-left">年</span>
                </div>
                <div class="styled-select pull-left boxDate">
                    <select autocomplete="off" name="month" id="month" class="pull-left mw70 ">
                        <option selected value=""></option>
                        <?php for ($i = 1; $i < 13; $i++) { ?>
                            <option value="<?php echo $i < 10 ? '0' . $i : $i; ?>"><?php echo $i < 10 ? '0' . $i : $i; ?></option>
                        <?php } ?>
                    </select>
                    <span class="pull-left">月</span>
                </div>
                <div class="styled-select pull-left boxDate">
                    <select autocomplete="off" name="day" id="day" class="pull-left mw70 ">
                        <option selected value=""></option>
                    </select>
                    <span class="pull-left">日</span>
                </div>
            </div>
        </div>
    </div>
    <div class="box-footer clearfix">
        <div class="col-md-12 row text-right">
            <a id="btnCancel" class="btn btn-large-180" href="../">キャンセル</a>
            <button type="button" id="btnSend" class="btn btn-red btn-large-180"><i class="sign-in"></i>送信する</button>
        </div>
    </div>
</div>
<?php $this->headScript()->appendFile($this->basePath('js/einavi/forgot-password.js')); ?>
<script>
    var messages = <?php echo isset($messages) ? $messages : 0 ?>;
    FORGOT_PASSWORD.init();
</script>