<!-- Styles -->
<?php $this->headLink ()->appendStylesheet ( $this->basePath ( 'css/home-static.css' ) )?>
<!-- Scripts -->

<div class="box eiken-policy">
	<div class="box-header">
		<strong>使い方 </strong>
	</div>
</div>

<div class="box col-md-12">
	<div class="col-md-4">
    	<div class="box-header border-none">
    		<strong>各種検定申込</strong>
    	</div>
    	
    	<div class="navigator padl20">
            <ul class="padl20">
                <li><a href="javascript:%20void(0);"><span>英検IBA申込</span></a>
                    <ul class="padl20">
                        <li><a href="javascript:%20void(0);"><span>IBA申込登録</span></a></li>
                    </ul>
                </li>
                <li><a href="javascript:%20void(0);"><span>英検申込</span></a>
                    <ul class="padl20">
                        <li><a href="javascript:%20void(0);"><span>個別支払</span></a></li>
                        <li><a href="javascript:%20void(0);"><span>案内状作成</span></a>
                            <ul class="padl20">
                                <li><a href="javascript:%20void(0);"><span>受験案内状設定</span></a></li>
                                <li><a href="javascript:%20void(0);"><span>目標級設定</span></a></li>
                                <li><a href="javascript:%20void(0);"><span>受験案内状印刷</span></a></li>
                            </ul>
                        </li>
                        <li><a href="javascript:%20void(0);"><span>団体支払</span></a>
                            <ul class="padl20">
                                <li><a href="javascript:%20void(0);"><span>案内状作成</span></a></li>
                                <li><a href="javascript:%20void(0);"><span>申込登録</span></a></li>
                            </ul>
                        </li>
                    </ul>
                </li>
            </ul>
    	</div>
	</div>
	
	<div class="col-md-4">
		<div class="box-header border-none">
			<strong>成績分析</strong>
		</div>
		
		<div class="navigator padr5 padl20">
		   <ul class="padl20">
			   <li><a href="javascript:%20void(0);"><span>英検級取得率：目標対実績</span><br><span>（級別）</span></a></li>
			   <li><a href="javascript:%20void(0);"><span>英検級取得率：目標対実績</span><br><span>（年度比較）</span></a></li>
			   <li><a href="javascript:%20void(0);"><span>CSEスコア推移表</span></a></li>
		   </ul>
		</div>
		
		<div class="box-header border-none">
			<strong>申込履歴・結果照会</strong>
		</div>
		
		<div class="navigator padl20">
            <ul class="padl20">
                <li><a href="javascript:%20void(0);"><span>申込履歴照会</span></a></li>
                <li><a href="javascript:%20void(0);"><span>試験結果照会</span></a>
                    <ul class="padl20">
                        <li><a href="javascript:%20void(0);"><span>英検履歴</span></a></li>
                        <li><a href="javascript:%20void(0);"><span>IBA履歴</span></a></li>
                    </ul> 
                </li>
            </ul>
		</div>
		
		<div class="box-header border-none">
			<strong>学習進捗管理</strong>
		</div>
		
		<div class="navigator padl20">
		   <ul class="padl20">
			   <li><a href="javascript:%20void(0);"><span>スタギア学習進捗照会</span></a></li>
		   </ul>
		</div>
	</div>
	
	<div class="col-md-4">
		<div class="box-header border-none">
			<strong>団体情報管理</strong>
		</div>
		
		<div class="navigator padl20">
		   <ul class="padl20">
			   <li><a href="javascript:%20void(0);"><span>学年管理</span></a></li>
			   <li><a href="javascript:%20void(0);"><span>クラス管理</span></a></li>
			   <li><a href="javascript:%20void(0);"><span>生徒管理</span></a></li>
			   <li><a href="javascript:%20void(0);"><span>団体情報</span></a></li>
			   <li><a href="javascript:%20void(0);"><span>ユーザ管理</span></a></li>
			   <li><a href="javascript:%20void(0);"><span>基準級</span></a></li>
		   </ul>
		</div>
		
		<div class="box-header border-none">
			<strong>目標設定・学習計画</strong>
		</div>
		
		<div class="navigator padr5 padl20">
            <ul class="padl20">
                <li><a href="javascript:%20void(0);"><span>目標設定</span></a>
                    <ul class="padl20">
                        <li><a href="javascript:%20void(0);"><span>目標設定</span></a></li>
                        <li><a href="javascript:%20void(0);"><span>全国・都道府県別・</span><br><span>自校英検取得率照会</span></a></li>
                        <li><a href="javascript:%20void(0);"><span>学年の目標級対英検級</span><br><span>取得率</span></a></li>
                    </ul>
                </li>
                <li><a href="javascript:%20void(0);"><span>学習計画</span></a></li>
            </ul>
		</div>
	</div>
</div>

<div class="clearfix"></div>